### ISSUE TITLE
external app environment (env) field v 1.4

### ISSUE THREAD

**Issue by pine3ree** [litespeedtech/openlitespeed#105]
I am trying to set a PHP_INI_SCAN_DIR using `$VH_ROOT/etc/php.d`, but `$VH_ROOT` is not interpolated to its value.

Is this a bug or just a missing feature?

kind regards,
maks

**Comment by litespeedtech** [comment]
PHP_INI_SCAN_DIR is an ENV that php will read and use it. 
So where did you set this value?

**Comment by pine3ree** [comment]
Hello @litespeedtech ,
It would be nice to be able to set it on a vHost basis using OLS variables, so that we can easily customize the extensions loaded per virtual host. So far I can set PHP_INI_SCAN_DIR per vHost but only without OLS expanded variables, i.e. I need to set manually the whole path like `/my/virtual/host/root/etc/php.d`. It would be nice to be able to use the `$VH_ROOT` variable t define it.
kins regards

**Comment by fabiodemartin** [comment]
I'm trying to do the same thing but it does not work.
Found a post on about this:
https://forum.openlitespeed.org/threads/is-ols-support-any-kind-of-special-variables-like-vh_root-vh_domain.3858/#post-6743

Regards!
