### ISSUE TITLE
IP2Location Doesn't Not Provide Lat/Lon Values

### ISSUE THREAD

**Issue by kiler129** [litespeedtech/openlitespeed#109]
When `DB9LITEBINIPV6` is loaded the following keys are appearing in `$_SERVER` array:
 - IP2LOCATION_ADDR
 - IP2LOCATION_COUNTRY_SHORT
 - IP2LOCATION_COUNTRY_LONG
 - IP2LOCATION_REGION
 - IP2LOCATION_CITY
 - IP2LOCATION_ISP
 - IP2LOCATION_DOMAIN
 - IP2LOCATION_ZIPCODE
 - IP2LOCATION_TIMEZONE
 - IP2LOCATION_NETSPEED
 - IP2LOCATION_IDDCODE
 - IP2LOCATION_AREACODE
 - IP2LOCATION_WEATHERSTATIONCODE
 - IP2LOCATION_WEATHERSTATIONNAME
 - IP2LOCATION_MCC
 - IP2LOCATION_MNC
 - IP2LOCATION_MOBILEBRAND
 - IP2LOCATION_USAGETYPE

There's no lat/lon information, despite the database containing it.

**Comment by rperper** [comment]
Hi,
   I'm one of the OpenLiteSpeed developers here.  This has been a stable module for years and has no known problems and the code appears visually sound.  To be able to identify any issue we'd need to know the exact database you used (where and how you got it so we can try it out) and the IP address you were accessing.  I assume you're talking about the IP2LOCATION_LATITUDE, IP2LOCATION_LONGITUDE (I see IP2LOCATION_ELEVATION missing as well).

   Thanks,
   Bob Perper

**Comment by kiler129** [comment]
Hello Bob,

I believe this module has some problems in one of the new versions, I reported one of them privately via e-mail due to possible security implications here.

The database I use is `DB9LITEBINIPV6`:
```
root@[REDACTED]:/usr/local/lsws/gdata# sha1sum DB9LITEIPV6.bin 
0a2c6e51f47cf592f7ad618f745299981e238666  DB9LITEIPV6.bin
```

The file was downloaded from https://lite.ip2location.com/file-download using automatic method via `http://www.ip2location.com/download/?token=[TOKEN]&file=DB9LITEBINIPV6`.

I was able to replicate this problem on two servers in *local subnet*, one of them has the following config:
```
greg@[redacted]:~$ uname -a
Linux [redacted] 4.15.0-33-generic #36-Ubuntu SMP Wed Aug 15 16:00:05 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
greg@[redacted]:~$  lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic
```
(another one is Debian 9.5 x64).

Both of the servers are running OpenLSWS from repo. Currently both of them run OpenLiteSpeed 1.4.37 as shown in the panel.  Additionally each of the servers has the following PHPs installed:

```
lsphp71/bionic,now 7.1.21-1+bionic amd64 [installed]
lsphp71-common/bionic,bionic,now 7.1.21-1+bionic all [installed,automatic]
lsphp71-json/bionic,now 7.1.21-1+bionic amd64 [installed,automatic]
lsphp71-opcache/bionic,now 7.1.21-1+bionic amd64 [installed,automatic]
lsphp72/bionic,now 7.2.8-1+bionic amd64 [installed]
lsphp72-common/bionic,bionic,now 7.2.8-1+bionic all [installed]
lsphp72-curl/bionic,now 7.2.8-1+bionic amd64 [installed]
lsphp72-intl/bionic,now 7.2.8-1+bionic amd64 [installed]
lsphp72-json/bionic,now 7.2.8-1+bionic amd64 [installed]
lsphp72-mysql/bionic,now 7.2.8-1+bionic amd64 [installed]
lsphp72-opcache/bionic,now 7.2.8-1+bionic amd64 [installed]
lsphp72-sqlite3/bionic,now 7.2.8-1+bionic amd64 [installed]
```

Here's the example printout from `$_SERVER`:
```

array(53) {
  ["PATH"]=>
  string(13) "/bin:/usr/bin"
  ["HTTP_ACCEPT_ENCODING"]=>
  string(17) "gzip, deflate, br"
  ["HTTP_ACCEPT_LANGUAGE"]=>
  string(14) "en-US,en;q=0.9"
  ["HTTP_COOKIE"]=>
  string(384) "[redacted]"
  ["HTTP_HOST"]=>
  string(14) "127.0.0.1:7000"
  ["HTTP_USER_AGENT"]=>
  string(105) "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36"
  ["HTTP_UPGRADE_INSECURE_REQUESTS"]=>
  string(1) "1"
  ["HTTP_DNT"]=>
  string(1) "1"
  ["HTTP_ACCEPT"]=>
  string(85) "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8"
  ["DOCUMENT_ROOT"]=>
  string(39) "/[redacted]/public"
  ["REMOTE_ADDR"]=>
  string(9) "127.0.0.1"
  ["REMOTE_PORT"]=>
  string(5) "60058"
  ["SERVER_ADDR"]=>
  string(9) "127.0.0.1"
  ["SERVER_NAME"]=>
  string(9) "127.0.0.1"
  ["SERVER_PORT"]=>
  string(4) "7000"
  ["REQUEST_URI"]=>
  string(1) "/"
  ["IP2LOCATION_ADDR"]=>
  string(9) "127.0.0.1"
  ["IP2LOCATION_COUNTRY_SHORT"]=>
  string(1) "-"
  ["IP2LOCATION_COUNTRY_LONG"]=>
  string(1) "-"
  ["IP2LOCATION_REGION"]=>
  string(1) "-"
  ["IP2LOCATION_CITY"]=>
  string(1) "-"
  ["IP2LOCATION_ISP"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_DOMAIN"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_ZIPCODE"]=>
  string(1) "-"
  ["IP2LOCATION_TIMEZONE"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_NETSPEED"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_IDDCODE"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_AREACODE"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_WEATHERSTATIONCODE"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_WEATHERSTATIONNAME"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_MCC"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_MNC"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_MOBILEBRAND"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["IP2LOCATION_USAGETYPE"]=>
  string(83) "This parameter is unavailable for selected data file. Please upgrade the data file."
  ["HTTPS"]=>
  string(2) "on"
  ["HAVE_REWITE"]=>
  string(1) "1"
  ["X_SPDY"]=>
  string(6) "HTTP/2"
  ["SSL_VERSION"]=>
  string(7) "TLSv1.3"
  ["SSL_SESSION_ID"]=>
  string(0) ""
  ["SSL_CIPHER"]=>
  string(22) "AEAD-AES128-GCM-SHA256"
  ["SSL_CIPHER_USEKEYSIZE"]=>
  string(3) "128"
  ["SSL_CIPHER_ALGKEYSIZE"]=>
  string(3) "128"
  ["LSWS_EDITION"]=>
  string(20) "Openlitespeed 1.4.37"
  ["X-LSCACHE"]=>
  string(10) "on,crawler"
  ["SCRIPT_FILENAME"]=>
  string(49) "/[redacted]/public/index.php"
  ["QUERY_STRING"]=>
  string(0) ""
  ["SCRIPT_NAME"]=>
  string(10) "/index.php"
  ["SERVER_PROTOCOL"]=>
  string(8) "HTTP/1.1"
  ["SERVER_SOFTWARE"]=>
  string(21) "LiteSpeed/1.4.37 Open"
  ["REQUEST_METHOD"]=>
  string(3) "GET"
  ["PHP_SELF"]=>
  string(10) "/index.php"
  ["REQUEST_TIME_FLOAT"]=>
  float(1535584391.2575)
  ["REQUEST_TIME"]=>
  int(1535584391)
}
```

Let me know if you need any more details. Do you think it may be related to https://github.com/litespeedtech/openlitespeed/issues/108?

**Comment by kiler129** [comment]
Additionally the settings for IP2Location seems to be not working correctly. Ignoring the label for type of caching the geolocation is **always** enabled, no matter what you set.

On Server Configuration > General > Enable GeoLocation Lookup I chosen "No". Additionally on Virtual Hosts > [Name] > General > Enable GeoLocation Lookup I also picked "No". The variables are still appearing in `$_SERVER`. The only way to get rid of them is to specify wrong path in "IP2Location DB File Path".

**Comment by rperper** [comment]
This appears to be a separate issue as well, an issue with the user interface.  Can you please open a support ticket on our forum to report the user interface issue so that it can be routed to the right person.  That has to be done from you so that the person can get directly to you for the issue.
Thanks,

Bob

**Comment by litespeedtech** [comment]
I will look at the code and reply you later.
Thanks.
David

**Comment by litespeedtech** [comment]
I reviewed the code and discussed with other developers. 
Actually this is correct.
Ip2Loc: when you setup the right DB, it will be turned on;
IpGeo: this is depended on your setting of "enableIpGeo", so we have Server/Vhost/Context levels setting.
You said you tuned off the setting, it is only for IpGeo. For the Ip2Loc, if you provide a wrong path or empty path, then it is turned off.
Thanks.
David

**Comment by kiler129** [comment]
@litespeedtech So you're saying the switch is ineffective for IP2Location? This seems strange, since I definitely don't want to put load on each request to the application if I know all location requests are served via a single route.

Is there a known problem with implementing this or just nobody had time to look at this? ;) If it's the second I may try to patch it to check the flag for IP2Location too.
