### ISSUE TITLE
Memory leak & segfault in 1.4.37

### ISSUE THREAD

**Issue by kiler129** [litespeedtech/openlitespeed#110]
I'm currently running OpenLSWS on Debian 9.5 x64. All components are installed from repository offered by LSWS. Today I discovered my server crashed and the logs are full of messages like following:

```
Fatal Error Fatal Error Unable to allocate shared memory segment of 268435456 bytes: 
shmget: File exists (17)
Unable to allocate shared memory segment of 268435456 bytes: shmat: Cannot allocate memory (12)
openlitespeed (lshttpd - #02): httpsession.cpp:812: int HttpSession::processUnpackedHeaders(): Assertion `m_request.getStatus() == HttpReq::HEADER_OK' failed.
sh: 1: gdb: not found
sh: 1: mailx: not found
```

Additionally kernel log contains the following message:
```
[31728.381227] litespeed[602]: segfault at 7f79b4d0274c ip 0000564c153c60ee sp 00007ffebd6fe440 error 4 in openlitespeed[564c15263000+3f9000]
```

I wasn't able to locate coredump. Server is not low on memory (3.8GB free of 4GB).

### Versions
`Linux wtm-lnx-25 4.9.0-8-amd64 #1 SMP Debian 4.9.110-3+deb9u4 (2018-08-21) x86_64 GNU/Linux`
```
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.5 (stretch)
Release:	9.5
Codename:	stretch
```
```
LiteSpeed/1.4.37 Open
	module versions:
	modpagespeed 2.1-1.11.33.4
	cache 1.57
	modinspector 1.1
	uploadprogress 1.1
	mod_security 1.1
```

**Comment by litespeedtech** [comment]
We changed a lot in these code in the latest release. Can you check the latest version?
Thanks.
