### ISSUE TITLE
openlitespeed 1.4.40 core dump

### ISSUE THREAD

**Issue by diegomontoya** [litespeedtech/openlitespeed#114]
Using RPM binary from litespeed repo for Centos 6. 

Core was generated by `openlitespee'.
Program terminated with signal 11, Segmentation fault.
#0  incRef (this=0xa6c0860, pData=0x7571655270747448) at ../../src/util/refcounter.h:31
31      ../../src/util/refcounter.h: No such file or directory.
        in ../../src/util/refcounter.h
Missing separate debuginfos, use: debuginfo-install GeoIP-1.6.5-1.el6.x86_64 expat-2.0.1-13.el6_8.x86_64 glibc-2.12-1.212.el6.x86_64 libgcc-4.4.7-23.el6.x86_64 libstdc++-4.4.7-23.el6.x86_64 nss-softokn-freebl-3.14.3-23.3.el6_8.x86_64 pcre-7.8-7.el6.x86_64
(gdb) bt
#0  incRef (this=0xa6c0860, pData=0x7571655270747448) at ../../src/util/refcounter.h:31
#1  SendFileInfo::setFileData (this=0xa6c0860, pData=0x7571655270747448) at sendfileinfo.cpp:55
#2  0x0000000000505eb4 in HttpSession::assignHandler (this=0xa6c0340, pHandler=<value optimized out>) at httpsession.cpp:1773
#3  0x0000000000506417 in HttpSession::handlerProcess (this=0xa6c0340, pHandler=<value optimized out>) at httpsession.cpp:1718
#4  0x0000000000508dbc in HttpSession::onWriteEx (this=0xa6c0340) at httpsession.cpp:2123
#5  0x0000000000508c69 in HttpSession::onTimerEx (this=0xa6c0340) at httpsession.cpp:2560
#6  0x000000000052cdcf in H2Connection::timerRoutine (this=0x7283220) at h2connection.cpp:1419
#7  0x00000000004f3edd in NtwkIOLink::onTimer (this=0x6317200) at ntwkiolink.cpp:903
#8  0x000000000055ccb3 in ReactorIndex::timerExec (this=0x2663e68) at reactorindex.cpp:74
#9  0x00000000004e5352 in processTimerNew (this=<value optimized out>) at eventdispatcher.cpp:214
#10 EventDispatcher::run (this=<value optimized out>) at eventdispatcher.cpp:242
#11 0x00000000004c742c in HttpServerImpl::start (this=0x25f39e0) at httpserver.cpp:500
#12 0x00000000004c02c9 in LshttpdMain::main (this=0x25f3770, argc=<value optimized out>, argv=0x7fffea8e8ee8) at lshttpdmain.cpp:978
#13 0x000000000049f188 in main (argc=1, argv=0x7fffea8e8ee8) at main.cpp:109
(gdb) erver.cpp:500

**Comment by litespeedtech** [comment]
Is this one easy to reproduce?
If yes, can you download https://openlitespeed.org/packages/openlitespeed-1.4.40.dbg.tgz which is the debug version and run with this version?
You just need to put the file in your /usr/local/lsws/bin/, stop the service first and run it such as />./openlitespeed-1.4.40.dbg.
If it create a core dump file again, then please send to us.
Thanks.
David

**Comment by diegomontoya** [comment]
@david The debug mode dumps at the same position and can confirm the segmentation faults are gone once we have disabled mmap in ols config.

**Comment by litespeedtech** [comment]
Can you test with 1.4.41? Since we fixed some memory relate bug in this release.
Thanks.
David
