### ISSUE TITLE
Pernament redirects setup as context are randomly failing

### ISSUE THREAD

**Issue by kiler129** [litespeedtech/openlitespeed#118]
We found a weird behavior while setting up a simple 301 redirects in context (assuming they are faster than using `RewriteRule` since they're native to lsws). The redirect is a simply redirecting `/abc/` to an external domain.

While using HTTP2 and testing with curl the server randomly responds with proper 301 or passes the request to rewrite rules which are causing 404 (since it goes to the application).

What I observed is first request after server reload is always a proper redirect, later on it's literally random - you may get 5 successful redirects and one failure or 5x 404 and a single 301.

**Comment by litespeedtech** [comment]
Please give us more details so that we can reproduce and fix the bugs.
Thanks.
David

**Comment by litespeedtech** [comment]
This is fixed in 1.4.47 which will be released soon.
Thanks.
David
