### ISSUE TITLE
compile error on Centos7.x

### ISSUE THREAD

**Issue by zhengshuxin** [litespeedtech/openlitespeed#121]
Hi, when I build the server, I've got the error info as below:
iptogeo.h:26:19: fatal error: GeoIP.h: No such file or directory
 #include "GeoIP.h"

Thanks
--- zsx

**Comment by qtwrk** [comment]
Hi,

Did you install all the dependencies ?

Or did you run some ./configure flags ?

Best regards

**Comment by zhengshuxin** [comment]
I just use: ./configure; make. And the error above happened.

**Comment by qtwrk** [comment]
you did install package needed before compile, right?

```
yum install epel-release
yum install gcc gcc-c++ make autoconf glibc rcs
yum install pcre-devel openssl-devel expat-devel geoip-devel zlib-devel udns-devel
```

**Comment by zhengshuxin** [comment]
I've built the project ok after 'yum install  geoip-devel'. Thanks very much!
--- zsx
