### ISSUE TITLE
Add a var to vHost

### ISSUE THREAD

**Issue by khaiphan9x** [litespeedtech/openlitespeed#122]
Please add $SERVER_IP var, I need it to configure some things!
Allow/Deny IP…
Thanks!

**Comment by khaiphan9x** [comment]
It seems that this problem has not been noticed.  Even so, the development team should answer me!

**Comment by litespeedtech** [comment]
Do you mean in config file? 
If yes, my answer is no, we do not have. Since all the variables are by defined and they are made by combination, appending and so on.
BTW, server's IPs may be not only one and it need to gotten by run some command.

**Comment by khaiphan9x** [comment]
Is there a similar way at this time? because I really need it. Thank you!

**Comment by litespeedtech** [comment]
I think maybe you can use some script to get the IP and use it in you script, or even update the conf file if you need it in the conf.

**Comment by khaiphan9x** [comment]
It seems that my knowledge is not enough.  Is there any way to get URI Segment in conf?

**Comment by litespeedtech** [comment]
I think maybe you want to set the different context which has the URI assigned and you will know your URI in that context.

**Comment by khaiphan9x** [comment]
Its not work!
![alt text](https://i.imgur.com/nQISZXY.jpg)

**Comment by khaiphan9x** [comment]
I'm try with .htaccess it also doesnt work!

    order deny, allow 

    deny from all 

    allow from 127.0.0.1

**Comment by litespeedtech** [comment]
Close this answered old issue.
