### ISSUE TITLE
Cannot login on wp on SSL

### ISSUE THREAD

**Issue by navotera** [litespeedtech/openlitespeed#123]
I cannot login to WP on SSL if I activated the Mod_security. No error on web page shown, just infinite loading on the browser tab bar.

On Mod Security disabled, it works flawlessly.

I am using Cyberpanel 1.8.1

Previous issues that get closed on cyberpanel as say that this is OLS bug. 
https://github.com/usmannasir/cyberpanel/issues/73

**Comment by litespeedtech** [comment]
What version OLS you are using?
If it is not 1.4.46, please just update to this version and try again.

**Comment by litespeedtech** [comment]
Since this issue was happened 3 months ago and we did fix some relate bugs in the recent releases.
If you still have the same issue, please let us know.
Thanks.
