### ISSUE TITLE
Vary: Accept is ignored

### ISSUE THREAD

**Issue by Toflar** [litespeedtech/openlitespeed#127]
Apparently the `Vary: Accept` header is ignored which is a real issue for API's that want to serve the same content in different formats.

For example you have an endpoint that serves books: `https://foobar.com/books`.
Now you want to give the API users the possibility to choose between JSON and XML. The proper way of doing that is by having them send the `Accept: application/json` or `Accept: application/xml` headers. The response then must contain `Vary: Accept` so the cache adds two different entries for this resource.

**Comment by litespeedtech** [comment]
I am going to do this.
Thanks.
David

**Comment by litespeedtech** [comment]
It is done in the 1.4.47. 
And it will be released soon.
