### ISSUE TITLE
Purge endpoint should delete all variants of the same path

### ISSUE THREAD

**Issue by Toflar** [litespeedtech/openlitespeed#128]
Given I request `/books` and it does have a representation in JSON and XML, I would add `Vary: Accept` in the response. This needs https://github.com/litespeedtech/openlitespeed/issues/127 to be fixed first.

So I'll end up having 2 variants of `/books` in the cache.
Now when I send `PURGE /books`, I expect **both** entries to be invalidated.
This is currently not the case.

Also see [Varnish](https://varnish-cache.org/docs/6.2/users-guide/purging.html?highlight=purging#http-purging):

> This will remove all variants as defined by `Vary`.

**Comment by litespeedtech** [comment]
I will add this feature.
Thanks.
David

**Comment by litespeedtech** [comment]
It is added and will be in the next release.
FYI.
David
