### ISSUE TITLE
HTTP/2 timeout in 20 seconds for POST request

### ISSUE THREAD

**Issue by jesusvilla** [litespeedtech/openlitespeed#129]
First I want to congratulate you for your excellent project. Currently I have OpenLiteSpeed ​​to replace Apache, this brings the HTTP / 2 by default but the connection is closed (err_spdy_protocol_error) when I make POST requests that take more than 20 seconds. 
How can I correct this? Will I have to make some configuration on OpenLiteSpeed? I'm using OpenLiteSpeed 1.4.45. 
I hope you can help me.

**Comment by litespeedtech** [comment]
We did fix a bug about http2 in 1.4.46.  Can you try 1.4.46?
If still get errors, please feel free to contact us.
Thank you.
David

**Comment by jesusvilla** [comment]
Thank you very much for your prompt response. Can I perform an update without losing the configuration and downtime? I work on centos 6 and I installed them with rpm.  [(Doc)](https://openlitespeed.org/kb/step-by-step-install-ols/)

**Comment by jesusvilla** [comment]
Ready. Thank you. I just did: `yum update openlitespeed `and then service lsws restart. Great project, thank you very much.
