### ISSUE TITLE
How to configure vhost log error only?

### ISSUE THREAD

**Issue by jesusvilla** [litespeedtech/openlitespeed#130]
I have a vhost template where the virtual host logs are always increasing and those files are not automatically deleted. I just want the errors to be recorded, for that I set the log level to 'ERROR' but it ignores me. Sorry for the inconvenience, but I can not find documentation to do what I want.

**Comment by jesusvilla** [comment]
Only register in log:
```
GET /api/action?params=%7B%22id%22:23576%7D HTTP/1.1
host: new.host.com
accept: application/json, text/plain, */*
origin: https://new2.host.com
Auth: *******hash*****
accept-language: en
user-agent: Mozilla/5.0 ****
referer: https://new2.host.com/other
accept-encoding: gzip 
x-requested-with: com.host.new
X-Forwarded-Host: new.host.com
X-Forwarded-Proto: https
X-Forwarded-For: ***.*.**.**
```

**Comment by litespeedtech** [comment]
what is you config?

**Comment by jesusvilla** [comment]
`
vhRoot                    $SERVER_ROOT/$VH_NAME/
configFile                $SERVER_ROOT/$VH_NAME/conf/vhconf.conf

virtualHostConfig  {
  docRoot                 /home/user/repo/html/$VH_NAME/
  adminEmails             user@user.com
  enableGzip              1
  enableIpGeo             1

  errorlog $VH_ROOT/logs/error.log {
    useServer             0
    logLevel              WARN
    rollingSize           4M
  }

  accesslog $VH_ROOT/logs/control.log {
    useServer             2
    rollingSize           4M
    keepDays              2
  }

  index  {
    useServer             1
    indexFiles            index.php, index.html, index.phtml
  }

  accessControl  {
    allow                 *
  }

  context / {
    location              $DOC_ROOT/
    allowBrowse           1
    extraHeaders          <<<END_extraHeaders
Header unset Server
Header unset X-Powered-By
Header set X-XSS-Protection "1; mode=block"
Header set X-Content-Type-Options "nosniff"
Header set Strict-Transport-Security: "max-age=31536000; includeSubDomains"
Header set X-Frame-Options "SAMEORIGIN"
Header set Feature-Policy "camera *; fullscreen *; geolocation *; microphone 'self'"
    END_extraHeaders


    rewrite  {
      enable              1
      base                /
RewriteRule ^api/(.*)$ https://api/$1 [P,L]
   }
 rewrite  {
    enable                1
    autoLoadHtaccess      1
    logLevel              0
RewriteCond %{HTTPS} !on
RewriteCond %{HTTP:X-Forwarded-Proto} !https
RewriteRule ^(.*)$ https://%{SERVER_NAME}%{REQUEST_URI} [R,L]
  }

  vhssl  {
    keyFile               /etc/httpd/extra/SSL/web.host.com/file.key
    certFile              /etc/httpd/extra/SSL/web.host.com/file.crt
    CACertFile            /etc/httpd/extra/SSL/web.host.com/fileca.crt
  }
}

`

**Comment by jesusvilla** [comment]
Help me please. I already gave my configuration.

**Comment by litespeedtech** [comment]
Is there any other errors in you server errorlog?
Did you use webadmin to do the config?

**Comment by jesusvilla** [comment]
There are no errors in the servers, only those messages that are made from the proxy. Yes, I use WebAdmin to do the config.

**Comment by litespeedtech** [comment]
So if every thing is good, you VHroot is 
vhRoot $SERVER_ROOT/$VH_NAME/
and is errorlog file should be 
$SERVER_ROOT/$VH_NAME/logs/error.log

Do you have such file created? 
Does $SERVER_ROOT/$VH_NAME/logs/ DIR exist?

**Comment by jesusvilla** [comment]
The directories are created with the requested permissions lsadm: lsadm

**Comment by litespeedtech** [comment]
The log will access by server, it is nobody:nobody by default, this is set in the server config (httpd_config.conf).
Can you change your permission and test again?

**Comment by jesusvilla** [comment]
Do you want to change the permissions of my vhost.conf by nobody:nobody? That would not make sense because otherwise it would not create the file or register the proxy logs. I based myself on the following article: [VirtualHost](https://openlitespeed.org/kb/setting-up-name-based-virtual-hosting-on-openlitespeed/)

**Comment by jesusvilla** [comment]
I tried changing the permissions to nobody:nobody and the virtualhost does not work.

**Comment by jesusvilla** [comment]
The error is in VirtualHost Template, I have created an external application from `Server Configuration> External App` and then add this to the VirtualHost Template:
`RewriteRule ^url /(.*)$ https://api/$1 [P]`

**Comment by jesusvilla** [comment]
Could you help me? Keep logging the proxy logs as an error.

**Comment by jesusvilla** [comment]
Please update the ubuntu repositories to test the latest version of openlitespeed (v1.4.47), it seems that this corrects the logs.

**Comment by jesusvilla** [comment]
> Please update the ubuntu repositories to test the latest version of openlitespeed (v1.4.47), it seems that this corrects the logs.

The case still persists despite updating to 1.4.47

**Comment by litespeedtech** [comment]
The conf file should still be lsadm:lsadm because it need to be access by webAdmin which is lsadm.
But the log files should be nobody:noby, becase openlitespeed run as nobody:nobody.
Can you change the permission of the log file? Also for the directory, it also need to be access by nobody.
Thanks.,
David

**Comment by litespeedtech** [comment]
Close this answered issue.
