### ISSUE TITLE
Update for repository ubuntu

### ISSUE THREAD

**Issue by jesusvilla** [litespeedtech/openlitespeed#132]
Hi,
The latest version of openlitespeed (v1.4.47) for the Ubuntu repositories [(http://rpms.litespeedtech.com/)](https://rpms.litespeedtech.com) is not yet available. Can you update it?

**Comment by litespeedtech** [comment]
It seems we have the RPMs for Ubuntu. 
Can you check again?
Thanks.
David

**Comment by litespeedtech** [comment]
We add support for ubuntu for a long time. Close it.
