### ISSUE TITLE
The repository started supporting CentOS/RHEL 8.

### ISSUE THREAD

**Issue by ivmm** [litespeedtech/openlitespeed#133]
LiteSpeed ​​and OpenLiteSpeed ​​about CentOS's depot, need to be updated to support RHEL8.

RHEL 8 was officially released in May, and OracleLinux 8 was released in beta. Checking the update status of CentOS8 can be found that it is almost in the final stage, and it may be officially released in August.

Http://rpms.litespeedtech.com/centos/ can support the latest system version as soon as possible, especially the new system OpenSSL 1.1.1 can make OLS or TLS1.3 experience out of the box.

**Comment by litespeedtech** [comment]
All of our pre-built package, source code package and ols1clk do support centos8 now.
Thank you for your feedback.
