### ISSUE TITLE
compile error on ARM

### ISSUE THREAD

**Issue by ACGunion** [litespeedtech/openlitespeed#136]
I'm compile version 1.5.5 under a arm64 instance 
`libtool: link: g++ -g -O2 -pg -D_GLIBCXX_USE_CXX11_ABI=0 -fstack-protector -Wl,--export-dynamic -D_GLIBCXX_USE_CXX11_ABI=0 -o openlitespeed prelinkedmods.o httpdtest.o main.o httpfetchdriver.o httpfetch.o linkobjpool.o pidfile.o hashdatacache.o keydata.o tlinklist.o rlimits.o duplicable.o gfactory.o fdpass.o pcregex.o autostr.o staticobj.o pool.o hashstringmap.o ghash.o emailsender.o guardedapp.o crashguard.o iconnection.o dlinkqueue.o connpool.o compressor.o brotlibuf.o gzipbuf.o vmembuf.o blockbuf.o stringlist.o semaphore.o refcounter.o gpointerlist.o linkedobj.o objpool.o gpath.o poolalloc.o env.o xmlnode.o iovec.o accesscontrol.o signalutil.o loopbuf.o stringtool.o tsingleton.o pcutil.o daemonize.o configentry.o datetime.o resourcepool.o linkedqueue.o httputil.o radixtree.o profiletime.o partitioninfo.o nicdetect.o systeminfo.o ni_fio.o filtermatch.o ls_aho.o ls_base64.o ls_buf.o ls_confparser.o ls_crc64.o ls_dlinkq.o ls_fileio.o ls_hash.o ls_lfqueue.o ls_lfstack.o ls_link.o ls_lock.o ls_loopbuf.o ls_map.o ls_md5.o ls_mpscq.o ls_objarray.o ls_objpool.o ls_pcreg.o ls_pool.o ls_ptrlist.o ls_sha1.o ls_shm.o ls_stack.o ls_str.o ls_strlist.o ls_strtool.o ls_time.o ls_tsstack.o ls_xpool.o xxhash.o offloader.o mtnotifier.o pthreadcond.o pthreadmutex.o pthreadworkqueue.o thread.o workcrew.o worker.o crewworker.o  -L/usr/lib -L/tmp/openlitespeed-1.5.5/udns-0.4/ ./main/libmain.a ./http/libhttp.a ./spdy/libspdy.a ./extensions/libextensions.a ./log4cxx/liblog4cxx.a ./socket/libsocket.a ./sslpp/libsslpp.a ./ssi/libssi.a ./edio/libedio.a ./lsiapi/liblsiapi.a ./modules/libmodules.a ./shm/liblsshm.a ./adns/libadns.a ../ssl/libssl.a ../ssl/libcrypto.a -ludns -lGeoIP /usr/lib/aarch64-linux-gnu/libexpat.so -ldl -lrt -lcrypt -lpcre -lz -lpthread
datetime.o: In function `ls_atomic_dcasv':
/tmp/openlitespeed-1.5.5/src/../include/lsr/ls_atomic.h:157: undefined reference to `__atomic_compare_exchange_16'
/tmp/openlitespeed-1.5.5/src/../include/lsr/ls_atomic.h:157: undefined reference to `__atomic_compare_exchange_16'
ls_lfqueue.o: In function `ls_atomic_dcasv':
/tmp/openlitespeed-1.5.5/src/../include/lsr/ls_atomic.h:155: undefined reference to `__atomic_compare_exchange_16'
/tmp/openlitespeed-1.5.5/src/../include/lsr/ls_atomic.h:155: undefined reference to `__atomic_compare_exchange_16'
ls_lfstack.o: In function `ls_atomic_dcas':
/tmp/openlitespeed-1.5.5/src/../include/lsr/ls_atomic.h:146: undefined reference to `__atomic_compare_exchange_16'
ls_lfstack.o:/tmp/openlitespeed-1.5.5/src/../include/lsr/ls_atomic.h:146: more undefined references to `__atomic_compare_exchange_16' follow
collect2: error: ld returned 1 exit status
Makefile:661: recipe for target 'openlitespeed' failed
make[3]: *** [openlitespeed] Error 1
make[3]: Leaving directory '/tmp/openlitespeed-1.5.5/src'
Makefile:2213: recipe for target 'all-recursive' failed
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory '/tmp/openlitespeed-1.5.5/src'
Makefile:561: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/tmp/openlitespeed-1.5.5/src'
Makefile:410: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
`

**Comment by http2benchmark** [comment]
same as #107 
Need to link against libatomic.a with link option "-latomic", just manually update the Makefile.
