### ISSUE TITLE
http://open.litespeedtech.com links to invalid SSL Certificate

### ISSUE THREAD

**Issue by timofeycom** [litespeedtech/openlitespeed#137]
The description of this repo links to http://open.litespeedtech.com, which then redirects to HTTPS. Upon redirection, the page shows a warning, "Connection Is Not Private".

Screenshot of the SSL/TLS error:
![Screen Shot 2019-08-28 at 12 10 30 PM](https://user-images.githubusercontent.com/26501155/63885667-b4a82180-c98d-11e9-8809-889a51fe6dc2.png)

I was able to replicate it on the latest versions of Chrome and Safari on a Mac Mojave, with cleared cookies.

Possible solution: Update the URL to https://openlitespeed.org/ or update the SSL/TLS certificate on https://open.litespeedtech.com.

**Comment by litespeedtech** [comment]
Thanks.
We use the https://openlitespeed.org/ directly now.

**Comment by cmsnegar** [comment]
u test firefox  or opera.  google chrome  not support SSL  openlitspeed
