### ISSUE TITLE
Change domaine name on AWS installation of Wordpress

### ISSUE THREAD

**Issue by beeriz** [litespeedtech/openlitespeed#138]
Hello.

Is it possible to modify the domain name selected during the installation of the AWS Wordpress version?

Or should I create a new vhost and link it to an existing Wordpress installation? If yes, how to do it ?

Image : https://aws.amazon.com/marketplace/pp/B07KSC2QQN?qid=1567528326849
OS : Ubuntu

Thank you!

**Comment by Code-Egg** [comment]
Hi,

If you followed https://docs.litespeedtech.com/cloud/wordpress/#step-3 to setup a domain from ssh and want to change it, simply follow [this step](https://docs.litespeedtech.com/cloud/wordpress/#step-2-add-domain-to-listener) to modify the domain through listener. 

Best

**Comment by beeriz** [comment]
Hey. when changing the domaine name and then requesting an SSL certificate I'm getting an error with certbot (404 not found) and when visiting the url my self I'm seeing the page 404 of Litesepeed. 

What I'm missing?
I did exactly like mentioned above

**Comment by Code-Egg** [comment]
Hi,

Certbot itself will auto setup in cron job ahead and if you setup though the script then the lsws restart hook should auto setup as well.  
https://github.com/litespeedtech/ls-cloud-image/blob/master/Setup/domainsetup.sh#L176

You can also manually check here '/etc/cron.d/certbot'. 

Best

**Comment by litespeedtech** [comment]
Close this answered issue.
