### ISSUE TITLE
[Question] HTTPS 1.1 vs 2 vs 3 (large blob download)

### ISSUE THREAD

**Issue by h0ax-ki1l3r** [litespeedtech/openlitespeed#143]
Hi,

I have used your platform to do large blob downloads (e.g. 1G) files and force the browser to not exceed more than 1 parallel connection for download. I used Chrome. 

For QUIC settings, I set it to Cubic such that congestion control remains the same between the server's TCP, client's TCP and QUIC.

I see that HTTP 3 is much faster than HTTP 2 and 1.1.
For instance,
HTTPS 1.1 took 55 seconds
HTTP 2 took 50 seconds
HTTP 3 took 35 seconds.

Can anyone explain:

    Why HTTP 2 is faster than HTTP 1.1?
    Why is HTTP 3 faster than HTTP 1.1 and HTTP 2?

I know the overheads, but such high difference is what I am not sure.

Any thoughts?

**Comment by litespeedtech** [comment]
You need to review the http2 and http3 spec, seems they are designed to be faster, especially http3.

**Comment by litespeedtech** [comment]
Close this long time replied question.
