### ISSUE TITLE
How to compile OLS to lscpd, and support hard coding of Python and PHP. Python path hard to write to the program.

### ISSUE THREAD

**Issue by killjin** [litespeedtech/openlitespeed#144]
How to compile OLS to lscpd, and support hard coding of Python and PHP. Python path hard to write to the program.

**Comment by litespeedtech** [comment]
Use OLS 1.4 branch source code, such as 1.4.50, because you can use configure in this branch.
Use --with-lscpd parameter for the configure and make.
It should create a binary for lscpd, you need to rename openlitespeed to lscpd.
Cyberpanle is using lscpd.
Thanks
David
