### ISSUE TITLE
No rule to make target '.deps/xxhash.Po' Error

### ISSUE THREAD

**Issue by navjotjsingh** [litespeedtech/openlitespeed#146]
I am trying to install Openlitespeed 1.6.4 from source in Fedora 31 and I keep getting this error

```
$ make && make install
Making all in src
make[1]: Entering directory '/home/navjot/openlitespeed-1.6.4/src'
Makefile:760: .deps/xxhash.Po: No such file or directory
make[1]: *** No rule to make target '.deps/xxhash.Po'.  Stop.
make[1]: Leaving directory '/home/navjot/openlitespeed-1.6.4/src'
make: *** [Makefile:409: all-recursive] Error 1
```

How to fix this? I have installed all the dependencies. Followed the instructions from https://openlitespeed.org/kb/installation-from-source-code/

**Comment by litespeedtech** [comment]
Hi,

For 1.6.4, we provide build.sh to do the compiling things and install.sh to do the installations.
Can you just run the ./build.sh first?
Or try to use our pre-built packages?

Thanks.
David

**Comment by navjotjsingh** [comment]
I tried that. Got the following error.

```
No match for argument: epel-release
Error: Unable to find a match: epel-release
This script only works on 6/7/8 for centos family._Static_assert

```

I need to install OpenliteSpeed in Fedora 31. How to do that?

**Comment by litespeedtech** [comment]
I tested on Fedora (maybe 31) and I did get some error while running build.sh.
But use our pre-built package is a good choice.
The downloading page is here,
https://openlitespeed.org/downloads/

**Comment by litespeedtech** [comment]
I will do some updating for the build.sh, but the changes seems to be not that easy.
For now, please use the pre-built package.

**Comment by litespeedtech** [comment]
Now, for Fedora 31, need to use the pre-built package. 
I will update the script to make it work on Fedora in the future.
Thanks
David
