### ISSUE TITLE
Some libraries cannot be compiled if CMake version 3 or later is not included in the standard repository

### ISSUE THREAD

**Issue by KotoishiHeart** [litespeedtech/openlitespeed#149]
Some Linux distributions such as Amazon Linux 2 have cmake 2.8 as the standard package.

As a result, some libraries require cmake 3.0 or higher for compilation and cannot be installed.

Is it possible to change so that cmake is always installed from the source code?

**Comment by litespeedtech** [comment]
I updated the build.sh which will check the cmake version and if lower than 3.0.0, it will build cmake from source code. 
I tested with centos 7, ubuntu 18 and freebsd 11, all results are good.
It will be first in the next release 1.6.5.
Thanks
David

**Comment by litespeedtech** [comment]
1.6.5 is released today. Please try this version.
This issue will be closed.
