### ISSUE TITLE
Logs can fill up storage free space

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/openlitespeed#153]
This is a enchancement request.

**To avoid situations like**
- #148 
- https://github.com/usmannasir/cyberpanel/issues/196

Ols must manage better the log rotation. Is not good for Ols to fill up the free storage space and compromise the server. If the server has no free space, Ols and the OS will break.

**What I recommend:**
- manage a limit about log space usage
- compress the logs

I know manage a limit can be something not easy to implement and do QA, but at least compress the rotated log files will save a lot of problems.

**Comment by litespeedtech** [comment]
Usually it won't use a large mount of your space when it is set to errorlog ERROR or DEBUG low.
I will do some tuning of that part of code to avoid the crash when it happens.

**Comment by franciscopaniskaseker** [comment]
@litespeedtech there is no option yet to compress and rotate those logs? I have other server that is filling all the space due some php stacktraces. I know those errors need to be fixed, however compress and rotation are very basic things and can be controlled by journal, rsyslog etc.

**Comment by girishalpha** [comment]
> @litespeedtech there is no option yet to compress and rotate those logs? I have other server that is filling all the space due some php stacktraces. I know those errors need to be fixed, however compress and rotation are very basic things and can be controlled by journal, rsyslog etc.

Yes I agree with this, compress and rotate is something that needed.

**Comment by litespeedlars** [comment]
For enterprise you could check here: https://www.litespeedtech.com/docs/webserver/config/slog#log_compressArchive

Similar settings should be available for OLS under the logs tab.

**Comment by eveneme** [comment]
+1 /usr/local/lsws/logs/security_audit.log
is constantly growing. It’s almost 4 GB now.
