### ISSUE TITLE
Support a UDP (QUIC) only listener

### ISSUE THREAD

**Issue by Marlinc** [litespeedtech/openlitespeed#156]
Currently it's impossible to run LiteSpeed alongside another webserver as LiteSpeed always tries to bind to TCP. It would be very useful if we could configure a listener to only listen on UDP.

The scenario I'm currently running it is that I'm using Traefik as load balancer (I can't really switch away from it) but would also like to have Google QUIC and IETF QUIC with HTTP/3 available.

Originally I tried letting LiteSpeed listen on port 4433 and having that port in `Alt-Svc`, unfortunately it appears browsers don't respect that port yet. This results in it being impossible to have both one webserver for HTTP/1.1 - HTTP/2 and LiteSpeed for HTTP/2-QUIC and HTTP/3.

**Comment by litespeedtech** [comment]
We are not likely doing that in Openlitespeed, our other product may support.
Thank you.
David
