### ISSUE TITLE
Bug with OpenLiteSpeed

### ISSUE THREAD

**Issue by thomassiskos** [litespeedtech/openlitespeed#160]
After update 1.9.3 problem OpenLiteSpeed stop end put manual to start, change php 7.2 to 7.3 to 7.4 and back and again stop.
The site wordpress does not load images.
Does not load the entire site

**Comment by darkspadez** [comment]
Do you mean 1.6.3? Please try 1.6.9 of OpenLiteSpeed to see if it fixes your issue.

**Comment by litespeedtech** [comment]
If still have problem with the latest OLS release, please let us know.
