### ISSUE TITLE
Invalid repo name under Debian 10

### ISSUE THREAD

**Issue by SquitoHUN** [litespeedtech/openlitespeed#161]
When trying to install OpenLiteSpeed V 1.5.11 (Binary downloaded from OLS website) under Debian 10 aka buster the installer creates a repo file without the nickname of the distro (missing "buster"), so during the installation you get this error message:
> E: Malformed entry 1 in list file /etc/apt/sources.list.d/lst_debian_repo.list (Component)

Content of lst_debian_repo.list:
> deb http://rpms.litespeedtech.com/debian/  main

**Comment by JOduMonT** [comment]
while buster is not officially supported ;)
simply

`echo "deb http://rpms.litespeedtech.com/debian/ buster main" > /etc/apt/sources.list.d/lst_debian_repo.list`

than rerun the installation it will work

**Comment by litespeedtech** [comment]
Debian 10 has been official supported.
