### ISSUE TITLE
Editing vhost context returns 404

### ISSUE THREAD

**Issue by jasonmoonen** [litespeedtech/openlitespeed#164]
We are running the latest version of openlitespeed (1.6.8)

On a vhost we've added this expression: exp:^(.(?<!/content)((/help)|(/setup)).)$

I noticed that it uses javascript to load the configuration and when it does it returns an internal server error (500) on /view/confMgr.php

**Comment by darkspadez** [comment]
Is this still the case on 1.6.11?

**Comment by jasonmoonen** [comment]
> Is this still the case on 1.6.11?

yep still the case, here's a video: https://youtu.be/Juy5gDdwbnU

**Comment by litespeedtech** [comment]
Revisiting this issue. Sorry for late reply. I'm wondering what kind of context url you try to match with this regexp? I don't know why there is "<" in the pattern. This character was blocked from input submit, treated as hacking attempt. Can you provide some valid url that you need to match with this pattern?

**Comment by litespeedtech** [comment]
Now I got it, it's a valid PCRE regex. It will be fixed in next 1.6.x & 1.7.x release.

**Comment by therealgilles** [comment]
Happy to hear you're adding extended support for regular expressions :)
