### ISSUE TITLE
Compile source failed cause ModSecurity updated 

### ISSUE THREAD

**Issue by kamitanw** [litespeedtech/openlitespeed#165]
Hello,
I try to compile latest version source,
but there are some errors on modsecurity-ls
`
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:45:5: error: ‘Rules’ does not name a type
     Rules                  *rules_set;
     ^~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:54:5: error: ‘Rules’ does not name a type
     Rules                  *rules_set;
     ^~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp: In function ‘int setSecRule(msc_conf_t*, char*, int, char*)’:
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:108:38: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
         ret = msc_rules_add(pConfig->rules_set, value, &error);
                                      ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:111:43: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
         ret = msc_rules_add_file(pConfig->rules_set, value, &error);
                                           ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:114:45: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
         ret = msc_rules_add_remote(pConfig->rules_set, value, uri, &error);
                                             ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp: In function ‘void* ParseConfig(module_param_info_t*, int, void*, int, const char*)’:
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:161:14: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
     pConfig->rules_set = msc_create_rules_set();
              ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:176:40: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
         ret = msc_rules_merge(pConfig->rules_set, pInitConfig->rules_set,
                                        ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:176:64: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
         ret = msc_rules_merge(pConfig->rules_set, pInitConfig->rules_set,
                                                                ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp: In function ‘void FreeConfig(void*)’:
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:258:32: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
     msc_rules_cleanup(pConfig->rules_set);
                                ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp: In function ‘int createModData(lsi_param_t*, msc_conf_t*)’:
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:344:56: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
                                                  conf->rules_set,
                                                        ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:364:17: error: ‘ModData {aka struct ModData_t}’ has no member named ‘rules_set’
         myData->rules_set = conf->rules_set;
                 ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:364:35: error: ‘msc_conf_t {aka struct msc_conf_t_}’ has no member named ‘rules_set’
         myData->rules_set = conf->rules_set;
                                   ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp: In function ‘int UriMapHook(lsi_param_t*)’:
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:528:5: error: ‘Rules’ was not declared in this scope
     Rules *rules = myData->rules_set;
     ^~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:528:12: error: ‘rules’ was not declared in this scope
     Rules *rules = myData->rules_set;
            ^~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:528:28: error: ‘ModData {aka struct ModData_t}’ has no member named ‘rules_set’
     Rules *rules = myData->rules_set;
                            ^~~~~~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp: In function ‘int respHeaderHook(lsi_param_t*)’:
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:684:5: error: ‘Rules’ was not declared in this scope
     Rules *rules = myData->rules_set;
     ^~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:684:12: error: ‘rules’ was not declared in this scope
     Rules *rules = myData->rules_set;
            ^~~~~
/usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:684:28: error: ‘ModData {aka struct ModData_t}’ has no member named ‘rules_set’
     Rules *rules = myData->rules_set;
                            ^~~~~~~~~
In file included from /usr/local/src/openlitespeed-1.6.8/../thirdparty/include/modsecurity/modsecurity.h:174:0,
                 from /usr/local/src/openlitespeed-1.6.8/src/modules/modsecurity-ls/mod_security.cpp:23:
/usr/local/src/openlitespeed-1.6.8/../thirdparty/include/modsecurity/intervention.h: At global scope:
/usr/local/src/openlitespeed-1.6.8/../thirdparty/include/modsecurity/intervention.h:59:17: warning: ‘void modsecurity::intervention::free(modsecurity::ModSecurityIntervention_t*)’ defined but not used [-Wunused-function]
     static void free(ModSecurityIntervention_t *i) {
                 ^~~~
/usr/local/src/openlitespeed-1.6.8/../thirdparty/include/modsecurity/intervention.h:39:17: warning: ‘void modsecurity::intervention::clean(modsecurity::ModSecurityIntervention_t*)’ defined but not used [-Wunused-function]
     static void clean(ModSecurityIntervention_t *i) {
                 ^~~~~
make[2]: *** [src/modules/modsecurity-ls/CMakeFiles/mod_security.dir/mod_security.cpp.o] Error 1
make[1]: *** [src/modules/modsecurity-ls/CMakeFiles/mod_security.dir/all] Error 2
make: *** [all] Error 2
Start to pack files.
`

I guess cause ModSecurity updated and renamed Rule to RuleSet:
https://github.com/SpiderLabs/ModSecurity/commit/7495675d540b3b3ccce681773205a4fe34daeb64

is it possible to fix it?
Thank you.

**Comment by litespeedtech** [comment]
This is possible. I will update the local lib modsec to check if we can compile.
We do not update the modsec lib every time.
Thank you for your info.

**Comment by litespeedtech** [comment]
We fixed this bug in 1.7.0 and also will fix it in the next 1.6.10.
Thank you.
