### ISSUE TITLE
Model cache erorr Ubuntu permissions

### ISSUE THREAD

**Issue by riyadhali** [litespeedtech/openlitespeed#173]
Dear Technical Support
I am a fan and openlitespeed user
I would like to report a cache model
In Ubuntu 18.04
Model cache  not create folders due to permissions
Despite authorizing the folder cachedata- user(nobody) : group(nogroup)
The problem appeared after deleting the old cachedata folder
Due to the problem of appearing home page (wordpress) on the site, old, days ago.

Version 
1.6.11
and
1.6.13
best regards

**Comment by litespeedtech** [comment]
Hello,

What do you mean by "model cache?"

**Comment by litespeedtech** [comment]
Please check the latest release, if problem persists, please reopen the issue.
