### ISSUE TITLE
Unable to setup mod_security

### ISSUE THREAD

**Issue by ghost** [litespeedtech/openlitespeed#175]
Installed via: 
[root@core ~]# yum install ols-modsecurity -y
Confirmed is enabled: 
[root@core comodo]# rpm -ql openlitespeed | grep mod_sec
/usr/local/lsws/modules/mod_security.so

Tried comodo ruleset and the phpinfo rule mentioned in this guide: https://openlitespeed.org/kb/openlitespeed-modsecurity-module/

Created the module inside of server configuration and yet nothing happens when visiting phpinfo file.

Using debug settings below, no file is created at the location:
modsecurity  on
modsecurity_rules 
SecRuleEngine On
SecDebugLog /tmp/auditlog-debug.txt
SecDebugLogLevel 9
SecAuditLogParts AB
SecAuditEngine On
SecAuditLog /tmp/auditlog.txt
SecAuditLogType Serial
SecAuditLogStorageDir /tmp/
SecRule REQUEST_URI "@pm phpinfo.php" "phase:1,id:'10',log,deny,status:403"

Is there something I'm missing?

**Comment by 27therealone27** [comment]
Seems to work when visiting the ip/phpinfo.php. Yet doesn't work on any of the virtual hosts.

**Comment by benyaminl** [comment]
see #189 
it should be 
```
modsecurity on
modsecurity_rules `
SecRuleEngine On
SecDebugLog /tmp/auditlog-debug.txt
SecDebugLogLevel 9
SecAuditLogParts AB
SecAuditEngine On
SecAuditLog /tmp/auditlog.txt
SecAuditLogType Serial
SecAuditLogStorageDir /tmp/
SecRule REQUEST_URI "@pm phpinfo.php" "phase:1,id:'10',log,deny,status:403"
`
```

There's a apostrope (`) and it's not on the Documentation, it takes me 2 hours to look on this. Anyway I think this should be on forum.openlightspeed.org because it's unrelated to the problem. (even I open the ticket here, hahaa..)

Hope it help.

**Comment by rperper** [comment]
The documentation was updated when #189  was updated.  I'm going to go ahead and close this.  Thanks again.

Bob Perper
LiteSpeed Technologies
