### ISSUE TITLE
config.status: error: cannot find input file: `src/adns/Makefile.in'

### ISSUE THREAD

**Issue by tczaude** [litespeedtech/openlitespeed#178]
When i make ebuild i see this error comeback from earlier version.
I use openlitespeed-1.6.12

**Comment by litespeedtech** [comment]
can you run aclocal and autoreconf before ./confgiure?
Actually for 1.6.x and 1.7.x versions, you can use build.sh to build directly.

**Comment by tczaude** [comment]
I try do this. I prefer build without build.sh because i try make ebuild for Funtoo.
But for formal i check build.sh yet

**Comment by tczaude** [comment]
We have another problem 

> configure.ac:484: error: required file 'src/liblsquic/Makefile.in' not found
> src/Makefile.am:121: error: required directory src/liblsquic does not exist
> src/adns/Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
> src/log4cxx/Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
> src/shm/Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
> src/sslpp/Makefile.am:4: warning: 'INCLUDES' is the old name for 'AM_CPPFLAGS' (or '*_CPPFLAGS')
> autoreconf-2.69: automake failed with exit status: 1

**Comment by litespeedtech** [comment]
we will retire autoconf/automake, switch cmake instead. So, please use build.sh .
