### ISSUE TITLE
[ERROR] "readyCompressed() buildCompressedPaths error." in log file 

### ISSUE THREAD

**Issue by slowaways** [litespeedtech/openlitespeed#179]
Hi,

I was using the LiteSpeed Cache plugin on WordPress and while I had made some settings I noticed the slow access to wp-admin.

Looking in the log, I noticed that every time I accessed some wp-admin page this error was written in the log.

[ERROR] "readyCompressed() buildCompressedPaths error."

found here:
![image](https://user-images.githubusercontent.com/9668277/82300152-d10d4380-998c-11ea-9f8b-3e2ca0d248bf.png)
src/http/staticfilecachedata.cpp : 849

Can anyone tell me if this is a directory permission error?
I changed the Swap Directory!

**Comment by litespeedtech** [comment]
Yes, it is likely a permission problem for the swap directory. Hope you have already resolved it.
