### ISSUE TITLE
Certbot PPA don't exist for focal

### ISSUE THREAD

**Issue by JOduMonT** [litespeedtech/openlitespeed#180]
### Context
at least on **focal**
**CertBot PPA** is not working

### Error
```
Err:11 http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release
  404  Not Found [IP: 2001:67c:1560:8008::15 80]
Hit:12 http://archive.ubuntu.com/ubuntu focal InRelease
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/certbot/certbot/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

no focal directory appear in http://ppa.launchpad.net/certbot/certbot/ubuntu/dists/

**Comment by Code-Egg** [comment]
Hi @JOduMonT ,

Right, no PPA for Focal and probably we don't need it more. We should just use the default certbot package for Ubuntu focal. It starts from version 0.40.

**Comment by JOduMonT** [comment]
as I see you fixed it ;)
https://github.com/litespeedtech/ls-cloud-image/commit/4da44b1d8d62fee40c542a23b3a3db779c91ec87
