### ISSUE TITLE
Wrong path for CertBot on CentOS 8

### ISSUE THREAD

**Issue by JOduMonT** [litespeedtech/openlitespeed#181]
## On Centos8
at least
via StackScript at Linode
During the initial script

### At the question:
`Do you wish to issue a Let's encrypt certificate for this domain? [y/N] y`

it always return
`mydomain.tld is inaccessible, please verify!`

while ping mydomain.tld return my ip
**but it's maybe because IPv6 answer first**

```
ping mydomain.tld
PING mydomain.tld(li1766-64.members.linode.com (2400::fea7:dc49)) 56 data bytes
64 bytes from li1766-64.members.linode.com (2400::fea7:dc49): icmp_seq=1 ttl=64 time=0.085 ms
--- mydomain.tld ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.085/0.085/0.085/0.000 ms
```
```
ip a s
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether f2:3c:92:a7:dc:49 brd ff:ff:ff:ff:ff:ff
    inet 172.xxx.xxx.64/24 brd 172.xxx.xxx.255 scope global noprefixroute eth0
       valid_lft forever preferred_lft forever
    inet6 2400::fea7:dc49/64 scope global dynamic noprefixroute 
       valid_lft 2591997sec preferred_lft 604797sec
    inet6 fe80::fea7:dc49/64 scope link noprefixroute 
       valid_lft forever preferred_lft forever
```

**Comment by Code-Egg** [comment]
Hi @JOduMonT ,

The error message is from https://github.com/litespeedtech/ls-cloud-image/blob/master/Setup/domainsetup.sh#L153. 
What did you see if you run `curl -Is http://mydomain.tld/ | grep -i LiteSpeed` from SSH console.

**Comment by JOduMonT** [comment]
okey, ??
if I do
curl -Is http://mydomain.tld/ | grep -i LiteSpeed nothing appear

but for curl -Is http://mydomain.tld
it's WordPress

![image](https://user-images.githubusercontent.com/5204724/82514160-2be69c80-9b3f-11ea-9d2c-936612fc05c3.png)

I'm confuse

**Comment by JOduMonT** [comment]
my bad
I change the root of my default website before ending the setup
so the variable **DOCHM**="${LSDIR}/${VHNAME}/html" wasn't valid

so I pointed it to my new dir
than run

`certbot certonly --non-interactive --agree-tos -m ${EMAIL} --webroot -w ${DOCHM} -d ${DOMAIN} -d ${WWW_DOMAIN}`

than I received certificated by certbot

but still at every ssh connection it ask me to setup my domain.

anyway, since nothing is their I'll reset and be a good boy by following the steps ;)

thank for your help

**Comment by JOduMonT** [comment]
so from a brand new installation
certbot installed but not found by your script

![image](https://user-images.githubusercontent.com/5204724/82516034-fbedc800-9b43-11ea-9234-ec31b370621a.png)

whereis certbot return
`certbot: /usr/local/bin/certbot`

**Comment by JOduMonT** [comment]
it's also happening on Ubuntu 20
![image](https://user-images.githubusercontent.com/5204724/82520081-7242f800-9b4d-11ea-9862-3cee333a3242.png)
whereis certbot
`certbot: /usr/local/bin/certbot`

**Comment by Code-Egg** [comment]
Hi,
I just did the test and confirmed that  I can reproduce it. I also found the issue which is on Linode, the certbot file is locate at `/usr/local/bin/certbot` instead of `/usr/bin/certbot`.  I am thinking if we should add a certbot full path for Linode or update the env, or add a symlink for it.

**Comment by JOduMonT** [comment]
I don't really know
but by simply running certbot, CentOS find it,
so instead of hardening the path you could loose a little it ;)

**Comment by JOduMonT** [comment]
@Code-Egg 
this repo (https://github.com/litespeedtech/ls-cloud-image)
it is where is your main code ?
so I could do PR instead of issue and/or comment

**Comment by JOduMonT** [comment]
> otherwise, I vote for a symlink

I confirm with a symlink it works like a charm ;)

**Comment by Code-Egg** [comment]
> @Code-Egg
> this repo (https://github.com/litespeedtech/ls-cloud-image)
> it is where is your main code ?
> so I could do PR instead of issue and/or comment

Yes you can. I just pushed some fixes, let us know if it works.
