### ISSUE TITLE
Add support for Rack

### ISSUE THREAD

**Issue by ioquatix** [litespeedtech/openlitespeed#182]
Hello,

In order to consolidate and reduce our external dependencies, the Rack gem is removing support for 3rd party handlers.

This means that we hope you will add your own handler for Rack applications if possible.

Here is the code that we are removing in Rack 3:

https://github.com/rack/rack/blob/2-2-stable/lib/rack/handler/lsws.rb

Ideally you bring that code (or some variation) into your own code base and additionally set up tests.

If you don't think it belongs in this repository, you could make an adapter gem, e.g. `openlitespeed-rack`.

**Comment by litespeedtech** [comment]
Thanks for the notification, we always use our own rack handler.
