### ISSUE TITLE
yum update gives error

### ISSUE THREAD

**Issue by adir6** [litespeedtech/openlitespeed#184]
Hello, I am trying to update my OLS using yum update command.

Version: 1.6.13 ---> 1.6.14

Since then, I am getting error.

Please help.

![sx-21-June-20-5166](https://user-images.githubusercontent.com/9323342/85223215-d708a100-b3de-11ea-97da-ac9b8b211071.png)

**Comment by litespeedtech** [comment]
If still a problem, please let us know.
