### ISSUE TITLE
"No request delivery notification has been received from LSAPI application, possible dead lock."

### ISSUE THREAD

**Issue by Diego-OT** [litespeedtech/openlitespeed#186]
Code that Im using:
`# PLAIN TEXT CONFIGURATION FILE

#

#It not set, will use host name as serverName

serverName           

user                      nobody

group                     nogroup

priority                  0

inMemBufSize              60M

swappingDir               /tmp/lshttpd/swap

autoFix503                1

gracefulRestartTimeout    300

mime                      conf/mime.properties

showVersionNumber         0

adminEmails               myemailglobal@gmail.com

errorlog /home/Litespeed_Logs/error.log {

  logLevel                DEBUG

  debugLevel              0

  rollingSize             100M

  enableStderrLog         1

}

accesslog /home/Litespeed_Logs/access.log {

  rollingSize             100M

  keepDays                30

  compressArchive         0

}

#adminEmails                      root@localhost

indexFiles                index.php, index.html

expires  {

  enableExpires           1

  expiresByType           image/*=A604800,text/css=A604800,application/x-javascript=A604800,application/javascript=A604800,font/*=A604800,application/x-font-ttf=A604800

}

tuning  {

  maxConnections          20000

  maxSSLConnections       10000

  connTimeout             30

  maxKeepAliveReq         1000

  keepAliveTimeout        5

  sndBufSize              0

  rcvBufSize              0

  maxReqURLLen            8192

  maxReqHeaderSize        16380

  maxReqBodySize          2047M

  maxDynRespHeaderSize    8192

  maxDynRespSize          2047M

  maxCachedFileSize       4096

  totalInMemCacheSize     20M

  maxMMapFileSize         256K

  totalMMapCacheSize      40M

  useSendfile             1

  fileETag                28

  enableGzipCompress      1

  compressibleTypes       text/*, application/x-javascript, application/xml, application/javascript, image/svg+xml,application/rss+xml

  enableDynGzipCompress   1

  gzipCompressLevel       6

  gzipAutoUpdateStatic    1

  gzipStaticCompressLevel 6

  brStaticCompressLevel   6

  gzipMaxFileSize         10M

  gzipMinFileSize         300

  quicEnable              1

  quicShmDir              /dev/shm

}

fileAccessControl  {

  followSymbolLink        1

  checkSymbolLink         0

  requiredPermissionMask  000

  restrictedPermissionMask 000

}

perClientConnLimit  {

  staticReqPerSec         10

  dynReqPerSec            2

  outBandwidth            9000K

  inBandwidth             0

  softLimit               15

  hardLimit               20

  gracePeriod             15

  banPeriod               300

}

CGIRLimit  {

  maxCGIInstances         20

  minUID                  11

  minGID                  10

  priority                0

  CPUSoftLimit            10

  CPUHardLimit            50

  memSoftLimit            1500M

  memHardLimit            1700M

  procSoftLimit           2500

  procHardLimit           3000

  cgroups                 0

}

accessDenyDir  {

  dir                     /

  dir                     /etc/*

  dir                     /dev/*

  dir                     conf/*

  dir                     admin/conf/*

}

accessControl  {

  allow                   ALL

}

extprocessor lsphp {

  type                    lsapi

  address                 uds://tmp/lshttpd/lsphp.sock

  maxConns                35

  env                     PHP_LSAPI_CHILDREN=35

  env                     LSAPI_AVOID_FORK=200M

  initTimeout             600

  retryTimeout            0

  persistConn             1

  respBuffer              0

  autoStart               2

  path                    fcgi-bin/lsphp7

  backlog                 100

  instances               1

  priority                0

  memSoftLimit            2047M

  memHardLimit            2047M

  procSoftLimit           400

  procHardLimit           500

}

scripthandler  {

  add                     lsapi:lsphp php

}

railsDefaults  {

  maxConns                1

  env                     LSAPI_MAX_IDLE=60

  initTimeout             600

  retryTimeout            0

  pcKeepAliveTimeout      10000

  respBuffer              0

  backlog                 50

  runOnStartUp            3

  extMaxIdleTime          300

  priority                3

  memSoftLimit            2047M

  memHardLimit            2047M

  procSoftLimit           500

  procHardLimit           600

}

wsgiDefaults  {

  maxConns                5

  env                     LSAPI_MAX_IDLE=60

  initTimeout             600

  retryTimeout            0

  pcKeepAliveTimeout      10000

  respBuffer              0

  backlog                 50

  runOnStartUp            3

  extMaxIdleTime          300

  priority                3

  memSoftLimit            2047M

  memHardLimit            2047M

  procSoftLimit           500

  procHardLimit           600

}

nodeDefaults  {

  maxConns                5

  env                     LSAPI_MAX_IDLE=60

  initTimeout             600

  retryTimeout            0

  pcKeepAliveTimeout      10000

  respBuffer              0

  backlog                 50

  runOnStartUp            3

  extMaxIdleTime          300

  priority                3

  memSoftLimit            2047M

  memHardLimit            2047M

  procSoftLimit           500

  procHardLimit           600

}

module cache {

  internal                1

#          1

checkPrivateCache   1

checkPublicCache    1

maxCacheObjSize     10000000

maxStaleAge         200

qsCache             1

reqCookieCache      1

respCookieCache     1

ignoreReqCacheCtrl  1

ignoreRespCacheCtrl 0

enableCache         0

expireInSeconds     3600

enablePrivateCache  0

privateExpireInSeconds 3600

  ls_enabled              1

}

virtualhost Example {

  vhRoot                  Example/

  configFile              conf/vhosts/Example/vhconf.conf

  allowSymbolLink         1

  enableScript            1

  restrained              1

  setUIDMode              0

}

listener Default {

  address                 *:80

  secure                  0

  map                     Example *

}

listener Defaultssl {

  address                 *:443

  secure                  1

  keyFile                 /etc/letsencrypt/live/www.mysite.net/privkey.pem

  certFile                /etc/letsencrypt/live/www.mysite.net/fullchain.pem

  map                     Example *

}

vhTemplate centralConfigLog {

  templateFile            conf/templates/ccl.conf

  listeners               Default

}

vhTemplate EasyRailsWithSuEXEC {

  templateFile            conf/templates/rails.conf

  listeners               Default

}

`

When this happens, the webserver will return a 500 Internal Server Error.
I have tried many edits, as you can see, value of initTimeout and pcKeepAliveTimeout are big (from 60 to, 600 and 10000).

I tried versions fcgi-bin/lsphp7+

Your help will be appreciated!

I used that command to install:
bash <( curl -k https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh ) --adminpassword mypassword --email myemail@gmail.com

PHP 7+

Erro logs:
`2020-06-26 12:46:25.005145 [NOTICE] [121.101.104.52:20750#Example] No request delivery notification has been received from LSAPI application, possible dead lock.

2020-06-26 12:46:25.405862 [INFO] [162.157.107.142:16000#Example] Connection idle time too long: 31 while in state: 6 watching for event: 0, close!

2020-06-26 12:46:25.405938 [INFO] [162.158.137.122:16000] Content len: 0, Request line:

GET /index.php?subtopic=houses&show=2163 HTTP/1.1

2020-06-26 12:46:25.405959 [INFO] [162.158.117.122:16000#Example] HttpExtConnector state: 8, request body sent: 0, response body size: -2, response body sent:0, left in buffer: 0, attempts: 0.

2020-06-26 12:46:27.016562 [NOTICE] [172.68.24.261:29042#Example] No request delivery notification has been received from LSAPI application, possible dead lock.

2020-06-26 12:46:27.016654 [NOTICE] [172.68.22.261:29040#Example] No request delivery notification has been received from LSAPI application, possible dead lock.

2020-06-26 12:46:27.045244 [NOTICE] [172.68.24.261:29118#Example] No request delivery notification has been received from LSAPI application, possible dead lock.

2020-06-26 12:46:27.045308 [NOTICE] [172.68.24.261:29136#Example] No request delivery notification has been received from LSAPI application, possible dead lock.

2020-06-26 12:46:27.065838 [NOTICE] [172.68.24.261:29054#Example] No request delivery notification has been received from LSAPI application, possible dead lock.

2020-06-26 12:46:27.069825 [NOTICE] [172.68.24.261:29068#Example] No request delivery notification has been received from LSAPI application, possible dead lock.

2020-06-26 12:46:27.069888 [NOTICE] [172.68.24.261:29104#Example] No request delivery notification has been received from LSAPI application, possible dead lock.`

**Comment by benyaminl** [comment]
This should be taken account to https://forum.openlitespeed.org/threads/many-possible-dead-lock-on-a-new-server-with-a-simple-script.3825/#post-6826

I also experience it last time and I think this should be on KB on OpenLightspeed.

**Comment by benyaminl** [comment]
> 
> 
> Code that Im using:
> `# PLAIN TEXT CONFIGURATION FILE
> 
> #It not set, will use host name as serverName
> 
> serverName
> 
> user nobody
> 
> group nogroup
> 
> priority 0
> 
> inMemBufSize 60M
> 
> swappingDir /tmp/lshttpd/swap
> 
> autoFix503 1
> 
> gracefulRestartTimeout 300
> 
> mime conf/mime.properties
> 
> showVersionNumber 0
> 
> adminEmails [myemailglobal@gmail.com](mailto:myemailglobal@gmail.com)
> 
> errorlog /home/Litespeed_Logs/error.log {
> 
> logLevel DEBUG
> 
> debugLevel 0
> 
> rollingSize 100M
> 
> enableStderrLog 1
> 
> }
> 
> accesslog /home/Litespeed_Logs/access.log {
> 
> rollingSize 100M
> 
> keepDays 30
> 
> compressArchive 0
> 
> }
> 
> #adminEmails root@localhost
> 
> indexFiles index.php, index.html
> 
> expires {
> 
> enableExpires 1
> 
> expiresByType image/_=A604800,text/css=A604800,application/x-javascript=A604800,application/javascript=A604800,font/_=A604800,application/x-font-ttf=A604800
> 
> }
> 
> tuning {
> 
> maxConnections 20000
> 
> maxSSLConnections 10000
> 
> connTimeout 30
> 
> maxKeepAliveReq 1000
> 
> keepAliveTimeout 5
> 
> sndBufSize 0
> 
> rcvBufSize 0
> 
> maxReqURLLen 8192
> 
> maxReqHeaderSize 16380
> 
> maxReqBodySize 2047M
> 
> maxDynRespHeaderSize 8192
> 
> maxDynRespSize 2047M
> 
> maxCachedFileSize 4096
> 
> totalInMemCacheSize 20M
> 
> maxMMapFileSize 256K
> 
> totalMMapCacheSize 40M
> 
> useSendfile 1
> 
> fileETag 28
> 
> enableGzipCompress 1
> 
> compressibleTypes text/*, application/x-javascript, application/xml, application/javascript, image/svg+xml,application/rss+xml
> 
> enableDynGzipCompress 1
> 
> gzipCompressLevel 6
> 
> gzipAutoUpdateStatic 1
> 
> gzipStaticCompressLevel 6
> 
> brStaticCompressLevel 6
> 
> gzipMaxFileSize 10M
> 
> gzipMinFileSize 300
> 
> quicEnable 1
> 
> quicShmDir /dev/shm
> 
> }
> 
> fileAccessControl {
> 
> followSymbolLink 1
> 
> checkSymbolLink 0
> 
> requiredPermissionMask 000
> 
> restrictedPermissionMask 000
> 
> }
> 
> perClientConnLimit {
> 
> staticReqPerSec 10
> 
> dynReqPerSec 2
> 
> outBandwidth 9000K
> 
> inBandwidth 0
> 
> softLimit 15
> 
> hardLimit 20
> 
> gracePeriod 15
> 
> banPeriod 300
> 
> }
> 
> CGIRLimit {
> 
> maxCGIInstances 20
> 
> minUID 11
> 
> minGID 10
> 
> priority 0
> 
> CPUSoftLimit 10
> 
> CPUHardLimit 50
> 
> memSoftLimit 1500M
> 
> memHardLimit 1700M
> 
> procSoftLimit 2500
> 
> procHardLimit 3000
> 
> cgroups 0
> 
> }
> 
> accessDenyDir {
> 
> dir /
> 
> dir /etc/*
> 
> dir /dev/*
> 
> dir conf/*
> 
> dir admin/conf/*
> 
> }
> 
> accessControl {
> 
> allow ALL
> 
> }
> 
> extprocessor lsphp {
> 
> type lsapi
> 
> address uds://tmp/lshttpd/lsphp.sock
> 
> maxConns 35
> 
> env PHP_LSAPI_CHILDREN=35
> 
> env LSAPI_AVOID_FORK=200M
> 
> initTimeout 600
> 
> retryTimeout 0
> 
> persistConn 1
> 
> respBuffer 0
> 
> autoStart 2
> 
> path fcgi-bin/lsphp7
> 
> backlog 100
> 
> instances 1
> 
> priority 0
> 
> memSoftLimit 2047M
> 
> memHardLimit 2047M
> 
> procSoftLimit 400
> 
> procHardLimit 500
> 
> }
> 
> scripthandler {
> 
> add lsapi:lsphp php
> 
> }
> 
> railsDefaults {
> 
> maxConns 1
> 
> env LSAPI_MAX_IDLE=60
> 
> initTimeout 600
> 
> retryTimeout 0
> 
> pcKeepAliveTimeout 10000
> 
> respBuffer 0
> 
> backlog 50
> 
> runOnStartUp 3
> 
> extMaxIdleTime 300
> 
> priority 3
> 
> memSoftLimit 2047M
> 
> memHardLimit 2047M
> 
> procSoftLimit 500
> 
> procHardLimit 600
> 
> }
> 
> wsgiDefaults {
> 
> maxConns 5
> 
> env LSAPI_MAX_IDLE=60
> 
> initTimeout 600
> 
> retryTimeout 0
> 
> pcKeepAliveTimeout 10000
> 
> respBuffer 0
> 
> backlog 50
> 
> runOnStartUp 3
> 
> extMaxIdleTime 300
> 
> priority 3
> 
> memSoftLimit 2047M
> 
> memHardLimit 2047M
> 
> procSoftLimit 500
> 
> procHardLimit 600
> 
> }
> 
> nodeDefaults {
> 
> maxConns 5
> 
> env LSAPI_MAX_IDLE=60
> 
> initTimeout 600
> 
> retryTimeout 0
> 
> pcKeepAliveTimeout 10000
> 
> respBuffer 0
> 
> backlog 50
> 
> runOnStartUp 3
> 
> extMaxIdleTime 300
> 
> priority 3
> 
> memSoftLimit 2047M
> 
> memHardLimit 2047M
> 
> procSoftLimit 500
> 
> procHardLimit 600
> 
> }
> 
> module cache {
> 
> internal 1
> # 1
> 
> checkPrivateCache 1
> 
> checkPublicCache 1
> 
> maxCacheObjSize 10000000
> 
> maxStaleAge 200
> 
> qsCache 1
> 
> reqCookieCache 1
> 
> respCookieCache 1
> 
> ignoreReqCacheCtrl 1
> 
> ignoreRespCacheCtrl 0
> 
> enableCache 0
> 
> expireInSeconds 3600
> 
> enablePrivateCache 0
> 
> privateExpireInSeconds 3600
> 
> ls_enabled 1
> 
> }
> 
> virtualhost Example {
> 
> vhRoot Example/
> 
> configFile conf/vhosts/Example/vhconf.conf
> 
> allowSymbolLink 1
> 
> enableScript 1
> 
> restrained 1
> 
> setUIDMode 0
> 
> }
> 
> listener Default {
> 
> address *:80
> 
> secure 0
> 
> map Example *
> 
> }
> 
> listener Defaultssl {
> 
> address *:443
> 
> secure 1
> 
> keyFile /etc/letsencrypt/live/www.mysite.net/privkey.pem
> 
> certFile /etc/letsencrypt/live/www.mysite.net/fullchain.pem
> 
> map Example *
> 
> }
> 
> vhTemplate centralConfigLog {
> 
> templateFile conf/templates/ccl.conf
> 
> listeners Default
> 
> }
> 
> vhTemplate EasyRailsWithSuEXEC {
> 
> templateFile conf/templates/rails.conf
> 
> listeners Default
> 
> }
> 
> `
> 
> When this happens, the webserver will return a 500 Internal Server Error.
> I have tried many edits, as you can see, value of initTimeout and pcKeepAliveTimeout are big (from 60 to, 600 and 10000).
> 
> I tried versions fcgi-bin/lsphp7+
> 
> Your help will be appreciated!
> 
> I used that command to install:
> bash <( curl -k https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh ) --adminpassword mypassword --email [myemail@gmail.com](mailto:myemail@gmail.com)
> 
> PHP 7+
> 
> Erro logs:
> `2020-06-26 12:46:25.005145 [NOTICE] [121.101.104.52:20750#Example] No request delivery notification has been received from LSAPI application, possible dead lock.
> 
> 2020-06-26 12:46:25.405862 [INFO] [162.157.107.142:16000#Example] Connection idle time too long: 31 while in state: 6 watching for event: 0, close!
> 
> 2020-06-26 12:46:25.405938 [INFO] [162.158.137.122:16000] Content len: 0, Request line:
> 
> GET /index.php?subtopic=houses&show=2163 HTTP/1.1
> 
> 2020-06-26 12:46:25.405959 [INFO] [162.158.117.122:16000#Example] HttpExtConnector state: 8, request body sent: 0, response body size: -2, response body sent:0, left in buffer: 0, attempts: 0.
> 
> 2020-06-26 12:46:27.016562 [NOTICE] [172.68.24.261:29042#Example] No request delivery notification has been received from LSAPI application, possible dead lock.
> 
> 2020-06-26 12:46:27.016654 [NOTICE] [172.68.22.261:29040#Example] No request delivery notification has been received from LSAPI application, possible dead lock.
> 
> 2020-06-26 12:46:27.045244 [NOTICE] [172.68.24.261:29118#Example] No request delivery notification has been received from LSAPI application, possible dead lock.
> 
> 2020-06-26 12:46:27.045308 [NOTICE] [172.68.24.261:29136#Example] No request delivery notification has been received from LSAPI application, possible dead lock.
> 
> 2020-06-26 12:46:27.065838 [NOTICE] [172.68.24.261:29054#Example] No request delivery notification has been received from LSAPI application, possible dead lock.
> 
> 2020-06-26 12:46:27.069825 [NOTICE] [172.68.24.261:29068#Example] No request delivery notification has been received from LSAPI application, possible dead lock.
> 
> 2020-06-26 12:46:27.069888 [NOTICE] [172.68.24.261:29104#Example] No request delivery notification has been received from LSAPI application, possible dead lock.`

Helo, have you tried to increase the initime?

**Comment by benyaminl** [comment]
Anyone with update on this? I also got this problem again and this is mentioned in many thread across internet
https://forum.openlitespeed.org/threads/many-possible-dead-lock-on-a-new-server-with-a-simple-script.3825/
https://forums.cyberpanel.net/discussion/1522/no-request-delivery-notification-has-been-received-from-lsapi-application-possible-dead-lock

**Comment by litespeedtech** [comment]
It usually happens with some PHP script takes long time to finish, or have a bug causing an infinity loop. 
People keep refreshing that URL, all PHP worker processes are occupied by the long run script, cannot take new request any more.
For some cases, increase the timeout or number of worker processes can help. The eventual fix is to fix the script.
Usually it is not some thing can be taken care of automatically by web server.

**Comment by benyaminl** [comment]
> 
> 
> It usually happens with some PHP script takes long time to finish, or have a bug causing an infinity loop.
> People keep refreshing that URL, all PHP worker processes are occupied by the long run script, cannot take new request any more.
> For some cases, increase the timeout or number of worker processes can help. The eventual fix is to fix the script.
> Usually it is not some thing can be taken care of automatically by web server.

Nah the problem is always like this if :
1. OLS installed on VM that use OpenShift with limited read iops (eg 1000)
2. The php script is wordpress with Woocommerce

I tried to optimize it, but no avail. Cloud provider is biznetgio.com

**Comment by litespeedtech** [comment]
You need to check if all PHP worker processes are busy when it is happening. 
Make sure PHP worker is not blocked on something. you can check with strace.

**Comment by leancode** [comment]
OK same problem here, and a problem it is:

Background:
I installed OLS for the first time for a Wordpress site for a client on a 16 Gigs 8 core VM. It's OpenLiteSpeed 1.7.15 on Debian 11.2. The site is a fairly light site, no Woocommerce and no heavy lifting. Simple custom site (no page builders etc). The site is currently only being accessed by 2 people, the client and myself while working on it. The LScache plugin is installed but cache is disabled for the time being. The site is behind Cloudflare cache with strict SSL and behind HA Proxy (for SSL offloading) on our end. Our other VMs run many more complex PHP based web applications for clients and have no problems whatsoever running under nginx/php-fpm. But this is our first Wordpress install and it seemed OLS might be the way to go. I am taking the time to give this data as it looks like a really promising piece of software, but for the moment it's not useable for us. It looks to me either like a bug or some undocumented configuration default that MUST be changed in order to make this software usable. 

What is supposed to happen / expected to happen:
The site should work out of the box. And it does, sort of. When it does it's _really_ fast. But every minute or so the request immediately hangs and then times out after 30 second with the Cloudflare 504 gateway timeout. When I make another request right away it works (and **fast**!!). 

What has been done:
I googled my fingers wound and tried pretty much everything, to absolutely no avail. It seems to be periodic and appears every minute or so but not precisely every minuten. In the logs I can see that each time it goes bad I see the "No request delivery notification has been received from LSAPI application, possible dead lock".
These are the things I tried for LiteSpeed SAPI App:
PHP_LSAPI_CHILDREN=128
Initial Request Timeout = 600
Connection Keep-Alive Timeout = 10000
Max Connections = 64
Instances = 64
Memory Soft Limit = 12G
Memory Hard Limit = 15G

The log looks like this to give you an idea:
23:33:28 [NOTICE] [78445] [10.8.80.103:48340#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:33:38 [NOTICE] [78445] [10.8.80.103:48340#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:33:48 [NOTICE] [78445] [10.8.80.103:48340#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:33:57 [NOTICE] [78442] sendKillCmdToWatchdog: 'extappkill:97405:-3:0'.
23:33:57 [NOTICE] [78440] Cmd from child: [extappkill:97405:-3:0]
23:33:57 [INFO] [78440] Failed to get process [97405] start time, not running, skip killing.
23 23:34 [NOTICE] [78442] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 65534 setuidmode 2.
23:34:03 [INFO] [78442] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 65534 setuidmode 2.
23:34:03 [NOTICE] [78442] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 65534, flags: 0.
23:34:03 [NOTICE] [78442] [AdminPHP] add child process pid: 97521
23:34:23 [NOTICE] [78443] [10.8.80.103:61368#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:34:33 [NOTICE] [78443] [10.8.80.103:61368#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:34:43 [NOTICE] [78443] [10.8.80.103:61368#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:34:53 [NOTICE] [78443] [10.8.80.103:15025-17#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:35:03 [NOTICE] [78443] [10.8.80.103:15025-17#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:35:13 [NOTICE] [78443] [10.8.80.103:15025-17#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:35:18 [NOTICE] [78442] sendKillCmdToWatchdog: 'extappkill:97521:-3:0'.
23:35:18 [NOTICE] [78440] Cmd from child: [extappkill:97521:-3:0]
23:35:18 [INFO] [78440] Failed to get process [97521] start time, not running, skip killing.
23:35:23 [NOTICE] [78446] [10.8.80.103:44476#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:35:26 [NOTICE] [78442] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 65534 setuidmode 2.
23:35:26 [INFO] [78442] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 65534 setuidmode 2.
23:35:26 [NOTICE] [78442] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 65534, flags: 0.
23:35:26 [NOTICE] [78442] [AdminPHP] add child process pid: 97776
23:35:33 [NOTICE] [78446] [10.8.80.103:44476#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:35:43 [NOTICE] [78446] [10.8.80.103:44476#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:35:57 [NOTICE] [78442] sendKillCmdToWatchdog: 'extappkill:97776:-3:0'.
23:35:57 [NOTICE] [78440] Cmd from child: [extappkill:97776:-3:0]
23:35:57 [INFO] [78440] Failed to get process [97776] start time, not running, skip killing.
23:36:23 [NOTICE] [78446] [10.8.80.103:19486#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.
23:36:26 [NOTICE] [78442] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 65534 setuidmode 2.
23:36:26 [INFO] [78442] [LocalWorker::workerExec] VHost:_AdminVHost suExec check uid 997 gid 65534 setuidmode 2.
23:36:26 [NOTICE] [78442] [LocalWorker::workerExec] Config[AdminPHP]: suExec uid -1 gid -1 cmd /usr/local/lsws/admin/fcgi-bin/admin_php -c ../conf/php.ini, final uid 997 gid 65534, flags: 0.
23:36:26 [NOTICE] [78442] [AdminPHP] add child process pid: 97963
23:36:33 [NOTICE] [78446] [10.8.80.103:19486#wordpress] No request delivery notification has been received from LSAPI application, possible dead lock.

**Comment by Alex16021998** [comment]
server settings
user                      nobody
group                     nobody
priority                  0
enableLVE                 0
inMemBufSize              60M
swappingDir               /tmp/lshttpd/swap
autoFix503                1
gracefulRestartTimeout    300
mime                      conf/mime.properties
showVersionNumber         0
adminEmails               root@localhost

errorlog logs/error.log {
  logLevel                DEBUG
  debugLevel              0
  rollingSize             100M
  enableStderrLog         1
}

accesslog logs/access.log {
  rollingSize             10M
  keepDays                30
  compressArchive         0
}
indexFiles                index.html, index.php

expires  {
  enableExpires           1
  expiresByType           image/*=A604800,text/css=A604800,application/x-javascript=A604800,application/javascript=A604800,font/*=A604800,application/x-font-ttf=A604800
}

tuning  {
  maxConnections          10000
  maxSSLConnections       10000
  connTimeout             300
  maxKeepAliveReq         10000
  keepAliveTimeout        50
  sndBufSize              0
  rcvBufSize              0
  maxReqURLLen            32768
  maxReqHeaderSize        65536
  maxReqBodySize          2047M
  maxDynRespHeaderSize    32768
  maxDynRespSize          2047M
  maxCachedFileSize       4096
  totalInMemCacheSize     5000M
  maxMMapFileSize         256K
  totalMMapCacheSize      40M
  useSendfile             1
  fileETag                28
  enableGzipCompress      1
  compressibleTypes       default
  enableDynGzipCompress   1
  gzipCompressLevel       6
  gzipAutoUpdateStatic    1
  gzipStaticCompressLevel 6
  brStaticCompressLevel   6
  gzipMaxFileSize         10M
  gzipMinFileSize         300

  quicEnable              1
  quicShmDir              /dev/shm
}

fileAccessControl  {
  followSymbolLink        1
  checkSymbolLink         0
  requiredPermissionMask  000
  restrictedPermissionMask 000
}

perClientConnLimit  {
  staticReqPerSec         0
  dynReqPerSec            0
  outBandwidth            0
  inBandwidth             0
  softLimit               10000
  hardLimit               10000
  gracePeriod             15
  banPeriod               300
}

CGIRLimit  {
  maxCGIInstances         20
  minUID                  11
  minGID                  10
  priority                0
  CPUSoftLimit            10
  CPUHardLimit            50
  memSoftLimit            1460M
  memHardLimit            1470M
  procSoftLimit           400
  procHardLimit           450
}

accessDenyDir  {
  dir                     /
  dir                     /etc/*
  dir                     /dev/*
  dir                     conf/*
  dir                     admin/conf/*
}

accessControl  {
  allow                   ALL
}

extprocessor lsphp {
  type                    lsapi
  address                 uds://tmp/lshttpd/lsphp.sock
  maxConns                10
  env                     PHP_LSAPI_CHILDREN=50
  env                     LSAPI_AVOID_FORK=200M
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               2
  path                    $SERVER_ROOT/lsphp73/bin/lsphp
  backlog                 100
  instances               1
  priority                0
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           1400
  procHardLimit           1500
}

scripthandler  {
  add                     lsapi:lsphp php
}

railsDefaults  {
  maxConns                1
  env                     LSAPI_MAX_IDLE=60
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      60
  respBuffer              0
  backlog                 50
  runOnStartUp            3
  extMaxIdleTime          300
  priority                3
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           500
  procHardLimit           600
}

wsgiDefaults  {
  maxConns                5
  env                     LSAPI_MAX_IDLE=60
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      60
  respBuffer              0
  backlog                 50
  runOnStartUp            3
  extMaxIdleTime          300
  priority                3
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           500
  procHardLimit           600
}

nodeDefaults  {
  maxConns                5
  env                     LSAPI_MAX_IDLE=60
  initTimeout             60
  retryTimeout            0
  pcKeepAliveTimeout      60
  respBuffer              0
  backlog                 50
  runOnStartUp            3
  extMaxIdleTime          300
  priority                3
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           500
  procHardLimit           600
}

module cache {
  internal                1

checkPrivateCache   1
checkPublicCache    1
maxCacheObjSize     10000000
maxStaleAge         200
qsCache             1
reqCookieCache      1
respCookieCache     1
ignoreReqCacheCtrl  1
ignoreRespCacheCtrl 0

enableCache         0
expireInSeconds     3600
enablePrivateCache  0
privateExpireInSeconds 3600
  ls_enabled              1
}

virtualhost Example {
  vhRoot                  Example/
  configFile              conf/vhosts/Example/vhconf.conf
  allowSymbolLink         1
  enableScript            1
  restrained              1
  setUIDMode              0
}

virtualhost isekaiscan.com {
  vhRoot                  /home/$VH_NAME
  configFile              $SERVER_ROOT/conf/vhosts/$VH_NAME/vhost.conf
  allowSymbolLink         1
  enableScript            1
  restrained              1
}

listener Default {
  address                 *:80
  secure                  0
  map                     isekaiscan.com isekaiscan.com
}

listener SSL {
  address                 *:443
  secure                  1
  keyFile                 /etc/letsencrypt/live/isekaiscan.com/privkey.pem
  certFile                /etc/letsencrypt/live/isekaiscan.com/fullchain.pem
  certChain               1
  sslProtocol             24
  enableECDHE             1
  renegProtection         1
  sslSessionCache         1
  enableSpdy              15
  enableStapling          1
  ocspRespMaxAge          86400
  map                     isekaiscan.com isekaiscan.com
}

vhTemplate centralConfigLog {
  templateFile            conf/templates/ccl.conf
  listeners               Default
}

vhTemplate EasyRailsWithSuEXEC {
  templateFile            conf/templates/rails.conf
  listeners               Default
}


error logs 
No request delivery notification has been received from LSAPI application, possible dead lock.
