### ISSUE TITLE
OpenLiteSpeed and possible file descriptor leak

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/openlitespeed#188]
I have one customer that the server reach the file descriptor limit 3 times. Every time I increased the limit to try to identify which user is doing that, as we have a lot of sites with very very low traffic.

Today I discovered that openlitespeed, running under nobody user, is leaking file descritors. See the last 12 hours file descriptor count:

```bash
nobody:7783
nobody:19223
```

The openlitespeed server is the unique service running under nobody user.

In stderr.log I am seeing a lot of 

```bash
2020-07-06 10:38:57.926 [STDERR] [480752] Reached max children process limit: 10, extra: 3, current: 13, busy: 11, please increase LSAPI_CHILDREN.
```

Which is really strange, because that server has really low traffic, so max children 10 is a good limit... but ok, I will increase that. But one of my questions is if this problems is relationated with file descriptor leak.

In error.log I am only seeing some errors on mysql databases that can not be relationated with file descriptor leaks.

Some server details:
CentOS Linux release 7.8.2003 (Core)
openlitespeed-1.6.13-1.el7.x86_64

I can update the openlitespeed, however the changelog of the newest does not seems to has anything relationated with my problem ( https://openlitespeed.org/release-log/version-1-6-x/ ).

How to debug that problem?

**Comment by litespeedtech** [comment]
This is my first seeing such issue. If you can create a ticket, our support team may have a look, to check if this is normal or not.
Thanks
David

**Comment by franciscopaniskaseker** [comment]
Happened again today. And again was nobody user.

```bash
[root@mail home]# users=$(awk -F: '{ print $1}' /etc/passwd)
[root@mail home]# for user in $users; do  echo -n "${user}:"; lsof -u $user | wc -l; done
nobody:100201
```

I opened a ticket about that (long time ago), but no answeer.

Maybe can be some site problem, however openlitespeed can not goes dowb due some site fault. All sites are gettin 503 due "too many open files" error.

**Comment by franciscopaniskaseker** [comment]
From both openlitespeed threads under nobody user.

```bash
[root@mail fd]# ls -l | wc -l
49999
[root@mail fd]# pwd
/proc/6366/fd
[root@mail fd]# cd /proc/6367/fd/
[root@mail fd]# ls -l | wc -l
50000
[root@mail fd]# 
```

**Comment by franciscopaniskaseker** [comment]
Today it happened again and I can see the same nobody user with most of all file descriptors.

**Comment by litespeedtech** [comment]
Hi,

Does it still happen with the the latest release 1.6.19 or 1.7.8? I may need to look into this.

**Comment by litespeedtech** [comment]
Please reopen this issue if still have this problem.

**Comment by franciscopaniskaseker** [comment]
Since 1.6.19 seems to be fixed.

**Comment by litespeedtech** [comment]
Thanks for the confirmation.
