### ISSUE TITLE
No apostrope for the mod security documentation

### ISSUE THREAD

**Issue by benyaminl** [litespeedtech/openlitespeed#189]
Hello I'm new in litespeed and I come accross https://openlitespeed.org/kb/openlitespeed-modsecurity-module/#Set_up_the_Module_with_a_simple_test_rule_and_verify_if_mod_security_works_on_OLS_or_not

it doesn't put any ` on the code 
```
module mod_security {
modsecurity  on
modsecurity_rules `
SecRuleEngine On
SecRule REQUEST_URI "@pm phpinfo.php" "phase:1,id:'10',log,deny,status:403"
`
modsecurity_rules_file          /rule/file/path
  ls_enabled              1
 }
```

it should be like that otherwise the modsecurity_rules won't tackle the phpinfo.php file. 
I try to figure it out for more than 2 hours, after seeing the image 
https://openlitespeed.org/wp-content/uploads/2018/07/ols-mod-security-enable-1-1.png 
Then I tried it. Is there anyway to submit/edit to the documentation of openlitespeed? Thank you.

**Comment by rperper** [comment]
Thanks so much for the update.  It should be correct now.  Please let us know if it is not.
Thanks Again!

Bob Perper
LiteSpeed Technologies

**Comment by benyaminl** [comment]
> 
> 
> Thanks so much for the update. It should be correct now. Please let us know if it is not.
> Thanks Again!
> 
> Bob Perper
> LiteSpeed Technologies

The rest should be Ok. Anyway thank you. 
Also there's no KB about deadlock of LS SAPI, I encounter it last time on some VPS and it hang whole VPS. Do I need to open a new ticket here?

Thank you

**Comment by benyaminl** [comment]
Oh It's already on #186 I think this should be closed. Thank you @rperper
