### ISSUE TITLE
lsqpack.h: No such file or directory - build with configure

### ISSUE THREAD

**Issue by qjavax** [litespeedtech/openlitespeed#190]
Hello, 
I'm trying to create pacman package of openlitespeed via configure script (already tryied with build.sh & install.sh - it won't work with PKGBUILD), and I'm having some dificulties with this.
Originally configure script enters infinite loop on boring ssl configure step with:
```
# command-line-arguments
loadinternal: cannot find runtime/cgo
```

Then after some research with build.sh i managed to create beforeconfigure.sh. that prepares confugre to pass correctly

Avaliable here: https://github.com/KujawaK/openlitespeed/blob/fix/configure/beforeconfigure.sh

and with 'make' im getting:
```

httprespheaders.cpp:29:10: fatal error: lsqpack.h: No such file or directory
   29 | #include <lsqpack.h>
      |          ^~~~~~~~~~~
compilation terminated.
make[3]: *** [Makefile:575: httprespheaders.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/tmp/makepkg/openlitespeed/src/openlitespeed/src/http'
make[2]: *** [Makefile:1151: all-recursive] Error 1
make[2]: Leaving directory '/tmp/makepkg/openlitespeed/src/openlitespeed/src'
make[1]: *** [Makefile:634: all] Error 2
make[1]: Leaving directory '/tmp/makepkg/openlitespeed/src/openlitespeed/src'
make: *** [Makefile:420: all-recursive] Error 1
```

How is this possible to fix?
PS: im running custom linux distro based on ArchLinux and problem with creating package with configure exists in >1.5.x versions

**Comment by litespeedtech** [comment]
Hi, we are phasing out build with configure, instead, use cmake to build the project. 
`build.sh` can be used for as a reference.
