### ISSUE TITLE
PHP 7 is not getting installed in Ubuntu 20 (LTS)

### ISSUE THREAD

**Issue by slavafomin** [litespeedtech/openlitespeed#191]
Hello! First of all, thank you for this great project!

I'm downloading a [tarball release](https://github.com/litespeedtech/openlitespeed/releases/tag/v1.7.3) of OpenLiteSpeed 1.7.3 and installing it on my Ubuntu 20 machine (`20.04.1 LTS`). However, the PHP 7 package is not getting installed due to the fact that `check_os()` shell function in `_in.sh` doesn't specify this version of Ubuntu. The latest specified version is `18`.

I've looked into mentioned [Debian repository](http://rpms.litespeedtech.com/debian/dists/focal/main/binary-amd64/) and I can see that PHP 7 packages for Focal Fossa are actually present there. I believe this would be trivial to fix by updating the mentioned `check_os()` function in `_in.sh` script.

---

Here's the info for Focal Fossa:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.1 LTS"
```

**Comment by litespeedtech** [comment]
This should have been fixed in the latest release.
