### ISSUE TITLE
name and license

### ISSUE THREAD

**Issue by qlcom** [litespeedtech/openlitespeed#195]
you used GPL v3 license but your software's name has the word open in it. Richard Stallman don't like Open source, he use the words 'Free software' . so you should have called it freelitespeed instead of openlitespeed.

**Comment by RhvsW** [comment]
Go away

**Comment by qlcom** [comment]
i am just making fun. 😁😁

**Comment by RhvsW** [comment]
No you're just really fucking annoying.

**Comment by qlcom** [comment]
why?
