### ISSUE TITLE
Server log viewer bug

### ISSUE THREAD

**Issue by therealgilles** [litespeedtech/openlitespeed#197]
Commit [d4bf50f6a2f32e282ea39affb90c96ea131bb5e7](https://github.com/litespeedtech/openlitespeed/commit/d4bf50f6a2f32e282ea39affb90c96ea131bb5e7#diff-621d5f245db357d42edd6480838f6b63) introduced a bug in the server log viewer.

The end log button does not to work anymore because LogFilter::POS_FILEEND is -1 and that value is rejected by the code change:

```
       if ($from < 0)
            $from = 0;
```

This also breaks the log viewer on the dashboard.

**Comment by therealgilles** [comment]
The correct fix should probably be done in this switch statement:

```
        switch ($act) {
            case 'begin':
                $startinput = 0;
                break;
            case 'end':
                $startinput = LogFilter::POS_FILEEND;
                break;
            case 'prev':
                $startinput -= $block;
                **_if ($startinput < 0)
                  $startinput = 0;_**
                break;
            case 'next':
                $startinput += $block;
                break;
        }
```

A similar check with 'next' and LogFilter::FLD_FILE_SIZE may be necessary too, not sure.

**Comment by therealgilles** [comment]
There seems to be more issues here. From instance, being at the end of the file and press 'prev' does not work.

**Comment by therealgilles** [comment]
I tracked one of the problems down. The startpos in search from is displayed with number_format, which by default, uses a comma separator for thousands. When $startinput is computed as follows:

```
        $startinput = UIBase::GrabGoodInput('any', 'startpos', 'float');
```

the comma separator makes it drop everything except the numbers before the first comma. One possible fix is as follows:

```
        $startinput = floatval(str_replace(',', '', UIBase::GrabGoodInput('any', 'startpos', 'string')));
```

**Comment by therealgilles** [comment]
Here is what I would do for the other part of the fix, to make 'prev' and 'next' wrap around:

```
        $frompos = ($frominput == LogFilter::POS_FILEEND) ? ($file_size - $block) : ($frominput * 1024);
        if ($frompos < 0) {
            $frompos = $file_size - $block;
            $endpos = $file_size;
        } elseif ($frompos > $file_size) {
            $frompos = 0;
            $endpos = $block;
        } else {
            $endpos = $frompos + $block;
        }
```

**Comment by therealgilles** [comment]
@davidlst: Let me know if you agree with these changes and I can prepare a PR.

**Comment by litespeedtech** [comment]
Thanks for your report. Internally this project is maintained in a separate repo. We will have this fixed in next release.

**Comment by therealgilles** [comment]
Clarifying that the fix has only 2 parts:
• https://github.com/litespeedtech/openlitespeed/issues/197#issuecomment-690789655
• https://github.com/litespeedtech/openlitespeed/issues/197#issuecomment-690794592

The [first proposed change](https://github.com/litespeedtech/openlitespeed/issues/197#issuecomment-690777365) is unnecessary.

**Comment by litespeedtech** [comment]
this has been fixed a while ago.
