### ISSUE TITLE
Automatically disabled Acquire::http::Pipeline-Depth

### ISSUE THREAD

**Issue by ddegner** [litespeedtech/openlitespeed#200]
I just ran apt update && apt upgrade on my new Ubuntu 20.04.1 LTS install from the https://openlitespeed.org/#install page. I received this error.

W: http://rpms.litespeedtech.com/debian/pool/main/focal/lsphp73-opcache_7.3.22-1+focal_amd64.deb: Automatically disabled Acquire::http::Pipeline-Depth due to incorrect response from server/proxy. (man 5 apt.conf)

**Comment by litespeedtech** [comment]
This is not an OLS bug.
