### ISSUE TITLE
Cannot change PHP PATH environment variable

### ISSUE THREAD

**Issue by hifihedgehog** [litespeedtech/openlitespeed#208]
(See also ticket https://github.com/usmannasir/cyberpanel/issues/466 at Cyberpanel.)

Note, this is what I currently see by default for OLS's environment PATH:

![image](https://user-images.githubusercontent.com/16614343/96625593-64e89000-12dc-11eb-9a02-7a116d38cdc5.png)

And it needs to be this for MailScanner/MailWatch to work:

> /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin

The real question here is how do I change the PATH variable environment for OpenLitespeed? I tried two different ways and they all failed.

1. Based on this (https://openlitespeed.org/kb/server-environment-variables/), I tried to hard set the PATH environment variable but OpenLitespeed seems to ignore it:

![image](https://user-images.githubusercontent.com/16614343/96626742-dffe7600-12dd-11eb-9bd7-4e344c51de36.png)

2.  I also tried editing the command section. That didn't work, either, but only because OpenLiteSpeed, unlike LiteSpeed, does not allow putting a path environment variable before the actual lsphp path.

![image](https://user-images.githubusercontent.com/16614343/96633006-864e7980-12e6-11eb-951d-ffc31cc06a6b.png)

For reference, in LiteSpeed, editing the command section would have worked since it allows adding a variable proceeding the path.

![image](https://user-images.githubusercontent.com/16614343/96632963-79ca2100-12e6-11eb-8235-cbbdef4591c6.png)

**Comment by hifihedgehog** [comment]
CC: @hennaboy

**Comment by kam821** [comment]
Is trying to manipulate PATH variable with PHP/Webserver even correct?
PATH is OS user/Shell level variable and it is passed to the program (openlitespeed/lsphp) when it starts.

**Comment by hifihedgehog** [comment]
> Is trying to manipulate PATH variable with PHP/Webserver even correct?
> PATH is OS user/Shell level variable and it is passed to the program (openlitespeed/lsphp) when it starts.

Yes, it is a basic feature of PHP. Note phpinfo's environment section. You can set this in Apache and Nginx, as well as in the commercial version of Litespeed:

![image](https://user-images.githubusercontent.com/16614343/96640512-4640c400-12f1-11eb-96fa-a4638b96414b.png)

**Comment by hifihedgehog** [comment]
> Is trying to manipulate PATH variable with PHP/Webserver even correct?
> PATH is OS user/Shell level variable and it is passed to the program (openlitespeed/lsphp) when it starts.

This is how you would do it in Apache:

> Ok, in my case, that was not it, it is actually an environment variable problem
> 
> 'which' depends on the PATH environment variable.
> 
> I added this to my php-fpm configuration:
> 
> ```
> env[PATH] = /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
> ```
> 
> Restarted php-fpm and it is now working for me.



https://github.com/mailwatch/MailWatch/issues/1026#issuecomment-357817154

**Comment by hifihedgehog** [comment]
And this is how you would do it in commercial Litespeed:

![image](https://user-images.githubusercontent.com/16614343/96641029-10e8a600-12f2-11eb-82df-d40d0043df25.png)

**Comment by hifihedgehog** [comment]
^ OpenLitespeed does not support the above method. If you attempt it, you get an error because OpenLitespeed wants to see ONLY a file path with NO proceeding variable. This is what happens if you attempt this in OpenLitespeed:
![image](https://user-images.githubusercontent.com/16614343/96641162-5016f700-12f2-11eb-9717-9563ee962321.png)

Again, I am repeating EVERYTHING I just stated in my initial post almost word for word. Please carefully read and hopefully patch this issue.

**Comment by hifihedgehog** [comment]
Note that $_SERVER['PATH'] is a valid PHP environment variable and Apache, Nginx, and commercial Litespeed can properly set this variable. In reading these instructions here (https://openlitespeed.org/kb/server-environment-variables/) on the OpenLitespeed site...

```
How To Set Server Environment Variables
At times, applications may require the creation of an internal server environment variable, such as you might set up with the SetEnv directive in Apache. You can set up server environment variables in OpenLiteSpeed, too.

Page Contents	
Server Side Setup
Application Usage
Server Side Setup
Log in to the WebAdmin Console, navigate to Virtual Host > External App. For this example, let’s use PHP.

In the Environment field, add the variables TEST_VALUE and TEST_VALUE2, like so:

TEST_VALUE=Hello
TEST_VALUE2=World
Copy
Save and restart OpenLiteSpeed.



Please note: if you are using PHP detached mode, you must first kill the lsphp process so it may be restarted. Otherwise the new variables won’t be loaded.

Application Usage
You can access the new variables in PHP code such as the following test.php:

<?php
$test1 = $_SERVER['TEST_VALUE'];
$test2 = getenv('TEST_VALUE2');

echo $test1.' '.$test2;
Copy
Access test.php from the browser, and you should see the values that were set at the server level, like so:
```

Source:

https://openlitespeed.org/kb/server-environment-variables/

...I would be led to believe that I should be able to set it. The problem is I can't, and this breaks functionality on certain web applications such as MailWatch.

**Comment by kam821** [comment]
@hifihedgehog 
Dziwne.
Przetestowałem go i działa dobrze, bez względu na to, czy jest skonfigurowany na poziomie serwera, czy vhosta, czy inny użytkownik (nobody / www-data).
Openlitespeed 1.6.16, lsphp 7.4, Debian 10.
Czy ręcznie ponownie uruchomiłeś LSPHP po zmianie ustawień i Graceful restart Openlitespeed?
LSPHP działa domyślnie w trybie odłączonym i nie robi tego automatycznie.
https://openlitespeed.org/kb/php-detached-mode/
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:detached_mode
![ols1](https://user-images.githubusercontent.com/26425123/96641795-8b7ee900-1325-11eb-91c9-f09c5ff987ed.PNG)
![ols2](https://user-images.githubusercontent.com/26425123/96641820-92a5f700-1325-11eb-86fb-9d1af00c4e45.PNG)
![ols3](https://user-images.githubusercontent.com/26425123/96641831-96d21480-1325-11eb-8411-3526f556bbb3.PNG)

**Comment by kam821** [comment]
Weird.
I tested it and it's working just fine, no matter if it is configured at server or vhost level or user different user (nobody/www-data).
Openlitespeed 1.6.16, lsphp 7.4, Debian 10.
Did you manually restart LSPHP after changing settings and Graceful restart Openlitespeed?
LSPHP is running in detached mode by default and it doesn't do this automatically.
https://openlitespeed.org/kb/php-detached-mode/
https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:php:detached_mode
![ols1](https://user-images.githubusercontent.com/26425123/96641872-a3566d00-1325-11eb-98b5-a8c466f0bf64.PNG)
![ols2](https://user-images.githubusercontent.com/26425123/96641878-a5b8c700-1325-11eb-93da-d5d448746020.PNG)
![ols3](https://user-images.githubusercontent.com/26425123/96641891-a9e4e480-1325-11eb-9a28-39078371898b.PNG)

**Comment by hifihedgehog** [comment]
Yep and yep. I followed those instructions and even added killall -9 lsphp in for good measure.

**Comment by hifihedgehog** [comment]
I just tried it again with the initial colon to see if that made any difference. I am on CentOS 7, using CyberPanel, OpenLitespeed 1.6.16.

Here are the steps I followed just to make sure I wasn't doing anything wrong:

1. Go to external app LiteSpeed SAPI App / "uds://tmp/lshttpd/lsphp.sock" and add the line "PATH=:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin" and save it.
![image](https://user-images.githubusercontent.com/16614343/96643038-ff54cd80-12f4-11eb-923e-758b9dd69a10.png)

2. Run "touch /usr/local/lsws/admin/tmp/.lsphp_restart.txt" in terminal.
![image](https://user-images.githubusercontent.com/16614343/96643135-257a6d80-12f5-11eb-9b9c-9d7811527b51.png)

3. Gracefully restart OpenLitespeed from the Litespeed admin panel.
![image](https://user-images.githubusercontent.com/16614343/96643177-33c88980-12f5-11eb-8400-5cc9fd5acbfb.png)


4. Go to a fresh cache cleared browser session of phpinfo.

And I see this:
![image](https://user-images.githubusercontent.com/16614343/96643001-f06e1b00-12f4-11eb-8407-7a4ef85d7496.png)

So weird!

**Comment by hifihedgehog** [comment]
If it's of any help, you can reach out to me on the Litespeed Slack and I can give you credentials so you can SSH in.

**Comment by hifihedgehog** [comment]
I just created a ticket at LiteSpeed. It's #589297, or https://store.litespeedtech.com/store/viewticket.php?tid=589297.

**Comment by litespeedtech** [comment]
I tested that feature, it is correctly supported.
My conf
```
extprocessor lsphp {
  type                    lsapi
  address                 uds://tmp/lshttpd/lsphp.sock
  maxConns                10
  env                     PHP_LSAPI_CHILDREN=10
  env                     TESTENV=$SERVER_ROOT/ttt
  env                     LSAPI_AVOID_FORK=200M
  env                     PATH=/usr/local/home:/usr/bin
  env                     TESTENVABC=$VH_NAME/ttt
  initTimeout             60
  retryTimeout            0
  persistConn             1
  respBuffer              0
  autoStart               2
  path                    fcgi-bin/lsphp
  backlog                 100
  instances               1
  priority                0
  memSoftLimit            2047M
  memHardLimit            2047M
  procSoftLimit           1400
  procHardLimit           1500
}
```
 and I got it from phpinfo.php
```
_SERVER["TESTENV"]	/home/user/ls175//ttt
_SERVER["PATH"]	/usr/local/home:/usr/bin
_SERVER["TESTENVABC"]	/ttt

_SERVER["argc"]	1
_ENV["TESTENV"]	/home/user/ls175//ttt
_ENV["PATH"]	/usr/local/home:/usr/bin
_ENV["TESTENVABC"]	/ttt
```
This shows the PATH env does work.

**Comment by litespeedtech** [comment]
Please make sure you set it in the right lsphp section.
Thanks
David

**Comment by hifihedgehog** [comment]
Thanks for clearing things up! The ball's now back in CyberPanel's court. Here is what I sent them:

> Hey, how would I edit the vHost.conf for CyberPanel itself? I am trying to add add a PATH env variable for one of CyberPanel's internal public sites, the ones served out of /usr/local/CyberCP/public, MailWatch. I can add a PATH env variable easily enough to the virtual host of one of my websites, but there is not a virtual host conf file for CyberPanel. So I tried adding an PATH env variable to the LSPHP socket for the entire server (/usr/local/lsws/conf/httpd_config.conf), but that doesn't affect CyberPanel's internal sites. Thoughts?

**Comment by litespeedtech** [comment]
Thanks for letting me know.

**Comment by hifihedgehog** [comment]
No problem. For MailWatch/MailScanner, adding this line at the end of the conf.php file does the trick. It's strange that there is no easily apparent way to set the PATH variable at all for CyberPanel's internal sites, though:

> putenv('PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin');
