### ISSUE TITLE
Openlitespeed accessControl and OLS web gui access

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/openlitespeed#209]
**Problem:**
After add trusted networks and deny everything else, some time after the OLS reject the connections to 7080 (web gui port).

**Questions:**

1. accessControl is about all ports (including 7080) or only 80/443?
1.1. if yes, to control only 80 and 443 I have to do this config under virtualhost accessControl?
2. Why it take some time to reject the IPs that are not allowed there? Maybe due gracefuly restart?

I did not find those answers on OLS documentation. In the LS documentation there is nothing about ports, so seems to be about all OLS listened ports. I have no rules about client throttling.

**Environment:**
- openlitespeed 1.6.16
- centos 7 x86_64

**Comment by litespeedtech** [comment]
The accesslog is about all ports, you can separate you vhosts to its own log; 
Change the config need to restart to reload it.
This is not an issue, please go to forum for questions.
Thanks
David

**Comment by franciscopaniskaseker** [comment]
In last two weeks I saw in 3 different servers the same behavior. In all cases the access control was ALL.

In 2 servers there is no 
```bash
accessControl {
allow ALL
}
```

directive, so I added manually and restarted the lsws service. But I do not think this is a fix, because if there is no accessControl directive, then by default it will allow all.

But in the other server this directive already was there and I had to restart the lsws to get the web gui working again.

Some notes:
- if I try to do telnet in 7080 port, it open the connection
- this happened with 1.6.18, 1.6.19 and 1.6.20 versions

I will update to 1.6.21 and check if the problem continue.

**Comment by litespeedtech** [comment]
I guess we need access to one the server exhibiting the problem to find out what happened exactly.
You can create a ticket when it happens again.

**Comment by franciscopaniskaseker** [comment]
@litespeedtech where can I create a ticket?

**Comment by litespeedtech** [comment]
Email to bug @ litespeedtech (dot) com  .
