### ISSUE TITLE
VirtualHost/VHTemplate SSL Protocol Version settings ignored

### ISSUE THREAD

**Issue by qmorek** [litespeedtech/openlitespeed#213]
I need to have possibility to test different versions of TLS on my server and wanted to have
tls12.*
tls13.*
subdomains and it is possible to specify SSL/TLS Protocol Version on virtual host or virtual host template level both in UI and in config files, for example:
```
vhssl  {
  keyFile                 /etc/letsencrypt/live/example.com/privkey.pem
  certFile                /etc/letsencrypt/live/example.com/fullchain.pem
  certChain               1
  sslProtocol             8
  enableSpdy              0
  enableQuic              0
}
```
but changing it on this level has no effect. It changes only when I change this setting on listener level...
I was checking it with chrome dev tools
https://www.ssllabs.com/ssltest/analyze.html page
and openssl s_client -prexit -connect
all showing the same.

**Comment by litespeedtech** [comment]
I will check our code if this is not implemented or it is a bug.
Thanks
David

**Comment by qmorek** [comment]
Thanks,
For enableSpdy and enableQuic it works fine, so I thought for sslProtocol will be the same :)

**Comment by qmorek** [comment]
Hi team,
any update here? Are you able to confirm if it is bug or not implemented?

**Comment by litespeedtech** [comment]
This feature does not work.  Since we deem this to be of marginal utility, we will not make it work.  Instead, we will remove the protocol version selection section from VHost and VHost templates configuration sections of the admin interface.  To test different protocol versions, you can still use the Listener setting.
