### ISSUE TITLE
Change admin path response

### ISSUE THREAD

**Issue by mgagliardo** [litespeedtech/openlitespeed#216]
Hello there.

I am working with some very specific piece of software and I can only make my server answer to `/` on whichever port I setup for the vhost (say 80). 

The thing is, I still need to access the admin server (for example, 7080) on another path like `/admin/`. The problem is the admin `always` redirects to `/`.

Is there anyway to redirect this response to whatever path I would want? I even tried to put the whole code behind an nginx proxy server with no luck.

Thanks in advance!

**Comment by litespeedtech** [comment]
I think should use subdomain, instead of changing the URL. the webadmin console is not designed for sysadmin access only. If you make it available for non-sysadmin user (a site owner), it could be a security risk. 
For managing the server, it is better to use a control panel, CyberPanel or DA.

**Comment by mgagliardo** [comment]
Yes the thing is it's a standalone and isolated, so no chances to point to a subdomain, the isolated installation + domain install is done at startup and there is no easy way to point a subdomain to it. Any chance I can recompile the code to achieve this? 

Security risks are on me on this case.
