### ISSUE TITLE
Websocket messages when proxied through OLS are delayed.

### ISSUE THREAD

**Issue by TroyDota** [litespeedtech/openlitespeed#219]
Messages that are large have considerable delay when proxied via OpenLiteSpeed

I uploaded an image via a websocket, when connected via the OLS proxy it takes ~30s to move about 200kb of image data in base64 
SO i exposed the port and connected directly to the open port and it took about ~1.2s to upload the same message.

time is time in mills ~ via open port
```
{ changes: [ 'profile_picture' ], failed: {} } 1287
```
via ols
```
{ changes: [ 'profile_picture' ], failed: {} } 30565
```

via nginx
```
{ changes: [ 'profile_picture' ], failed: {} } 1451
```

using the latest version of OLS (OpenLiteSpeed 1.7.8) 
proxy config
![image](https://user-images.githubusercontent.com/49777269/107039420-8f485580-67c6-11eb-8b05-fd172a534bdf.png)

**Comment by TroyDota** [comment]
It seems that OLS is doing something that is a bit weird when it comes to how it is processing websocket messages.

**Comment by litespeedtech** [comment]
Hi, it is likely a performance issue with the Layer4 proxy connection. I guess it read/forward data in too small chunks. 
Can you please capture some strace output for us to analysis. 
Please run OLS with 1 worker only. Locate the PID of the worker process. do the follow command 
`strace -tt -T -o l4_slow_strace.log -p $PID_of_openlitespeed_worker` 
Please make sure to use the real PID, do not use `$PID_of_openlitespeed_worker` as is.
Do a slow upload test, stop strace.
Make the  `l4_slow_strace.log` available for us to download.

**Comment by TroyDota** [comment]
Sure.

**Comment by TroyDota** [comment]
@litespeedtech https://cdn.viders.dev/ols/l4_slow_strace.log
my script responded with a error message (expected) after 25864ms
https://cdn.viders.dev/ols/super_cool_script.mp3.js
is what i used to "upload" the image.

**Comment by litespeedtech** [comment]
I think I figured out what happened based on strace output.
Can you please try the latest debug build
`/usr/local/lsws/admin/misc/lsup.sh -b -e 1.6.20`
or 
`/usr/local/lsws/admin/misc/lsup.sh -b -e 1.7.9`

see if it addresses the problem or not.

**Comment by TroyDota** [comment]
Seems good, what was the issue?

**Comment by litespeedtech** [comment]
Thanks for the confirmation.
It is caused by SSL input buffering, missing event to finish reading pending data.

**Comment by TroyDota** [comment]
One last thing, is the debug version okay for production?
