### ISSUE TITLE
VHost Template : Can't set up "Actions" section

### ISSUE THREAD

**Issue by TonioParis** [litespeedtech/openlitespeed#220]
Can't set up "Actions" section.

I tried to click on this section (and scroll).
Also tried on Firefox & Chrome / W10 (all are up to date)

I just saw the same problem here : https://forum.openlitespeed.org/threads/cannot-configure-access-log-for-vhost-template.4305/

A screenshot of my problem is attached.

Thanks for your help.

![PB openlitespeed](https://user-images.githubusercontent.com/12527361/107112660-83f23a00-6859-11eb-8cbf-a240ef845977.png)

**Comment by litespeedtech** [comment]
Thanks. This should work in 1.7.8. will be fixed in next release of 1.6.x.

**Comment by TonioParis** [comment]
Ok thanks for your answer.
