### ISSUE TITLE
Are SSL certificates in VHOST template ignored ?

### ISSUE THREAD

**Issue by TonioParis** [litespeedtech/openlitespeed#221]
Hello,

I'm trying to use VHOST template for (at least) 2 domains and with 1 SSL certificate per domain.
I tried many tests but I can't find the good way and I can't find an example of config...

Then, is it an issue or I'm wrong ?
Is there any guide with an example about my need ?

Here is my configuration :
OpenLiteSpeed 1.6.19 / DEBIAN 10 (updated).

In /usr/local/lsws/conf/templates/centralConfig.conf :

> vhRoot                    $SERVER_ROOT/mon_vps/php/$VH_NAME
> 
> configFile                $SERVER_ROOT/conf/vhosts/$VH_NAME/vhconf.conf
> 
> virtualHostConfig  {
>   docRoot                 $VH_ROOT/www/
>   enableGzip              1
>   enableIpGeo             1
>   cgroups                 0
> 
>   vhssl  {
>     keyFile               /etc/letsencrypt/live/$VH_NAME/privkey.pem
>     certFile              /etc/letsencrypt/live/$VH_NAME/fullchain.pem
>         OR
>         keyFile : /etc/letsencrypt/live/$VH_DOMAIN/privkey.pem
>         certFile : /etc/letsencrypt/live/$VH_DOMAIN/fullchain.pem
>     certChain             1
>   }
> }

In : /usr/local/lsws/conf/httpd_config.conf

> listener http {
>   address                 *:80
>   secure                  0
> }
> 
> listener https {
>   address                 *:443
>   secure                  1
> }
> 
> vhTemplate centralConfigTonio {
>   templateFile            $SERVER_ROOT/conf/templates/centralConfig.conf
>   listeners               http, https
> 
>   member website_1.com
> 
>   member website_2.com
> }

But if I delete the SSL Section in "VHost Templates" and complete directly in the Listeners Section, it works ! :

Listener https > SSL :
SSL Private Key & Certificate :

Private Key File : /etc/letsencrypt/live/website_1.com/privkey.pem
Certificate File : /etc/letsencrypt/live/website_1.com/fullchain.pem
Chained Certificate : Yes
**==> https://www.website_1.com works !**

OR in the same listener, if I make this replacement :

Private Key File : /etc/letsencrypt/live/website_2.com/privkey.pem
Certificate File : /etc/letsencrypt/live/website_2.com/fullchain.pem
Chained Certificate : Yes
**==> https://www.website_2.com works !**

**Comment by litespeedtech** [comment]
This is configuration problem, you need to configure a default SSL certificate for the the `listener https` .
Without that, the https listener will fail. port 443 wont open. 
You can use any SSL certificate as default, as long as there is a valid SSL certificate configuration. 
It will be used, for example, when you access `https://<server_ip>` 

SSL certificate configured in the VH template will be used when a specific domain is accessed.
