### ISSUE TITLE
Is it possible to configure a reverse proxy to a unix socket?

### ISSUE THREAD

**Issue by TroyDota** [litespeedtech/openlitespeed#222]
Hi, is it currently possible to configure a reverse proxy to a unix socket.

Example, 
`https://verycooldomain.com -> /tmp/very_cool_socket.png.sock`
`https://verycooldomain2.com -> /tmp/very_cool_socket.jpg.sock`

Same question for the websocket proxy.

I didnt see mentions of this in the docs, and was curious. nginx supports this but i wasnt sure if OLS did too.
_I also might be blind so sorry if im wasting someone's time._

**Comment by litespeedtech** [comment]
Such configuration is not possible at the moment.  Nevertheless, we plan to add it in the future.  Stay tuned!

**Comment by litespeedtech** [comment]
It is supported in 1.6.21 and upcoming 1.7.10 .

**Comment by TroyDota** [comment]
Thanks xqcL
