### ISSUE TITLE
Bubblewrap problem

### ISSUE THREAD

**Issue by gjerek** [litespeedtech/openlitespeed#223]
I have a problem with 1.6.19 and 1.7.8 versions of openlitespeed.

I have used bubblewrap in 1.6.16, setting off on server level and on on virtual levels...everything fine.
But upgrading to 1.6.19 or 1.7.8 breaks it, user home directory is not mounted.

Also in 1.6.19 bubblewrap settings are missing from admin UI.

**Comment by litespeedtech** [comment]
Hi, @gjerek 
can you do a quick test for 1.6.20 & 1.7.9 for bubblewrap?
/usr/local/lsws/admin/misc/lsup.sh -b -v 1.6.20  
this will use the prerelease version.

**Comment by gjerek** [comment]
@litespeedtech I tried, on 1.6.20 I get this error with default bubblewrap command:
2021-02-06 10:27:45.003 [STDERR] bwrap: Unknown option --symlink../tmp
2021-02-06 10:27:46.092 [STDERR] bwrap: execvp 65534’: No such file or directory
2021-02-06 10:27:49.136 [STDERR] bwrap: execvp 65534’: No such file or directory

I tried to copy paste default command with space --symlink ../tmp but correct path /usr/bin/bwrap but in that case there's no error and bwrap is not starter.

**Comment by litespeedtech** [comment]
Which Linux distribution/version are you using? 
How has bubblewrap binary been installed?

**Comment by gjerek** [comment]
Debian 10
bubblewrap was installed via apt

**Comment by rperper** [comment]
This is a known issue with Bubblewrap versions before 0.3.3.  Upgrading to that version or higher should address the problem.  See https://openlitespeed.org/kb/bubblewrap-in-openlitespeed/

**Comment by litespeedtech** [comment]
https://tracker.debian.org/pkg/bubblewrap
you can try stable-bpo: 0.4.1-3~bpo10+1

**Comment by litespeedtech** [comment]
Hi,

Please run lsup.sh command again to try the updated pre-release package. 
should be fixed.

**Comment by gjerek** [comment]
thank you very much it works perfectly fine on 1.6.20 pre-release now.
