### ISSUE TITLE
configure: WARNING: unrecognized options: --enable-litespeed

### ISSUE THREAD

**Issue by ziaratban** [litespeedtech/openlitespeed#228]
` --enable-litespeed` option not unrecognized when i want to compile the php 8.0.3 from source in WebAdmin console.

```
**LOG_DETAIL** retrieved from /usr/local/lsws/phpbuild/buildphp_1616776673.4.log

==============================================
Start building PHP 8.0.3 with LSAPI
==============================================
Fri Mar 26 21:35:50 +0430 2021

Changing to build directory /usr/local/lsws/phpbuild/php-8.0.3
buildconf: Checking installation
buildconf: autoconf version 2.69 (ok)
buildconf: Forcing buildconf. The configure files will be regenerated.
buildconf: Cleaning cache and configure files
buildconf: Rebuilding configure
buildconf: Rebuilding main/php_config.h.in
buildconf: Run ./configure to proceed with customizing the PHP build.
Configuring PHP build (2-3 minutes)
 ./configure '--prefix=/usr/local/lsws/lsphp83' .... '--enable-litespeed'
configure: WARNING: unrecognized options: --enable-litespeed

...
```

**Comment by litespeedtech** [comment]
What OS is used? 
It should not force build configure script for PHP 8.0. 
The generated build script may not work properly with the shell installed in your OS. 
if you open /usr/local/lsws/phpbuild/buildphp_1616776673.4.install.sh, it has 
```
BUILDCONF_FORCE=N
if [ "${PHP_MAIN_VER1}" -lt "5" ] ; then
    BUILDCONF_FORCE=Y
elif [ "${PHP_MAIN_VER1}" = "5" ] && [ "${PHP_MAIN_VER2}" -lt "3" ] ; then
    BUILDCONF_FORCE=Y
fi

if [ "${BUILDCONF_FORCE}" = "Y" ] ; then
        ./buildconf --force
        check_errs $? "Could not generate configuration script for version prior to 5.3"
fi
```
for PHP 8, BUILDCONF_FORCE should stay `N`, and skip `./buildconf --force` .
you can manually remove those code before start the build from command line.

**Comment by ziaratban** [comment]
my OS is CentOS 8.
i want to compile some extensions statically into PHP 8.0.3.
i edited `buildphp_1616776673.4.install.sh` and manually set `BUILDCONF_FORCE` to `Y` because `force` command is required according [this doc](https://www.php.net/manual/en/install.pecl.static.php).

if `BUILDCONF_FORCE` is the value of `N` then i can not compile extensions with php.
if `BUILDCONF_FORCE` is the value of `Y` then i get `unrecognized` warning.

But one thing is that the compilation runs successfully and `lsphp` is made next to `php` when i set  `BUILDCONF_FORCE` to `Y`.

**Comment by litespeedtech** [comment]
In the process rebuilding `configure` script, that option is lost. It has something to do with your automake/autoconf environment. 
You may need to manually fix it if you have to run `buildconf`, you can copy the section for `--enable-litespeed` back from original `configure` script. In this regard, not much we can help. 
Compiling extensions statically usually does not require rebuild configure script, should be controlled by `configure` parameters.

**Comment by ziaratban** [comment]
finally i edited `buildphp_1616813651.2.install.sh` and i replaced `--enable-litespeed` with `--with-litespeed`. (and set `BUILDCONF_FORCE` to `Y`).
I'm not receiving that warning right now.

@litespeedtech
Can you please explain what happened?

**Comment by litespeedtech** [comment]
Looks the `sapi/litespeed/config.m4` in the PHP 8.0.3 source tree has been over written with the one from litespeed universal patch package. 
PHP 8.0 has
```
PHP_ARG_ENABLE([litespeed],,
  [AS_HELP_STRING([--enable-litespeed],
    [Build PHP as litespeed module])],
  [no])
```
the universal patch has 
```
PHP_ARG_WITH(litespeed,,
[  --with-litespeed        Build PHP as litespeed module], no)
```
it is for PHP version < 5.3 
after rebuild configure script, the option name revert back to `--with-litespeed`.
If you manually apply the litespeed universal patch, you should only copy over *.c and *.h from the patch package.

**Comment by ziaratban** [comment]
@litespeedtech 
Finally i compiled everything manually and installed php `8.0.3`.
Litespeed Compile PHP tools no help me for this.
in during compile i came to a question.
what is difference between `php-8.0.3/sapi/litespeed` from [php distributions](https://www.php.net/distributions/php-8.0.3.tar.gz) and [litespeed release](https://www.litespeedtech.com/packages/lsapi/php-litespeed-7.9.tgz)?

**Comment by litespeedtech** [comment]
litespeed release is a universal patch that works with all versions of PHP. 
the one from PHP 8.0.3 source package is only for that version, and may not be the latest release of litespeed SAPI. If it is `LiteSpeed V7.9`, no need to apply the universal patch.
