### ISSUE TITLE
send empty header value

### ISSUE THREAD

**Issue by ziaratban** [litespeedtech/openlitespeed#230]
when i set below config in context of virtual host then lsws sent empty value.
`Header add Access-Control-Allow-Origin %{xxxx}e env=xxxx`

the empty value is not valid based on [this doc](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin).

apache not send this header.

**Comment by litespeedtech** [comment]
openlitespeed has limited support for that. 
`%{xxxx}e` header value should be supported, while `env=xxxx` condition is not.

**Comment by ziaratban** [comment]
> 
> 
> openlitespeed has limited support for that.
> `%{xxxx}e` header value should be supported, while `env=xxxx` condition is not.

ok. but still this issue without `env=xxxx`.

**Comment by litespeedtech** [comment]
You need to verify the environment `xxxx` is set and has value. 
I tested latest 1.7.10, it works fine with my test case. I set environment with a rewrite rule, and the env value is used as the header value.

**Comment by ziaratban** [comment]
I want to implement [`SetEnvIf`](https://httpd.apache.org/docs/current/mod/mod_setenvif.html) command by `Rewrite Rules` and `Static context > Header Operations`.

scenario for `CORS`:
```
a.com:
--> x.com (allow)
--> y.com (allow)
--> z.com (allow)
--> g.com (disallow)
```

`Virtual Hosts > Rewrite`
```
RewriteCond %{HTTP_HOST} ^a.com$
RewriteCond %{HTTP:Origin} ^https://(www\.)?(x\.com|y\.com|z\.com)$
RewriteCond %{REQUEST_FILENAME} -f
RewriteRule . - [E=AccessControlAllowOrigin:%0]
```
`Static Context > Header Operations`
```
Header add Access-Control-Allow-Origin %{AccessControlAllowOrigin}
```
It works on `x.com` , `y.com` and `z.com` but the `litespeed` for `g.com` sent empty header value for `Access-Control-Allow-Origin`

![image](https://user-images.githubusercontent.com/6462878/113659142-aa482080-96b6-11eb-8c79-4ac98da7b17b.png)


`OpenLiteSpeed` : `1.6.20`

**Comment by litespeedtech** [comment]
That is working as it should be.
because when `Origin` is `g.com`, 
```
RewriteCond %{HTTP:Origin} ^https://(www\.)?(x\.com|y\.com|z\.com)$
```
fails, the rewrite rule is not executed, env `AccessControlAllowOrigin` is not set.
It is not a server bug, but how to use rewrite rule to set correct environment value.

**Comment by ziaratban** [comment]
I am end user.
I expect the right output. i not send that header by php. 
Base on this references the `Access-Control-Allow-Origin` cannot empty .
https://www.w3.org/TR/2008/WD-access-control-20080912/#access-control-allow-origin
https://tools.ietf.org/html/rfc7540#section-8.1.2
https://tools.ietf.org/html/rfc7230#section-3.2
