### ISSUE TITLE
Log format - not consistent with logFormat in server conf

### ISSUE THREAD

**Issue by peterlh** [litespeedtech/openlitespeed#232]
Hi 
When using a server level access log, and having each vhost: `accesslog { useServer 1; }`

Using a custom log format, but the vhost: `XXX %h %l %u %t \"%r\" %>s %b` 
Added XXX for visual clarification. 

Seems that the vhost name is prepended to the logfile line, like a json array(?). 

My access.log looks like this then:
["vhostname.com"] XXX %h %l %u %t \"%r\" %>s %b

How to get rid of the prepended part, such the access log only contains my log format?

Expected result: Each would start with "XXX ...".

Server conf snip:
```
accesslog /var/log/lsws/access.2021-04-11.log {
logFormat               XXX %v %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"
logHeaders              0
rollingSize             0
keepDays                0
compressArchive         0
}
```

Vhost snip: 
```
accesslog  {
  useServer               1
}
```

Logfile output:
```
["domain.com"] XXX domain.com 10.20.30.40 - - [11/Apr/2021:11:08:26 +0200] "GET / HTTP/1.1" 200 11175 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
["domain.com"] XXX domain.com 10.20.30.40 - - [11/Apr/2021:11:08:29 +0200] "GET / HTTP/1.1" 200 11175 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
["domain.com"] XXX domain.com 10.20.30.40 - - [11/Apr/2021:11:08:35 +0200] "GET / HTTP/1.1" 200 11175 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
["domain.com"] XXX domain.com 10.20.30.40 - - [11/Apr/2021:11:28:59 +0200] "GET / HTTP/1.1" 200 11175 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/89.0.4389.90 Safari/537.36"
```

**Comment by peterlh** [comment]
Using OpenLiteSpeed 1.6.21 from apt on Ubuntu 18.04.2 LTS

**Comment by litespeedtech** [comment]
When you log vhost access at server level, it need to prepend the vhost name, so access from different virtual hosts can be differentiated. It cannot be changed.
However, you can get the result you want by not using `accesslog { useServer 1; }` , instead, set the log file path to the same file as the server level log file.

**Comment by peterlh** [comment]
Okay thanks for reply. 

I was unsure if there could be an issue with many filehandle / vhosts writing to the same access file on a server with many vhost like 300-500 vhosts using same accesslog?

**Comment by litespeedtech** [comment]
No worry, there is only one file handle used for each unique log file.

**Comment by peterlh** [comment]
Great, thanks!
