### ISSUE TITLE
Missing UDS support for reverse proxying external apps 

### ISSUE THREAD

**Issue by AmirHmZz** [litespeedtech/openlitespeed#234]
According to 1.7.10 release changelog, Openlitespeed is now able to proxy external backend servers using Unix Domain Sockets.
But there's no way to enter an `UDS` path in Address field of a `WebServer`.

![Untitled](https://user-images.githubusercontent.com/38752106/114875438-8604e600-9e12-11eb-8641-d09ab3e5c781.jpg)

I'm running openlitespeed 1.7.10 on ubuntu 20.04

**Comment by litespeedtech** [comment]
Just try `unix:/path` see if it works or not, the examples need update.

**Comment by AmirHmZz** [comment]
Thanks for instant ( litespeed ! ) reply.
I've tried it. It seems there's some kind of field validation rules on the **Address** field.
![Untitled](https://user-images.githubusercontent.com/38752106/114877324-6a024400-9e14-11eb-8764-92ebedd1951a.jpg)

**Comment by litespeedtech** [comment]
Looks the webadmin code need some update.
Can you try modify the config file directly, see if it works or not?

**Comment by AmirHmZz** [comment]
Yes, its worked fine. Only webadmin needs to be bug-fixed.
Thanks anyway!
