### ISSUE TITLE
Charset not being set correctly

### ISSUE THREAD

**Issue by alystair** [litespeedtech/openlitespeed#239]
All other options work, able to do Header Operations, etc... however this does not work at all:

![image](https://user-images.githubusercontent.com/159109/116321653-74afc800-a788-11eb-8bb5-adfb343ed287.png)

```conf
docRoot                   $VH_ROOT/

errorlog $VH_ROOT/logs/error.log {
  useServer               1
  logLevel                DEBUG
  rollingSize             10M
}

index  {
  useServer               0
}

context exp:^.+\.(css|js|json|md|html|svg)$ {
  location                $DOC_ROOT/$0
  allowBrowse             1

  rewrite  {

  }
  addDefaultCharset       on
  defaultCharsetCustomized utf-8

  phpIniOverride  {

  }
}

rewrite  {
  enable                  1
  autoLoadHtaccess        1
  logLevel                0
}
```

**Comment by litespeedtech** [comment]
It probably wont work with matching context, you can try it with a "/" context, currently it only apply to text/html and text/plain, next release will add more content type.

**Comment by litespeedtech** [comment]
1.7.12 should work better with other text/* content.

**Comment by litespeedtech** [comment]
This should not be an issue with 1.7.12 now.
