### ISSUE TITLE
Cannot install version 1.7.10 using apt upgrade

### ISSUE THREAD

**Issue by MaximKing1** [litespeedtech/openlitespeed#243]
When I try to update OpenLiteSpeed to 1.7.10 using `apt-get upgrade openlitespeed` but it shows that 1.6.21 is the latest? Any help

**Comment by qtwrk** [comment]
because apt/yum repo only contains v1.6.x , for now.

for 1.7 , try `/usr/local/lsws/admin/misc/lsup.sh -e 1.7.10`

**Comment by litespeedtech** [comment]
1.7.10 is still on the edge tier, available in edge repo.
1.7.11 will be put in stable tier soon (next week), you will be able to update with apt-get.

**Comment by MaximKing1** [comment]
> 1.7.10 is still on the edge tier, available in edge repo.
> 1.7.11 will be put in stable tier soon (next week), you will be able to update with apt-get.

Thank you

**Comment by litespeedtech** [comment]
1.7.11 is available now.
