### ISSUE TITLE
QUIC RFC 9000 support

### ISSUE THREAD

**Issue by harry-xiaomi** [litespeedtech/openlitespeed#245]
https://datatracker.ietf.org/doc/html/rfc9000 has been released.

**Comment by litespeedtech** [comment]
We released 1.7.11 as well.

**Comment by harry-xiaomi** [comment]
Thanks! I checked https://openlitespeed.org/downloads/, but the release notes has not been updated there.

**Comment by litespeedtech** [comment]
Maybe some thing wrong with the change log. It should matches
https://github.com/litespeedtech/openlitespeed/releases/tag/v.1.7.11

**Comment by harry-xiaomi** [comment]
DO NOT DEPLOY THIS VERSION OF HTTP/3 UNTIL IT IS IN AN RFC.  This
    version is still a work in progress.  For trial deployments, please
    use earlier versions.

Note that HTTP/3 is still an Active Internet-Draft, and should not be deployed in production. https://datatracker.ietf.org/doc/draft-ietf-quic-http/

**Comment by litespeedtech** [comment]
There are discussions and agreement on this in the email list. 
Everyone is good to deploy h3 once RFC9000 is official.
