### ISSUE TITLE
I guess blockbot is not supported in openlitespeed?

### ISSUE THREAD

**Issue by avpavp** [litespeedtech/openlitespeed#250]
it's referenced here:

https://www.litespeedtech.com/support/wiki/doku.php/litespeed_wiki:config:xmlrpc.php_bot_attack_block#example_2xmlrpcphp_bot

but I search the source code here, and while other flags seem to be in the source, this one isn't?

Just looking for confirmation / clarification...

Thanks!

**Comment by litespeedtech** [comment]
This has been added in release 1.7.12.
