### ISSUE TITLE
[STDERR] Failed to open temp file for swapping: Permission denied

### ISSUE THREAD

**Issue by franciscopaniskaseker** [litespeedtech/openlitespeed#251]
**OS:** Centos 7.9.2009
**Openlitespeed:** openlitespeed-1.7.11-1.el7.x86_64

**Error:**
```bash
[STDERR] Failed to open temp file for swapping: Permission denied
```

I do not have more details about. I am just seeing this error, but I am not seeing other problem that is related.

**Comment by litespeedtech** [comment]
This is another log with incomplete information, will get more detail in 1.7.12 . So, you will know which file path has problem.

**Comment by litespeedtech** [comment]
Release 1.7.12 should have addressed this.
