### ISSUE TITLE
HTTP3 version 1 support ?

### ISSUE THREAD

**Issue by AmirHmZz** [litespeedtech/openlitespeed#258]
I've seen support for http3 vsersion 1 is added in open litespeed since version 1.7.11 
But how to enable it ?

**Comment by litespeedtech** [comment]
As long as UDP port 443 is open on firewall, it is enabled automatically. no extra configuration required.

**Comment by AmirHmZz** [comment]
Is http/3 version 1 equal to h3-29?

**Comment by litespeedtech** [comment]
Yeah, about the same.
