### ISSUE TITLE
centos5 compile error

### ISSUE THREAD

**Issue by shuiqingliu** [litespeedtech/openlitespeed#26]
> make[3]: Leaving directory `/root/openlitespeed-1.3.8/src/spdy'
>Making all in sslpp
>make[3]: Entering directory `/root/openlitespeed-1.3.8/src/sslpp'
g++ -DHAVE_CONFIG_H -I. -I../../src -I../../src  -I/usr/include -I/usr/local/include  -g -O2 -fstack-protector  -MT sslconnection.o -MD -MP -MF .deps/sslconnection.Tpo -c -o sslconnection.o sslconnection.cpp
sslconnection.cpp: In member function ‘int SSLConnection::setTlsExtHostName(const char*)’:
sslconnection.cpp:394: error: ‘SSL_set_tlsext_host_name’ was not declared in this scope
make[3]: *** [sslconnection.o] Error 1
make[3]: Leaving directory `/root/openlitespeed-1.3.8/src/sslpp'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/openlitespeed-1.3.8/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/openlitespeed-1.3.8/src'
make: *** [all-recursive] Error 1

***
* I had Install dependencies like this:

<pre>
yum install epel-release
yum install gcc gcc-c++ make autoconf glibc rcs 
yum install pcre-devel openssl-devel expat-devel geoip-devel zlib-devel
</pre>
* my system information

`uname -a`
<pre
2.6.32-042stab094.8 #1 SMP Tue Dec 16 20:36:56 MSK 2014 x86_64 x86_64 x86_64 GNU/Linux
</pre>

`cat /etc/redhat-release`
<pre>CentOS release 5.10 (Final)</pre>

**Comment by litespeedtech** [comment]
Looks like the OpenSSL version is too old. 
You can try install OpenSSL 1.0.2 from source, which allows you to enable SPDY and HTTP/2.

**Comment by shuiqingliu** [comment]
Thank you very much,I will try update the OpenSSL to compile.
