### ISSUE TITLE
ModSecurity Error

### ISSUE THREAD

**Issue by dresch86** [litespeedtech/openlitespeed#260]
I have OLS (1.7.12) setup with ModSecurity and I am using the latest OWASP rule set from GitHub. It appears to be loading and finding the files, but throwing this error:

``2021-07-22 04:31:09.126788 [ERROR] [11] [Module:mod_security]setSecRule(type 2) /usr/local/lsws/modsec/owasp/crs/owasp-master.conf failed, ret -1, reason: 'Rules error. File: /usr/local/lsws/modsec/owasp/crs/rules/REQUEST-901-INITIALIZATION.conf. Line: 55. Column: 14. Expecting an action, got:  "id:901001,\
'.
``

This should be able to handle the slashes, correct?

**Comment by rperper** [comment]
There's actually a procedure to be followed to use the OWASP rule set.  Check out: https://openlitespeed.org/kb/openlitespeed-modsecurity-module/

Make sure that you've followed the procedures.  If so, I might suggest that you open a ticket.  Please include your OpenLiteSpeed error.log, and the httpd_config.conf file.

To answer your question, the slashes are fine.

Thanks,

Bob

**Comment by litespeedtech** [comment]
there is an extra space at the end of line as the error indicated, `"id:901001,\ '` 
It is not in the original rule file, so it must be added by accident. Just remove the extra space should fix it.
