### ISSUE TITLE
How to se set the LIBXML_CFLAGS and LIBXML_LIBS ?

### ISSUE THREAD

**Issue by GaneshKandu** [litespeedtech/openlitespeed#261]
```
[1mConfiguring extensions[m
checking io.h usability... no
checking io.h presence... no
checking for io.h... no
checking for strtoll... yes
checking for atoll... yes
checking whether to build with LIBXML support... yes
checking for libxml-2.0 >= 2.7.6... no
configure: error: in `/usr/local/apps/lsws/phpbuild/php-7.4.20':
configure: error: The pkg-config script could not be found or is too old.  Make sure it
is in your PATH or set the PKG_CONFIG environment variable to the full
path to pkg-config.

Alternatively, you may set the environment variables LIBXML_CFLAGS
and LIBXML_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

To get pkg-config, see <http://pkg-config.freedesktop.org/>.
See `config.log' for more details
**ERROR** Could not configure PHP build
```

I am getting this error while building php i have installed ols on custom path and LIBXML is also installed on custom path 
,i am trying to set LIBXML_CFLAGS and LIBXML_LIBS 

LIBXML_LIBS='-L/usr/local/apps/lib' LIBXML_CFLAGS='-I/usr/local/apps/include'

 OLS says 

 Invalid value at LIBXML_LIBS='-L/usr/local/apps/lib'
 
How i can set LIBXML_CFLAGS and LIBXML_LIBS ?

**Comment by GaneshKandu** [comment]
i am doing it from ```Tools > Compile PHP```

**Comment by litespeedtech** [comment]
You can try to add it to `Compiler Flags` in step 2. 
If it does not work, you have to manually patch the generated script.

**Comment by GaneshKandu** [comment]
> You can try to add it to `Compiler Flags` in step 2.

this not working

**Comment by GaneshKandu** [comment]
> You can try to add it to `Compiler Flags` in step 2.

not working.
