### ISSUE TITLE
OpenLiteSpeed logs

### ISSUE THREAD

**Issue by YashaCLabs** [litespeedtech/openlitespeed#262]
Hi

I want to see only the QUIC logs, more precicly, the congestion control module from the QUIC library.

- How can I configure the OLS server to disable all other logs and show only the logs from QUIC.
- How can I configure the QUIC inside the OLS to show only the logs from the congestion control module.

It is important to disable the rest of the logs due to high performance impact of all the logs beeing enabled.
[related thread on the OLS forum](https://forum.openlitespeed.org/threads/openlitespeed-logs.4994/#post-11403)

**Comment by litespeedtech** [comment]
In QuicEngine::init(), you need to add code like
```
    lsquic_logger_lopt("bbr=debug,cubic=info");
```
If you would like to define separate log control for your own module, please check lsquic_logger.c

**Comment by YashaCLabs** [comment]
added `lsquic_logger_lopt("bbr=debug,cubic=debug,pcc=debug");` to `QuicEngine::init(...)`
the `pcc=debug` is our module. I do see logs from `pcc`. what i want is to shutdown all the rest of the logging, from `quic` and the server. the only loggs i need is the `pcc`.

**Comment by litespeedtech** [comment]
You can remove `bbr=debug,cubic=debug,`, it is just an example, not required.

**Comment by YashaCLabs** [comment]
ok, thanks.

removing bbr and cubic from this line will remove them from logging. now how do i remove all the rest of the QUIC and the OLS server logs

**Comment by litespeedtech** [comment]
Change server->log, log level to a level other than DEBUG.

**Comment by YashaCLabs** [comment]
setting the log to:
![image](https://user-images.githubusercontent.com/57320189/128634366-da17b0a6-c014-49e3-a4a2-6e109915ab3f.png)
canceld almoust all the logs, except some [NOTICE] lines. but it also canceld the congestion control logs.

**Comment by litespeedtech** [comment]
You can try leave Log Level to DEBUG, set `Debug Level` to `NONE`.

**Comment by YashaCLabs** [comment]
makes no difference

**Comment by litespeedtech** [comment]
Please make sure to add your `lsquic_logger_lopt()` line below `setDebugLog(isQuicLogEnable);`.

**Comment by YashaCLabs** [comment]
```
void QuicEngine::setDebugLog(int is_enable) 
{
    if (is_enable)
    {
        lsquic_set_log_level("debug");
        lsquic_logger_lopt("bbr=debug,cubic=debug,pcc=debug");
        //lsquic_logger_lopt("pacer=info");
    }
    else
        lsquic_set_log_level("warn");
}
```
does this looks ok?

**Comment by litespeedtech** [comment]
No, you need to add your `lsquic_logger_lopt()` as the last line in that function to force it. Or, add it in `QuicEngine::init()`.

**Comment by YashaCLabs** [comment]
ok, this solved it.

thank u very much for your time.
