### ISSUE TITLE
Openlitespeed v1.7.xx have issues with modsecurity

### ISSUE THREAD

**Issue by die2mrw007** [litespeedtech/openlitespeed#267]
There is a major bug in latest Openlitespeed v1.7.xx as it has compatibility issues with modsecurity. If we enable modsec with either comodo or owasp ruleset, then the server have downtimes and slowdown. v1.6.xx of openlitespeed doesnt have this issue.

Please guide. This is a known issue since more than a month now and the only solution as of now is to downgrade openlitespeed to v1.6.xx.
But that isn't a good solution anyways.

**Comment by deewinc** [comment]
I hope it gets resolved soon. Over a month is such a long time for a critical security bug.

**Comment by litespeedtech** [comment]
while, it is the first time ever we were notified about it. 
we will need more information and environment to find out what is the cause.

**Comment by litespeedtech** [comment]
It is more likely a mod_security project bug, as we have not updated our integration code for a while, only update the mod_security project to the latest.

**Comment by die2mrw007** [comment]
> while, it is the first time ever we were notified about it.
> we will need more information and environment to find out what is the cause.

Actually, majority of users are facing this issue but unfortunately none reported it as either they are not using modsec with OLS or they havent updated OLS to v1. 7.xx yet.. And those who did, thought its a bug related to the web panel they are using and reported there. I am talking about cyberpanel in this case as there are many users reporting this issue in the cyberpanel support and group.

**Comment by deewinc** [comment]
> while, it is the first time ever we were notified about it.
> we will need more information and environment to find out what is the cause.

How comes it is the first time for you while this thread was posted earlier by someone else? And he determined that you're not using OLD modsecurity rules, meaning it's highly likely that it's not related to modsecurity itself.

https://github.com/usmannasir/cyberpanel/issues/653

**Comment by litespeedtech** [comment]
We have different team to handle different project. Not every one will monitor every issue of every project. 
Please understand that. 
And, does it have anything to do with 1.7 release? 

If you really want to help, please stop complaining and criticizing, think about how to help identify and address the problem.

**Comment by litespeedtech** [comment]
Back to the problem, we need get our hands on a server experiencing this problem, generate some debug logging and analyze what happened. 
@die2mrw007 would you like to create a ticket by writing email to bug <at> litespeedtech <dot> com  for further investigation?

**Comment by die2mrw007** [comment]
> Back to the problem, we need get our hands on a server experiencing this problem, generate some debug logging and analyze what happened.
> @die2mrw007 would you like to create a ticket by writing email to bug litespeedtech com for further investigation?

Sure, i will do the needful on my part in resolving this issue as soon as possible.

**Comment by deewinc** [comment]
> We have different team to handle different project. Not every one will monitor every issue of every project.
> Please understand that.
> And, does it have anything to do with 1.7 release?
> 
> If you really want to help, please stop complaining and criticizing, think about how to help identify and address the problem.

No one is complaining and no one is criticising. I'm just wondering why you're not aware of the issue. And just as you say, there are different teams handling different stuff. That's a reason enough as to why you're unaware of the issue. 

As for helping resolve the issue, I have pointed out at a possible cause from the thread I have tagged. That can give you a head start.

Another thing is the issue doesn't generate any error logs. So it's hard to know what's happening behind the scenes. Probably needs a guru from your side to dig deeper. 

As for me, I already downgraded the server. May be @die2mrw007 has a server running v.1.7.x.x to hand it over to you.

**Comment by litespeedtech** [comment]
Just pushed out a new test binary build, upgraded LibModSecurity from v3.0.4 to v3.0.5
Feel free to try it with command `/usr/local/lsws/admin/misc/lsup.sh -b -e 1.7.13` . 
Please let us know the result. If problem persists, please downgrade and contact (email) our support to arrange server access for trouble shooting.

**Comment by die2mrw007** [comment]
> Just pushed out a new test binary build, upgraded LibModSecurity from v3.0.4 to v3.0.5
> Feel free to try it with command `/usr/local/lsws/admin/misc/lsup.sh -b -e 1.7.13` .
> Please let us know the result. If problem persists, please downgrade and contact (email) our support to arrange server access for trouble shooting.

Thank you so much. I will try this out now and will get back if any issues.

**Comment by die2mrw007** [comment]
> Just pushed out a new test binary build, upgraded LibModSecurity from v3.0.4 to v3.0.5
> Feel free to try it with command `/usr/local/lsws/admin/misc/lsup.sh -b -e 1.7.13` .
> Please let us know the result. If problem persists, please downgrade and contact (email) our support to arrange server access for trouble shooting.

/usr/local/lsws/admin/misc/lsup.sh -b -e 1.7.13
lsup.sh Version: v2.83-9/29/2020.
download URL is https://openlitespeed.org/preuse/openlitespeed-1.7.13.tgz
2021-09-02 04:14:29 URL:https://openlitespeed.org/preuse/openlitespeed-1.7.13.tgz [77917891/77917891] -> "ols.tgz" [1]
[OK] litespeed: stopped.
cat: /tmp/lshttpd/lshttpd.pid: No such file or directory
All binaries are updated and service is started.

This is the output I received. I hope this output is fine.
Server under observation to check if problem still persist.

Thank you so much again for the speedy response and resolution. Love the way Litespeed as whole team.

**Comment by die2mrw007** [comment]
Server running very fine with the provided fix. Thank you so much.
I have asked few of openlitespeed users to check the same and report if they find any issues. So far, its all good it seems.

**Comment by litespeedtech** [comment]
Great! thanks for the confirmation.

**Comment by deewinc** [comment]
Sorry guys. 

Yet to push the update. 

I have a developer fixing stuff on my website and he's yet to complete the task. 

I will do a follow up this coming week and provide an update. 

Glad to hear that it works

**Comment by die2mrw007** [comment]
No issues after applying the patch provided by Litespeed team here since 3 days. So I guess we can mark this as solved.
