### ISSUE TITLE
Any possibilities to write in c scripting? e.g. compilation using tinycc etc

### ISSUE THREAD

**Issue by hiqsociety** [litespeedtech/openlitespeed#270]
Any possibilities to write in c scripting? e.g. compilation using tinycc etc

if so, where can i do a simple "hello world" test? any documentation on this?

**Comment by litespeedtech** [comment]
Is https://github.com/litespeedtech/openlitespeed/blob/master/addon/example/hellohandler.c close to what you want? 
https://github.com/litespeedtech/openlitespeed/blob/master/doc/ModuleDeveloperGuide.pdf is the doc.

**Comment by superdolt** [comment]
yes thx.

**Comment by hiqsociety** [comment]
yes thx
