### ISSUE TITLE
QUIC in OLS: supported or not?

### ISSUE THREAD

**Issue by systemcrash** [litespeedtech/openlitespeed#272]
Docs (and litespeed web) suggest that OpenLitespeed is QUIC enabled. But the OLS website specifically says it is not. 

https://www.litespeedtech.com/products/litespeed-web-server/editions

Which is correct?

https://openlitespeed.org/support/
`Does OpenLiteSpeed support QUIC?`
OLS does support HTTP/2 and SSL, but it does not yet support QUIC.

**Comment by litespeedtech** [comment]
OLS site is outdated. OLS support QUIC since 1.6 .
