### ISSUE TITLE
Accesslog not writing to stdout

### ISSUE THREAD

**Issue by gazrobur** [litespeedtech/openlitespeed#273]
**🐛 Bug report 🐛**

**Issue:** Openlitespeed stopped writing accesslog to the console (only error logs are shown). (version 1.7.14)

**Config:**
```
errorlog /dev/console {
        logLevel             NOTICE
        debugLevel           0
        rollingSize          10M
        enableStderrLog      1
}

accesslog /dev/console {
        logFormat "%{X-Forwarded-For}i %l %u %t "%r" %>s %b "%{Referer}i" "%{User-agent}i"
        rollingSize          10M    
        keepDays             30    
        compressArchive      0
        logReferer           1     
        logUserAgent         1
}
```

**Before:**
In the previous version of openlitespeed (1.7.11) it just worked. My thought was that something changed what was not documented well.

Please help me to get rid of this problem

**Comment by GiuseppeIuculano** [comment]
> It is for security reason, if you want to log to STDOUT, you can use `stdout` as file name.

I tried this but it doesn't work , how writes log to stdout?  this is important in a docker environment

**Comment by psy0rz** [comment]
i also have this problem, also see https://github.com/litespeedtech/ols-docker-env/issues/77

**Comment by litespeedtech** [comment]
`accesslog stdout { ...` should work now.
