### ISSUE TITLE
Cannot use vhost template variables to set environment variables

### ISSUE THREAD

**Issue by martincpt** [litespeedtech/openlitespeed#275]
I've just created a vhost template designed to host Django / Python WSGI applications. 

Each vhost member of this template should have it's corresponding virtualenv created and I want to set their PYTONPATH and LS_PYTHONBIN dynamically by passing its $VH_NAME variable.

**Environment:**
`PYTHONPATH=/home/ubuntu/.virtualenvs/$VH_NAME/lib/python3.8
LS_PYTHONBIN=/home/ubuntu/.virtualenvs/$VH_NAME/bin/python`

But it seems like it's not working. $VH_NAME (or any other template var) just not getting replaced when setting them in Environment variables.

Any idea how to fix or get around this?

Thanks!

**Comment by litespeedtech** [comment]
Made some code tweaks to accommodate this. You can try the latest beta build.
`/usr/local/lsws/admin/misc/lsup.sh -b -v 1.7.14`

**Comment by martincpt** [comment]
Awesome!

Looks like it's working with the latest beta.

Thank you for the fast tweaks!
