### ISSUE TITLE
workers write to disk

### ISSUE THREAD

**Issue by acrixl** [litespeedtech/openlitespeed#28]
workes constantly write to disk at 4Kb/s speed
what they write?
is this need to be persist across restarts?

**Comment by kopytov** [comment]
Workers writes status information "/tmp/lshttpd/.rtreport" every second. May be this is what you are looking for.

**Comment by hossiken** [comment]
iotop:
 794 be/4 nobody      0.00 B/s    3.87 K/s  0.00 %  0.00 % openlitespeed (lshttpd - #01)
  795 be/4 nobody      0.00 B/s    3.87 K/s  0.00 %  0.00 % openlitespeed (lshttpd - #02)
  796 be/4 nobody      0.00 B/s    3.87 K/s  0.00 %  0.00 % openlitespeed (lshttpd - #03)
  797 be/4 nobody      0.00 B/s    3.87 K/s  0.00 %  0.00 % openlitespeed (lshttpd - #04)
  798 be/4 nobody      0.00 B/s    3.87 K/s  0.00 %  0.00 % openlitespeed (lshttpd - #05)
  799 be/4 nobody      0.00 B/s    3.87 K/s  0.00 %  0.00 % openlitespeed (lshttpd - #06)
  800 be/4 nobody      0.00 B/s    3.87 K/s  0.00 %  0.00 % openlitespeed (lshttpd - #07)
  801 be/4 nobody      0.00 B/s    3.87 K/s  0.00 %  0.00 % openlitespeed (lshttpd - #08)
  768 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % openlitespeed (lshttpd - main)
    1 be/4 root        0.00 B/s    0.00 B/s  0.00 %  0.00 % init [3]

The above 8 threads 'tick' around ~4k every second.  I am/was staging this build on a xen vm (virtual machine). I noticed this problem when this vm surpassed my HOME DVR!!! in sector write request in xen top.  This is clearly unacceptable and would greatly appropriate a fix/work around.  Also, I am very tankful this was NOT on a SSD - I imagine this would eat through the wear leveling of a SSD rapidly. 

Thoughts?

**Comment by litespeedtech** [comment]
The real time report is configurable now and you can write to a share memory if you want.

**Comment by TBMSP** [comment]
2024 OpenLiteSpeed 1.7.19 still 4k every second.
