### ISSUE TITLE
Rocky8 have an issue with the failovermethod line in CentOS.repo

### ISSUE THREAD

**Issue by JOduMonT** [litespeedtech/openlitespeed#283]
I installed OLS this way and
sudo rpm --import https://rpms.litespeedtech.com/centos/RPM-GPG-KEY-litespeed
sudo dnf config-manager --add-repo https://rpms.litespeedtech.com/centos/litespeed.repo
sudo dnf install -y openlitespeed
sudo systemctl enable --now lsws

the only issue if in your repo file you have `failovermethod=priority` which Rocky 8 doesn't like

````
Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/litespeed.repo; Configuration: OptionBinding with id "failovermethod" does not exist                                                                             Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/litespeed.repo; Configuration: OptionBinding with id "failovermethod" does not exist                                                                             Invalid configuration value: failovermethod=priority in /etc/yum.repos.d/litespeed.repo; Configuration: OptionBinding with id "failovermethod" does not exist
````

**Comment by istiak101** [comment]
`failovermethod=priority` is removed from dnf in RHEL 8. The dnf version you are using is 1:1 with RHEL. This issue is already patched in upstream Fedora and will not give any output for this wrong configuration. I suggest @litespeedtech to remove `failovermethod=priority` from their .repo file.

**Comment by istiak101** [comment]
@litespeedtech you also need to fix .rpm specs for Rocky 8. litespeed-repo-1.2-1 can't be installed on due to dependency issue.

**Comment by litespeedtech** [comment]
Fixed a while ago.
