### ISSUE TITLE
ftp.pcre.org is no longer available

### ISSUE THREAD

**Issue by Janthon-Kyle** [litespeedtech/openlitespeed#288]
Error in build.sh when buildiing PCRE.

Message for Official Websit.

"Note that the former **ftp.pcre.org** FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead."

**Comment by karlisk** [comment]
it should be "https://ftp.exim.org/pub/pcre/pcre-8.43.tar.gz" instead of "ftp://ftp.pcre.org/pub/pcre/pcre-8.43.tar.gz".

**Comment by istiak101** [comment]
Another nice thing would be switching to pcre2-10.39 .

**Comment by litespeedtech** [comment]
Thanks. Pull request has been merged.
