### ISSUE TITLE
mmap never uses when sendfile is enabled

### ISSUE THREAD

**Issue by kopytov** [litespeedtech/openlitespeed#29]
About "Use sendfile" option:

> Specifies whether to use the sendfile() system call to serve static files. Static files can be served in four different ways: memory buffer cache, memory-mapped cache, plain read/write, and sendfile(). Files smaller than the Max Cached Small File Size are served from memory buffer cache. Files larger than the Max Cached Small File Size but smaller than the Max MMAP File Size will be served from memory-mapped cache. Files larger than the Max MMAP File Size will be served via plain read/write or sendfile(). Sendfile() is a "zero copy" system call that can greatly reduce CPU utilization when serving very large static files. Sendfile() requires an optimized network card kernel driver and thus may not be suitable for some small-vendor network adapters.

I have a openLiteSpeed server with options:
* Max Cached Small File Size (bytes):4096
* Total Small File Cache Size (bytes): 20M
* Max MMAP File Size (bytes): 256K
* Total MMAP Cache Size (bytes): 40M
* Use sendfile(): Yes

When I try to download file with size 21K openLiteSpeed should use mmap. But it use sendfile:

    read(21, "GET /wp-content/themes/fozzy/intro-experiment/css/style.css HTTP/1.0\r\nReferer: http://dev.fozzy.com/en/intro-experiment-prices\r\nUser-Agent: Wget/1.12 (linux-gnu)\r\nAccept: */*\r\nHost: dev.fozzy.com\r\nConnection: Keep-Alive\r\n\r\n", 2044) = 223
    stat("/srv/www/dev/fozzy.com/wp-content/cache/supercache/dev.fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css/index.html", 0x737dd8) = -1 ENOENT (No such file or directory)
    stat("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", {st_mode=S_IFREG|0775, st_size=20956, ...}) = 0
    stat("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", {st_mode=S_IFREG|0775, st_size=20956, ...}) = 0
    stat("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", {st_mode=S_IFREG|0775, st_size=20956, ...}) = 0
    readlink("/srv/www/dev/fozzy.com/wp-content", 0x7fff6c716e31, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes", 0x7fff6c716e31, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes/fozzy", 0x7fff6c716e31, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment", 0x7fff6c716e31, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css", 0x7fff6c716e31, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", 0x7fff6c716e31, 4094) = -1 EINVAL (Invalid argument)
    open("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", O_RDONLY) = 22
    fcntl(22, F_SETFD, FD_CLOEXEC) = 0
    writev(21, [{"HTTP/1.0 200 OK\r\n", 17}, {"cache-control: public, max-age=604800\r\nexpires: Thu, 09 Apr 2015 09:51:37 GMT\r\netag: \"51dc-547f32c1-3f4b3\"\r\nlast-modified: Wed, 03 Dec 2014 15:56:49 GMT\r\ncontent-type: text/css\r\ncontent-length: 20956\r\naccept-ranges: bytes\r\ndate: Thu, 02 Apr 2015 09:51:37 GMT\r\nserver: LiteSpeed\r\nconnection: keep-alive\r\n", 303}, {"\r\n", 2}], 3) = 322
    sendfile(21, 22, [0], 20956) = 20956

If I change "Use sendfile()" to "No" then openLiteSpeed starts to use mmap for the same file:

    read(21, "GET /wp-content/themes/fozzy/intro-experiment/css/style.css HTTP/1.1\r\nUser-Agent: curl/7.41.0\r\nHost: dev.fozzy.com\r\nAccept: */*\r\n\r\n", 2044) = 1
    stat("/srv/www/dev/fozzy.com/wp-content/cache/supercache/dev.fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css/index.html", 0x737dd8) = -1 ENOENT (No such file or directory)
    stat("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", {st_mode=S_IFREG|0775, st_size=20956, ...}) = 0
    stat("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", {st_mode=S_IFREG|0775, st_size=20956, ...}) = 0
    stat("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", {st_mode=S_IFREG|0775, st_size=20956, ...}) = 0
    readlink("/srv/www/dev/fozzy.com/wp-content", 0x7fff413921d1, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes", 0x7fff413921d1, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes/fozzy", 0x7fff413921d1, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment", 0x7fff413921d1, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css", 0x7fff413921d1, 4094) = -1 EINVAL (Invalid argument)
    readlink("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", 0x7fff413921d1, 4094) = -1 EINVAL (Invalid argument)
    open("/srv/www/dev/fozzy.com/wp-content/themes/fozzy/intro-experiment/css/style.css", O_RDONLY) = 22
    fcntl(22, F_SETFD, FD_CLOEXEC) = 0
    mmap(NULL, 20956, PROT_READ, MAP_PRIVATE, 22, 0) = 0x7f2569701000
    close(22)                 = 0
    writev(21, [{"HTTP/1.1 200 OK\r\n", 17}, {"cache-control: public, max-age=604800\r\nexpires: Thu, 09 Apr 2015 12:24:37 GMT\r\netag: \"51dc-547f32c1-3f4b3\"\r\nlast-modified: Wed, 03 Dec 2014 15:56:49 GMT\r\ncontent-type: text/css\r\ncontent-length: 20956\r\naccept-ranges: bytes\r\ndate: Thu, 02 Apr 2015 12:24:37 GMT\r\nserver: LiteSpeed\r\n", 279}, {"\r\n", 2}, {"@charset \"utf-8\";\n\n@font-face {\n\t\tfont-family: 'Myriad Pro';\n\t\tsrc: url('../fonts/mp-regular-webfont.eot');\n\t\tsrc: url('../fonts/mp-regular-webfont.eot?#iefix') format('embedded-opentype'), url('../fonts/mp-regular-webfont.woff') format('woff'), url('../fonts/mp-regular-webfont.svg#MyriadProRegular') format('svg'), url('../fonts/mp-regular-webfont.ttf') format('truetype');\n\t\tfont-weight: normal;\n\t\tfont-style: normal;\n}\n\n@font-face {\n\t\tfont-family: 'Myriad Pro Cond';\n\t\tsrc: url('../fonts/myriadpro-cond-webfont.eot');\n\t\tsrc: url('../fonts/myriadpro-cond-webfont.eot?#iefix') format('embedded-opentype'), url('../fonts/myriadpro-cond-webfont.woff') format('woff'), url('../fonts/myriadpro-cond-webfont.ttf') format('truetype');\n\t\tfont-weight: normal;\n\t\tfont-style: normal;\n}\n\n@font-face {\n\t\tfont-family: 'Myriad Pro Cond';\n\t\tsrc: url('../fonts/MyriadPro-SemiboldCond.eot');\n\t\tsrc: url('../fonts/MyriadPro-SemiboldCond.eot?#iefix') format('embedded-opentype'), url('../fonts/MyriadPro-SemiboldCond.woff') format('woff'), url('../fonts/MyriadPro-SemiboldCond.ttf') format('truetype');\n\t\tfont-weight: 600;\n\t\tfont-style: normal;\n}\n\n@font-face {\n\t\tfont-family: 'Myriad Pro Cond';\n\t\tsrc: url('../fonts/MyriadPro-SemiboldCondIt.eot');\n\t\tsrc: url('../fonts/MyriadPro-SemiboldCondIt.eot?#iefix') format('embedded-opentype'), url('../fonts/MyriadPro-SemiboldCondIt.woff') format('woff'), url('../fonts/MyriadPro-SemiboldCondIt.ttf') format('truetype');\n\t\tfont-weight: 600;\n\t\tfont-style: italic;\n}\n\n@font-face {\n\t\tfont-family: 'Rouble';\n\t\tsrc: "..., 20956}], 4) = 14344
    epoll_ctl(6, EPOLL_CTL_MOD, 21, {EPOLLIN|EPOLLOUT|EPOLLERR|EPOLLHUP, {u32=21, u64=21}}) = 0
    epoll_wait(6, {}, 10, 100) = 0
    epoll_wait(6, {{EPOLLOUT, {u32=21, u64=21}}}, 10, 100) = 1
    writev(21, [{" none;\n\t\tmargin: 22px 0 68px 0;\n\t\tpadding: 0;\n}\n\n.menu2 > ul > li > ul > li {\n\t\tmargin: 22px 0 0 0;\n}\n\n.en .menu2 > ul > li > ul,\n.en
    menu2 > ul > li > ul > li {\n\t\tmargin-top: 27px;\n}\n\n.en .menu2 > ul > li > ul {\n\t\tmargin-bottom: 78px;\n}\n\n.btn-hold {\n\t\tmargin: 60px 5px 0 5px;\n}\n\n.top-text .btn-hold {\n\t\tmargin-top: 56px;\n}\n\n.clouds-bg h3 {\n\t\tdisplay: none;\n}\n\n.clouds-bg .btn-hold {\n\t\tmargin-top: 66px;\n}\n\n.benefits .btn-hold {\n\t\tmargin-top: 63px;\n}\n\n.about .btn-hold {\n\t\tmargin-top: 59px;\n}\n\n.btn {\n\t\tdisplay: block;\n\t\tposition: relative;\n\t\ttext-decoration: none;\n\t\tcolor: #fff;\n\t\tvertical-align: top;\n}\n\n.btn .t {\n\t\tposition: relative;\n\t\tfont-family: \"Myriad Pro Cond\", \"Trebuchet MS\", Arial, Helvetica, sans-serif;\n\t\tfont-weight: 600;\n\t\tfont-style: italic;\n\t\tfont-size: 33px;\n\t\ttext-transform: uppercase;\n\t\tletter-spacing: 1px;\n\t\tdisplay: inline-block;\n\t\tpadding: 3px 41px 0 41px;\n\t\theight: 77px;\n\t\tline-height: 77px;\n\t\tdisplay: block;\n\t\ttext-align: left;\n}\n\n.top-text .btn,\n.top-text .btn .t {\n\t\tdisplay: inline-block;\n}\n\n.top-text .btn .t {\n\t\tpadding-left: 87px;\n\t\tpadding-right: 87px;\n\t\theight: 68px;\n\t\tline-height: 68px;\n}\n\n.btn .b {\n\t\tposition: absolute;\n\t\ttop: 0;\n\t\tleft: 0;\n\t\tright: 0;\n\t\tbottom: 0;\n\t\t-moz-transform: skew(-10deg);\n\t\t-o-transform: skew(-10deg);\n\t\t-webkit-transform: skew(-10deg);\n\t\ttransform: skew(-10deg);\n}\n\n.btn:hover .b {\nfilter:progid:DXImageTransform    Microsoft.Alpha(opacity=90);\n\t\topacity: 0.9;\n}\n\n.top-text .btn .b {\n\t\tbackground: url(data:image/svg+xml;base64,PD94bWwgdmVyc2lvbj0iMS4wIiA/Pgo8c3ZnIHh"..., 6910}], 1)

So it looks like a bug: openLiteSpeed ignores option "Max MMAP File Size" and always uses sendfile when it enabled. This behavior reduces page loading speed when it has a lot of js-, css- & small images.

    $ /usr/local/lsws/bin/litespeed --version
    LiteSpeed/1.3.9 Open

**Comment by litespeedtech** [comment]
We intentionally do that because we think sendfile() is still faster than mmap() + writev(). 
You believe mmap() + writev() is faster for many smaller files?

**Comment by kopytov** [comment]
Yes, I've made simple benchmarks by using "time wget -qp ..."

With enabled sendfile I've got average download time about 4,6-4,8 seconds. And about 3,3-3,4 seconds when sendfile is disabled.

**Comment by centminmod** [comment]
interesting maybe that explains my benchmarks for OLS 1.4.6 and HTTP/2 254 World Country Flags demo at https://h2ohttp2.centminmod.com:8099/flags.html.

Average flag size is between 1.6-1.9KB

Results at https://h2ohttp2.centminmod.com:8099/webpagetests1.html ?

using default values in OLS

    Static File Delivery Optimization
    Max Cached Small File Size (bytes)	4096
    Total Small File Cache Size (bytes)	20M
    Max MMAP File Size (bytes)	256K
    Total MMAP Cache Size (bytes)	40M
    Use sendfile()	Yes

**Comment by kopytov** [comment]
Hi centminmod. In your example image size is about 1,5-1,8K (less than "Max Cached Small File Size"). In this case OLS stores files into process memory & does not use mmap or sendfile (even if "Use sendfile()" is Yes).

The problem occurs when files sizes are greater than "Max Cached Small File Size".

**Comment by kopytov** [comment]
To illustrate the problem I took clean SSD server with Linux, created 2 equal OpenVZ containers with OLS (first — "Use sendfile(): Yes", second — "Use sendfile(): No", other settings equal).

Next I took centminmod's flags page and changed img src to bigger images (average image size now about 20K):
 * http://sendfile.fozzy.com/flags.html
 * http://mmap.fozzy.com/flags.html

Next I wrote simple bechmarking script which download entire page with images:

    #!/bin/bash
    
    while [ 1 ]
    do
        echo -n "$( date ) : "
        /usr/bin/time -f "%e" wget -qp $@ 2>&1
        rm -rf *.fozzy.com
        sleep 10
    done

And now the results:

    $ ./speed-test http://mmap.fozzy.com/flags.html
    Fri Apr  3 17:01:29 MSK 2015 : 12.47
    Fri Apr  3 17:01:51 MSK 2015 : 12.45
    Fri Apr  3 17:02:14 MSK 2015 : 12.45
    Fri Apr  3 17:02:36 MSK 2015 : 12.45
    Fri Apr  3 17:02:59 MSK 2015 : 12.50
    Fri Apr  3 17:03:21 MSK 2015 : 12.44
    Fri Apr  3 17:03:44 MSK 2015 : 12.44
    Fri Apr  3 17:04:06 MSK 2015 : 12.46
    Fri Apr  3 17:04:29 MSK 2015 : 12.45
    Fri Apr  3 17:04:51 MSK 2015 : 13.82

    $ ./speed-test http://sendfile.fozzy.com/flags.html
    Fri Apr  3 17:05:13 MSK 2015 : 23.77
    Fri Apr  3 17:05:47 MSK 2015 : 24.08
    Fri Apr  3 17:06:21 MSK 2015 : 23.96
    Fri Apr  3 17:06:55 MSK 2015 : 23.74
    Fri Apr  3 17:07:29 MSK 2015 : 23.83
    Fri Apr  3 17:08:03 MSK 2015 : 23.76
    Fri Apr  3 17:08:36 MSK 2015 : 23.80
    Fri Apr  3 17:09:10 MSK 2015 : 23.76
    Fri Apr  3 17:09:44 MSK 2015 : 23.94
    Fri Apr  3 17:10:18 MSK 2015 : 23.82

So about two times faster with disabled sendfile.

**Comment by litespeedtech** [comment]
Please try the following patch to keep MMAP active.

diff --git src/main/httpserver.cpp src/main/httpserver.cpp
index 3788186..c185d94 100644
--- src/main/httpserver.cpp
+++ src/main/httpserver.cpp
@@ -1809,8 +1809,8 @@ int HttpServerImpl::configTuning(const XmlNode *pRoot)
 #endif
     config.setUseSendfile(val);
 
-    if (val)
-        FileCacheDataEx::setMaxMMapCacheSize(0);
+//     if (val)
+//         FileCacheDataEx::setMaxMMapCacheSize(0);
 
     const char *pValue = pNode->getChildValue("SSLCryptoDevice");

**Comment by kopytov** [comment]
Thank you.

I've built OLS with your patch on mmap.fozzy.com, then enable sendfile and it still works fast.

**Comment by litespeedtech** [comment]
For the flags test, we will try some optimization on the HTTP2 implementation to make it more efficient delivering many small files. 
For https connections, sendfile() cannot be used anyway.

**Comment by centminmod** [comment]
sweet thanks @kopytov for clarification and test data and thanks @litespeedtech for the fix :)

**Comment by kopytov** [comment]
Fixed by @litespeedtech in 1.3.10.
