### ISSUE TITLE
Install without third-party/modules?

### ISSUE THREAD

**Issue by kalleboy** [litespeedtech/openlitespeed#295]
How to not install third-party tools or modules like ModSecurity, BoringSSL and Luajit during installation? Is there any way to customize the modules to build? Is there any option to prevent their installation?

Thanks.

**Comment by kalleboy** [comment]
for build.sh, I have no idea but for configure;
"./configure --with-brotli=no --with-iptogeo2=no --with-ip2loc=no --with-lua=no --with-bssl=no" didn't work.

**Comment by litespeedtech** [comment]
That requires updating https://github.com/litespeedtech/openlitespeed/blob/master/src/modules/CMakeLists.txt manually.

**Comment by rperper** [comment]
Note that we now include a build.sh script which I believe addresses your request: https://openlitespeed.org/kb/install-openlitespeed-from-source-with-build-script/

This script still does the creation of the third-party directory, which includes the local (to that directory) installation of ModSecurity, Boring, etc.  However it does it all for you and is optimized.  I just used to to compile the ARM version from source and we maintain this fully.  

If this is insufficient for you, please let us know in what way it doesn't work.
