### ISSUE TITLE
Get real client ip when openlitespeed is backend and nginx or haproxy is set as revesed proxy

### ISSUE THREAD

**Issue by christianostrem** [litespeedtech/openlitespeed#296]
Hi,

We are using openlitespeed as webserver with an nginx proxy server in front of our openlitespeed serveres.
But we cant get the real ip. We are only getting the reversed proxy ip.

We have tried all of the options under: Use Client IP in Header

We have tested this with apache also with the RemoteIPProxyProtocol On using the mod_remoteip module
and this is working just fine.

**Comment by AKASHRP98** [comment]
@christianostrem You need to set "option forwardfor" in frontend option on haproxy config file

**Comment by christianostrem** [comment]
We have done that in haproxy, we had a working example with apache using mod_remoteip.
Not working in ols, the ssl hadshake broke.

**Comment by christianostrem** [comment]
We have installed nginx now. Where we have everything up and running except the real ip.

**Comment by AKASHRP98** [comment]
Add this " useIpInProxyHeader 1 " to httpd_config file

**Comment by AKASHRP98** [comment]
This works me when using OLS behind haproxy

**Comment by christianostrem** [comment]
Use Client IP in Header | Yes
We have tried this many times with no success. 
What type of proxy are you using. Have you installed it your self?

**Comment by AKASHRP98** [comment]
I am using Haproxy. And it works well

**Comment by christianostrem** [comment]
Okey. We have tried wit ha proxy and cant get it to work. Can you paste or send me your ha proxy configuration. 
PS: We have the ssl termintation on the ols server and is using ssl. That might be a big difference.

**Comment by AKASHRP98** [comment]
global
        #nuster cache off data-size 100m
        master-worker
        maxconn 50000
        tune.ssl.default-dh-param 2048
        ssl-dh-param-file /opt/Hosting/dhparam.pem
        user hosting
        group hosting
        chroot /var/lib/hosting
        log /dev/log local0
defaults
        log /dev/log local0
        option httplog
        mode http
        log-format "%[capture.req.hdr(0)] %[capture.res.hdr(0)] %ci [%tr] %b %{+Q}r %TR/%Tw/%Tc/%Tr/%Ta %ST %B %tsc %ac/%fc/%bc/%sc/%rc [%[capture.req.hdr(>        option http-ignore-probes
        timeout connect 30s
        timeout client 30s
        timeout server 30s
        timeout http-request 30s
frontend nonssl
        bind *:80
        option forwardfor
        acl letsencrypt-acl path_beg /.well-known/acme-challenge/
    use_backend letsencrypt-backend if letsencrypt-acl
        http-request capture req.hdr(Host) len 100
        http-request capture req.fhdr(User-Agent) len 100
        declare capture response len 20
        http-response capture res.hdr(x-cache) id 0
        acl has_domain hdr(Host),map_str(/opt/Hosting/routes.map) -m found
        acl has_wildcard hdr(Host),map_sub(/opt/Hosting/wildcardroutes.map) -m found
        http-request reject if !has_domain !has_wildcard
        acl has_cookie hdr_sub(cookie) wordpress_logged_in
        acl has_path path_sub wp-admin || wp-login
        acl static_file path_end .js || .css || .png || .jpg || .jpeg || .gif || .ico
        use_backend nocache if has_path || has_cookie
        use_backend static if static_file
        use_backend %[req.hdr(host),map(/opt/Hosting/routes.map)] if { req.hdr(host),map(/opt/Hosting/routes.map) -m found }
        use_backend %[req.hdr(host),map_sub(/opt/Hosting/wildcardroutes.map)] if {req.hdr(host),map_sub(/opt/Hosting/wildcardroutes.map) -m found }
backend Akash
    #nuster cache off
   # nuster rule r0
    http-response set-header x-cache HIT if { nuster.cache.hit }
    http-response set-header x-cache MISS unless { nuster.cache.hit }
    server s1 0.0.0.0:8088
backend nocache
    http-response set-header x-cache BYPASS
    server s2 0.0.0.0:8088
backend static
    http-response set-header x-type STATIC
    server s2 0.0.0.0:8088
backend Staging
  # http-response set-header x-cache BYPASS
   # http-response set-header x-type STAGING
        server s2 0.0.0.0:8088
backend letsencrypt-backend
    server letsencrypt 127.0.0.1:8888

**Comment by christianostrem** [comment]
If ıam reading the config correct you have the ssl termination on the proxy server.
We have the ssl termination on the ols server and its here it gets tricky.

**Comment by AKASHRP98** [comment]
Yeah we terminate ssl on haproxy

**Comment by christianostrem** [comment]
That simplifies things a lot when it comes to real ip. We have the ssl on the ols of security reasons.

**Comment by AKASHRP98** [comment]
Okay I will try without terminating ssl

**Comment by christianostrem** [comment]
On apache we need to enable the RemoteIPProxyProtocol On by using the apache mod_remoteip module.

**Comment by christianostrem** [comment]
> Okay I will try without terminating ssl

The ssl termination needs to be on the Ols servere instead of the Proxy server. 
On haproxy we used send_proxy but then things stopped working.

**Comment by AKASHRP98** [comment]
Can you send me your haproxy conf file

**Comment by christianostrem** [comment]
I think the config was like this.
It was a colleague of mine who was setting up the server. He isn't online yet.
```
global
    #log         127.0.0.1 local2    #Uncomment if using rsyslog /var/log/haproxy.log
    log         /dev/log local0      #When rsyslog is configured to populate /var/log/haproxy.log
    chroot      /var/lib/haproxy
    pidfile     /var/run/haproxy.pid
    maxconn     4000
    user        haproxy
    group       haproxy
    daemon
    stats socket /var/lib/haproxy/stats

defaults
    mode                    http
    log                     global
    option                  httplog
    option                  dontlognull
    option                  redispatch
    retries                 3
    timeout http-request    10s
    timeout queue           1m
    timeout connect         10s
    timeout client          1m
    timeout server          1m
    timeout http-keep-alive 10s
    timeout check           10s
    maxconn                 4000

frontend loadbalancer01
    bind *:80
    default_backend backend_http

frontend main_https_listen
    bind *:443
    mode                tcp
    option              tcplog
    log                 global
    tcp-request inspect-delay 5s
    tcp-request content accept if { req.ssl_hello_type 1 }
    default_backend backend_https

backend backend_https
    description ssl backend server
    mode tcp
    balance source
    option ssl-hello-chk
    server 255.255.255.255 255.255.255.255:443 send-proxy

backend backend_http
    description http backend server
    balance     roundrobin    #if multiple server, go to next available
    server 255.255.255.255 255.255.255.255:80 send-proxy
```

**Comment by christianostrem** [comment]
Replaced the ip with: 255.255.255.255

**Comment by christianostrem** [comment]
We hare running HAProxy version 2.5.0-f2e0833 2021/11/23 - https://haproxy.org/

**Comment by qtwrk** [comment]
you should also try enable the debug log on OLS , to see what headers it received and what is the value of it.

**Comment by AKASHRP98** [comment]
Send-proxy is the culprit. As haproxy passes Proxy-protocol, openlitespeed is not accepting these type of requests. You may try Haproxy with transparent binding.
Maybe someone from Litespeed could help you.

**Comment by christianostrem** [comment]
> you should also try enable the debug log on OLS , to see what headers it received and what is the value of it.

I have set the server log error.log to debug with debug lvl high. 
I haven found a x-forward header yet. 
Am I Debugging the correct way?

**Comment by qtwrk** [comment]
```
2022-01-14 12:09:59.218416 [DEBUG] [3505581] [127.0.0.1:59818:HTTP2-1] HPACK decode: (00/00/00) 18 x-forwarded-proto: https
2022-01-14 12:09:59.218437 [DEBUG] [3505581] [127.0.0.1:59818:HTTP2-1] HPACK decode: (00/00/00) 18 x-forwarded-for: 123.123.123.123
x-forwarded-proto: https
x-forwarded-for: 123.123.123.123
```


if you don't these , then I believe the proxy did not send the header at all.

**Comment by christianostrem** [comment]
> Send-proxy is the culprit. As haproxy passes Proxy-protocol, openlitespeed is not accepting these type of requests. You may try Haproxy with transparent binding. Maybe someone from Litespeed could help you.

Thats good to know. We are using nginx now, but we will definitely try this. I dont know if anyone at litespeed is willing to help. Since they dosent really offer any support other then the forum, but ill try to get hold on one in slack. If you know of anyone who is willing to help. pls tell.

**Comment by christianostrem** [comment]
> ```
> 2022-01-14 12:09:59.218416 [DEBUG] [3505581] [127.0.0.1:59818:HTTP2-1] HPACK decode: (00/00/00) 18 x-forwarded-proto: https
> 2022-01-14 12:09:59.218437 [DEBUG] [3505581] [127.0.0.1:59818:HTTP2-1] HPACK decode: (00/00/00) 18 x-forwarded-for: 123.123.123.123
> x-forwarded-proto: https
> x-forwarded-for: 123.123.123.123
> ```
> 
> if you don't see log entries like these , then I believe the proxy did not send the header at all.

Are you showing the access log or the error log.

**Comment by qtwrk** [comment]
it's from `tail -f /usr/local/lsws/logs/error.log | grep -i x-forward`

**Comment by christianostrem** [comment]
> it's from `tail -f /usr/local/lsws/logs/error.log | grep -i x-forward`

Super. Thanks ill check.

**Comment by qtwrk** [comment]
further more , you should see this 

```
[127.0.0.1:59822:HTTP2-1] HttpSession::processNewReqInit client IP from 'X-Forwarded-For: 123.123.123.123'.
...
...
...
[127.0.0.1:59822:HTTP2-1] update REMOTE_ADDR based on X-Forwarded-For header to 123.123.123.123
```
in particular, the last line if 1) proxy sends x-forward , and 2) you have enabled the true client IP in OLS

**Comment by christianostrem** [comment]
> further more , you should see this
> 
> ```
> [127.0.0.1:59822:HTTP2-1] HttpSession::processNewReqInit client IP from 'X-Forwarded-For: 123.123.123.123'.
> ...
> ...
> ...
> [127.0.0.1:59822:HTTP2-1] update REMOTE_ADDR based on X-Forwarded-For header to 123.123.123.123
> ```
> 
> in particular, the last line if 1) proxy sends x-forward , and 2) you have enabled the true client IP in OLS

Okey. Super ill check that to. Good to know what Iam looking for.

**Comment by christianostrem** [comment]
One more question. Did you try to get it working with binding?

**Comment by litespeedtech** [comment]
Maybe Linux virtual server (LVS) is a better choice for your need. It is a true L4 load balancer, and faster than HAProxy.

**Comment by christianostrem** [comment]
We are using the litespeed adc no though it dosent fix the issue but its not the adc its the ols that dosent support the proxy protocol. We have solved it by have the same ssl on the adc and the ols.
