### ISSUE TITLE
Auto Start="Throught CGI Daemon" & Run On Start Up="suEXEC Daemon" don't work

### ISSUE THREAD

**Issue by kopytov** [litespeedtech/openlitespeed#30]
If you will create LSAPI App with settings from subject, you will get errors:

    invalid value of <runOnStartUp>:2, use default=0
    invalid value of <autoStart>:2, use default=0

**Comment by litespeedtech** [comment]
Yes, this is a bug of 1.3.x and it was Fixed. 
Thanks.
