### ISSUE TITLE
503 After successful compile.

### ISSUE THREAD

**Issue by sqpp** [litespeedtech/openlitespeed#300]
Hey, 

I was able to finally make the build on arm64 (Ubuntu), although after starting the server, I get into 503 error. I also noticed for instance that the /usr/local/lsws/phpbuild and /usr/local/lsws/php directories are empty. 

Is there any way to fix this?

**Comment by litespeedtech** [comment]
you need to compile lsphp binary manually for arm64 as well.

**Comment by litespeedtech** [comment]
`--enable-litespeed` for later version of PHP.
