### ISSUE TITLE
1.7.15 bug with CyberPanel

### ISSUE THREAD

**Issue by mvalasis** [litespeedtech/openlitespeed#303]
Hi there,

I don't know if the issue is on OLS's side or on CyberPanel's, 
but the problem appears after upgrading from 1.7.14 to 1.7.15 all websites go down with an error "403 too many redirects"

the issue get resolved by logging in on OLS and setting External App Set UID Mode to DocRoot UID
 
I also opened the issue on CyberPanel here: https://github.com/usmannasir/cyberpanel/issues/816

**Comment by litespeedtech** [comment]
Hi, this issue should have been addressed with the latest update to 1.7.15 
For binary installation not using a repo, can do 
```
/usr/local/lsws/admin/misc/lsup.sh -v 1.7.15 
```
