### ISSUE TITLE
source code compiling headers missing error

### ISSUE THREAD

**Issue by surjit** [litespeedtech/openlitespeed#307]
../../src/http/httprespheaders.h:28:10: fatal error: lsxpack_header.h: No such file or directory
   28 | #include <lsxpack_header.h>
      |          ^~~~~~~~~~~~~~~~~~

Ubuntu 20.04 LTS
https://openlitespeed.org/packages/openlitespeed-1.7.15.src.tgz
./configure
make

**Comment by litespeedtech** [comment]
Please use build.sh
