### ISSUE TITLE
H2: HEADERS frame followed by an empty DATA frame (with END_STREAM flag set) causes issues. 

### ISSUE THREAD

**Issue by jalopezsilva** [litespeedtech/openlitespeed#312]
We ran into a server in the wild that is using Litespeed that is rejecting our requests with a ``400 Bad Request`` because of an empty ``DATA`` frame following a ``HEADERS`` frame with ``:method`` set to ``GET``. An empty ``DATA`` frame can be used to signal End Of Message (EOM) with an ``END_STREAM`` flag set. 

We have verified that removing the empty ``DATA`` frame and sending an ``END_HEADERS``, ``END_STREAM`` flag with the ``HEADERS`` frame solves the problem.

Host: kosovatoday.net
Path: /wp-content/uploads/2022/03/lput-ttt.jpg
Server: Litespeed

I'm attaching an image of the request sent by our client and the subsequent response by the Litespeed server.

Request:
![H2 Request](https://user-images.githubusercontent.com/1276443/163880199-8eb14f5e-895e-4f3a-a725-532992216842.png)

Response:
![H2 Response](https://user-images.githubusercontent.com/1276443/163880746-f489b97d-9019-479f-bf5b-88878f31630c.png)

**Comment by litespeedtech** [comment]
Hi, thanks for the bug report.
We have tried to reproduce it internally, but failed. 
Is there any easy way to reproduce it. 
The best way is to access kosovatoday.net backend server to check server debug log. Do you have contact of the admin of kosovatoday.net?
