### ISSUE TITLE
access denied for a fastcgi context

### ISSUE THREAD

**Issue by RavikumarTulugu** [litespeedtech/openlitespeed#322]
I have added a fastcgi context and an external app to handle the URI. When i access the URI , i am getting 403 , in the error logs i see below messages. after enabling debug logs i found these. 

The context is found on first lookup but it is missing on second lookup. I am not expert in code base , pasting here it might help

022-06-27 12:15:14.880424 [DEBUG] [251890] HttpVHost::bestMatch /paymenthook (len 12) return 0x2a50980, loc $DOC_ROOT/paymenthook.
2022-06-27 12:15:14.880428 [DEBUG] [251890] [223.184.79.0:45288:HTTP2-15] Find context with URI: [/paymenthook], location: [$DOC_ROOT/paymenthook].
2022-06-27 12:15:14.880432 [DEBUG] [251890] HttpVHost::bestMatch /paymenthook (len 12) return (nil), loc nil.

I pasted the same issue in forum , pasting the link to forum for cross reference. 
[https://forum.openlitespeed.org/threads/access-denied-for-fast-cgi-uri.5390/#post-12864](url)

**Comment by litespeedtech** [comment]
You need to define a FastCGI External app first, then assign the FastCGI app to the FastCGI context.

**Comment by RavikumarTulugu** [comment]
I am pasting the screenshot of both the external app and the fastcgi context configuration. The fastcgi app is started and listening on port 8000 

![image](https://user-images.githubusercontent.com/2748005/176091977-2eadf4c2-fa2a-494d-9f0c-edda11b7dd20.png)

**Comment by litespeedtech** [comment]
Figured out the problem. It is a bug related to vhost level external application configuration. Will have it fixed. 
If you move the FCGI app config to server level, it will work.

**Comment by RavikumarTulugu** [comment]
Thanks for the confirmation.
