### ISSUE TITLE
litespeed object cached connection test failed

### ISSUE THREAD

**Issue by Dark345** [litespeedtech/openlitespeed#328]
Hello please reference [this issue](https://github.com/litespeedtech/lsmcd/issues/26#issuecomment-1219856345) @ Bob (@rperper)
as stated in that reply.

I'll rechecked the settings explained in that reply, with the add of: 
-rebooted the instance (OLS & PHP)
-set the host value to /tmp/lsmcd.sock - Port 0. I used a local socket instead of a TCP socket

**Comment by rperper** [comment]
Please open a ticket as described here: https://store.litespeedtech.com/store/submitticket.php?step=2&deptid=2

**Comment by Dark345** [comment]
> Please open a ticket as described here: https://store.litespeedtech.com/store/submitticket.php?step=2&deptid=2

I'm not a customer of LS Enterprise

**Comment by qtwrk** [comment]
> > Please open a ticket as described here: https://store.litespeedtech.com/store/submitticket.php?step=2&deptid=2
> 
> I'm not a customer of LS Enterprise

that's OK,  you can still submit a ticket
