### ISSUE TITLE
Every OLS worker produces its own LSAPI instances

### ISSUE THREAD

**Issue by kopytov** [litespeedtech/openlitespeed#33]
I noticed that openlitespeed creates more lsphp instances than I configured:
- AutoStart: Yes 
- Instances: 1
- Environment: PHP_LSAPI_CHILDREN=35

I looked at src/extensions/localworker.cpp and found that every OLS worker has its own PidList and, for example, worker # 02 doesn't know anything about already started instance by worker # 01 and starts its own. This means that if you have a server with N CPU cores (and N OLS workers by default) you get N lsphp instances & N \* PHP_LSAPI_CHILDREN lsphp workers on heavy load. On small load you get a lot of excess idled instances and this increase memory consumption and reduce speed (because OLS need to start unnecessary instances & every instance's group of lsphp workers have its own opcode cache).

Even if it is not a bug, it is not useful. May be it will better to share PidList between OLS workers to get number of instances user really need.

The workaround is to set Number of Workers: 1.

**Comment by litespeedtech** [comment]
This is by design, OpenLiteSpeed uses keepalive connections to backend, make it difficult to share one group of LSPHP Process Group among multiple openlitespeed workers.  Maybe need to add the daemon mode support as with LSWS enterprise.
