### ISSUE TITLE
OLS backed server with PH8.1 installed

### ISSUE THREAD

**Issue by tymoey** [litespeedtech/openlitespeed#334]
Hello all,

I'd need some/help and advise on the existing website with OLS backed, my site was installed with OLS and WordPress, and today, I've noticed that the site has prompted for the Download file instead of the real site, i believe that it was the underlying PHP issue, but up to no vail on the investigation. 

Any advise/alternative on that would be much appreciated.

**Comment by litespeedtech** [comment]
PHP 8.1 support has been added to our repos, it should work  now.
