### ISSUE TITLE
Update Modsecurity module to 3.0.8

### ISSUE THREAD

**Issue by kam821** [litespeedtech/openlitespeed#337]
mod_security has recently received a security update/functionality extension, which e.g. coreruleset currently uses to protect against certain types of attacks:
https://github.com/SpiderLabs/ModSecurity/releases/tag/v3.0.8
https://github.com/coreruleset/coreruleset/releases/tag/v3.3.4
https://terjanq.medium.com/waf-bypasses-via-0days-d4ef1f212ec

It would be nice if mod_security could be updated.
Currently version 3.0.5 is hardcoded in openlitespeed third-party.git repo.

PS: Is the file src/modules/modsecurity-ls/dllibmodsecurity.sh obsolete?
It seems so, because it is even more outdated, has 3.0.2 version hardcoded and is not part of the openlitespeed CMake build chain.

Best regards

**Comment by litespeedtech** [comment]
mod_security has been updated to 3.0.8 in third-party repo, please compile from source.
