### ISSUE TITLE
http3 not working with chrome ols-1.7.16 localhost

### ISSUE THREAD

**Issue by maxdinatale** [litespeedtech/openlitespeed#339]
I cannot establish a connection in http3 with QUIC using Chrome with my ols server in localhost.

The first time I try to connect, Chrome uses QUIC and gets stuck at QUIC handshake, then it loads the page with http2 and all subsequent requests (refreshing the page) are loaded with http2 (https, no certificate problems). To reproduce this behavior it is necessary to go to Chrome settings and clear all browsing data. 

I tried the same request to ols with Firefox and it uses http3 and QUIC as expected, so it should be something related to Chrome.

Wireshark traces with both requests (Chrome and Firefox): [wireshark.zip](https://github.com/litespeedtech/openlitespeed/files/9839004/wireshark.zip)

Setup:

- ols-1.7.16, I enabled quic at all levels (server, listener, vhosts) and used certificate made by mkcert. 
  - vhost: Example
  - listener: https on port 443;
- mkcert v1.4.3;
- chrome 105.0.5195.102 (Official Build).

**Comment by litespeedtech** [comment]
Chrome does not work with self signed cert. Best bet is a real domain with Let's Encrypt cert.
