### ISSUE TITLE
kernel error with modsecurty in ols 1.7.16

### ISSUE THREAD

**Issue by ramippala** [litespeedtech/openlitespeed#340]
Hi,

`Nov  4 19:15:18 prod-1 kernel: [1822580.562311] traps: litespeed[24198] trap stack segment ip:7f1b12361a90 sp:7ffc97413d70 error:0 in mod_security.so[7f1b12046000+75c000]`

we faced a server downtime and received an alert related to the kernel error, after checking logs we found the above error in kernel logs

```
Computer	prod-1
count_	1
set_Facility	["kern"]
set_SyslogMessage	["[1822580.562309] show_signal: 5 callbacks suppressed"]
set_HostIP	["10.0.0.4"]
set_ProcessName	["kernel"]
set_Type	["Syslog"]
```

**Comment by ramuippala** [comment]
`Nov  4 20:13:04 prod-2 kernel: [1826100.372547] litespeed[25959]: segfault at 41 ip 00007f0905561a90 sp 00007ffddfe44e20 error 4 in mod_security.so[7f0905246000+75c000]`
