### ISSUE TITLE
No installation options on openlitespeed.org for 1.7.16.1

### ISSUE THREAD

**Issue by jordantrizz** [litespeedtech/openlitespeed#342]
There is no installation method available for Openlitespeed 1.17.16.1 on openlitespeed.org

**Comment by litespeedtech** [comment]
All new binary installations are 1.7.16.1 .

**Comment by jordantrizz** [comment]
Thanks, how do we know if the binary has successfully upgraded? Right now I'm only seeing `LiteSpeed/1.7.16 Open (BUILD built: Fri May 13 19:00:23 UTC 2022)`
