### ISSUE TITLE
compile php bug

### ISSUE THREAD

**Issue by SumiHeart** [litespeedtech/openlitespeed#343]
there is a bug when you try to compile php from ols panel,
when go to step2 will show an error and all stopped,

`$ver = 'memcache-' . BuildConfig::GetVersion(BuildConfig::MEMCACHE_VERSION8);`
[problem line](https://github.com/litespeedtech/openlitespeed/blob/master/dist/admin/html.open/lib/util/build_php/buildfunc.inc.php#L692)

MEMCACHE_VERSION8 should be MEMCACHE8_VERSION will be fixed,

thank you

**Comment by litespeedtech** [comment]
Thanks, will fix in next build.
