### ISSUE TITLE
Missing memcache module for php 8.x, for CentOS?

### ISSUE THREAD

**Issue by c4tom** [litespeedtech/openlitespeed#346]
For debian/ubuntu i found

https://rpms.litespeedtech.com/debian/pool/main/jammy/lsphp81-memcached_3.2.0-1%2Bjammy_amd64.deb

but for CentOS (but, i use Oracle Linux 8)
https://rpms.litespeedtech.com/centos/8/x86_64/RPMS/ ?

![image](https://user-images.githubusercontent.com/1284875/206724856-d8f6db2d-dcd3-429f-8da8-8e0388392601.png)

how can i add or enable memcache module in php 8.1 to make it work in wordpress lscache plugin?

**Comment by qtwrk** [comment]
php80 has Memcached module already but php81 you may need to manually compile it

**Comment by litespeedtech** [comment]
php81/php82 memcached modules are now available in https://rpms.litespeedtech.com/centos/8/update/x86_64/RPMS/ .
