### ISSUE TITLE
[request] arm 1click support

### ISSUE THREAD

**Issue by rafalohaki** [litespeedtech/openlitespeed#349]
When i was trying to install openlitespeed, i got this error:
``Sorry, currently one click installation only supports Centos(6-8), Debian(7-10) and Ubuntu(14,16,18,20).
You can download the source code and build from it.
The url of the source code is https://github.com/litespeedtech/openlitespeed/releases.``
Ubuntu 22.04.1 LTS aarch64 arm

**Comment by litespeedtech** [comment]
Yes, ARM support is on our to-do list.

**Comment by rafalohaki** [comment]
Seems like there is no problem with building on arm. Couldnt see binary in repo http://rpms.litespeedtech.com/debian/dists/jammy/
Hope it will be there soon.

**Comment by timnolte** [comment]
@rafalohaki if you are inclined to try a Docker solution I have a [working image available](https://hub.docker.com/r/ndigitals/openlitespeed), more testing that would be helpful as I work with the LiteSpeedTech team to help make arm64 support official.

**Comment by rafalohaki** [comment]
> @rafalohaki if you are inclined to try a Docker solution I have a [working image available](https://hub.docker.com/r/ndigitals/openlitespeed), more testing would be helpful as I work with the LiteSpeedTech team to help make arm64 support official.
sure, seems its working tbh.
volume binding is working, variable for user and password change would be great

**Comment by timnolte** [comment]
@rafalohaki if's you'd be so kind as to open up issues here: https://github.com/ndigitals/ols-dockerfiles/issues I'd be happy to address them.

**Comment by rafalohaki** [comment]
oke
