### ISSUE TITLE
lswsctrl stop leave an openlitespeed process alive

### ISSUE THREAD

**Issue by mingodad** [litespeedtech/openlitespeed#35]
Hello !
Doing tests with openlitespeed master under ubuntu 14.04 64bits when I call:
```
lswsctrl stop
```
The server stop reponding and almost all openlitespeed processes are removed except one, after several stop/start I have several openlitespeed processes.

I discovered it by accident when trying to update the openlitespeed binary after stopping the server and I was getting "text busy" error.

Cheers !

**Comment by litespeedtech** [comment]
You got "text busy" error is because openlitespeed is still running. In some case you can not stop it by command "lswsctrl stop", you can find the pid and kill the pid.
Thanks.

**Comment by mingodad** [comment]
I do not remember see/read anything about this on the documentation and at first I expect all openlitespeed processes to end/quit when issuing a "stop" command unless there was a "quit" command.

Cheers !

**Comment by litespeedtech** [comment]
It depends on what was served by the server by the time you stop it. 

We try to perform a graceful stop, which only stop all processes after finish serving pending requests. If a pending request takes long time to finish, the server process will linger for a while. 

You can use lsof and strace to find out what was doing by that time.
