### ISSUE TITLE
No request delivery notification has been received from LSAPI application, possible dead lock

### ISSUE THREAD

**Issue by DGINXREAL** [litespeedtech/openlitespeed#360]
Hello,

i have multiple virtual hosts on my server running. But i have only one with Wordpress. When i try to make multiple changes, the pages/request loading very long, then i get an 503 Error. Inside my logs i found this multiple times when the sites are hanging. 

`No request delivery notification has been received from LSAPI application, possible dead lock`

i tried multiple solutions on this issues pages and forum but nothing works.

**Comment by litespeedtech** [comment]
This has been addressed in the updated 1.7.19 release today. Just download the binary package again, or, run command 
```
/usr/local/lsws/admin/misc/lsup.sh -v 1.7.19
```
to apply the fix.
