### ISSUE TITLE
Compiling on macos reports errors

### ISSUE THREAD

**Issue by xpf0000** [litespeedtech/openlitespeed#364]
error:  httpsession.cpp:1140:31: error: use of undeclared identifier 'memrchr'; did you mean 'memchr'?
            p = (const char *)memrchr(pIpBegin, ',', pEnd - pIpBegin);

**Comment by litespeedtech** [comment]
MacOSX may not provide memrchr() in its libc. You may have to add code like 
https://opensource.apple.com/source/sudo/sudo-60/src/memrchr.c.auto.html

**Comment by xpf0000** [comment]
Okay. Thanks for the reply. 

I'm working on a php and web development environment management tool for macos. Currently it has both nginx and apache http servers integrated. I would also like to add the OpenLiteSpeed module. Both nginx and apache are installed via homebrew. Can OpenLiteSpeed be uploaded to homebrew? 

I see that OpenLiteSpeed provides a pre-built version for linux, can a pre-built version for macos be released later and uploaded to homebrew?

**Comment by rperper** [comment]
memrchr() has been removed from OLS starting at release 1.8.

**Comment by rperper** [comment]
We have no plans for a MacOS binary for OpenLiteSpeed at this time.  The release can be built from source.
