### ISSUE TITLE
percona the infamous one

### ISSUE THREAD

**Issue by JOduMonT** [litespeedtech/openlitespeed#366]
as far I don't use the option `--pure-percona` everything works as expected

## REPRODUCE
boot a server; in my case it's Alma 9
`wget https://raw.githubusercontent.com/litespeedtech/ols1clk/master/ols1clk.sh`
### WORK
`bash ./ols1clk.sh`

### FAIL
`bash ./ols1clk.sh --pure-percona`

## PROPOSED SOLUTION
since it seams to be; I'm the only one carring about Percona; I propose to drop this and focus on MariaDB.

**Comment by Code-Egg** [comment]
@JOduMonT 
I just launched a fresh AlamLinux 9, and `bash ./ols1clk.sh --pure-percona` works for me. What the error did you get? 


```
Congratulations! Installation finished.
End OpenLiteSpeed one click installation << << << << << << <<

Start auto testing >> >> >> >>
OK: test webAdmin page passed.
OK: test Example HTTP vhost page passed.
OK: test Example HTTPS vhost page passed.
End auto testing << << << <<
Thanks for using OpenLiteSpeed One click installation!
```

```
rpm -qa | grep percona-server
percona-server-shared-8.0.34-26.1.el9.x86_64
percona-server-client-8.0.34-26.1.el9.x86_64
percona-server-server-8.0.34-26.1.el9.x86_64
```
