### ISSUE TITLE
OLS 1.3.10 internally adds trailing slash for DHParam

### ISSUE THREAD

**Issue by kopytov** [litespeedtech/openlitespeed#37]
For example, httpd_config.xml:

    ...
    <DHParam>$SERVER_ROOT/conf/cert/dhparam.pem</DHParam>
    ...

In error_log:

    ...
    2015-05-05 14:32:06.199 [ERROR] [config:server:listener:[2a00:1178:1:43::d]:443:ssl] Path for DH Parameter file is not accessible: /usr/local/lsws/conf/cert/dhparam.pem/
    ...

I wrote a patch to fix this issue. It just adds additional variable to store destination path for DHParam.

    diff --git a/src/sslpp/sslcontext.cpp b/src/sslpp/sslcontext.cpp
    index 98ca0b7..dd6635b 100644
    --- a/src/sslpp/sslcontext.cpp
    +++ b/src/sslpp/sslcontext.cpp
    @@ -1016,6 +1016,7 @@ SSLContext *SSLContext::config(const XmlNode *pNode)
         char achKey [MAX_PATH_LEN];
         char achCAFile[MAX_PATH_LEN];
         char achCAPath[MAX_PATH_LEN];
    +    char achDHParam[MAX_PATH_LEN];
     
         const char *pCertFile;
         const char *pKeyFile;
    @@ -1103,7 +1104,7 @@ SSLContext *SSLContext::config(const XmlNode *pNode)
             const char *pDHParam = pNode->getChildValue("DHParam");
             if (pDHParam)
             {
    -            if (ConfigCtx::getCurConfigCtx()->getValidFile(achCAPath, pDHParam,
    +            if (ConfigCtx::getCurConfigCtx()->getValidFile(achDHParam, pDHParam,
                         "DH Parameter file") != 0)
                 {
                     ConfigCtx::getCurConfigCtx()->log_warn("invalid path for DH paramter: %s, ignore and use built-in DH parameter!",
    @@ -1111,7 +1112,7 @@ SSLContext *SSLContext::config(const XmlNode *pNode)
     
                     pDHParam = NULL;
                 }
    -            pDHParam = achCAPath;
    +            pDHParam = achDHParam;
             }
             pSSL->initDH(pDHParam);
         }

**Comment by litespeedtech** [comment]
Thank you so much for letting me known. Absolutely this is a bug.
I will use the below patch to fix it.

diff --git src/sslpp/sslcontext.cpp src/sslpp/sslcontext.cpp
index f78f1a6..8af73d7 100644
--- src/sslpp/sslcontext.cpp
+++ src/sslpp/sslcontext.cpp
@@ -1195,7 +1195,8 @@ SSLContext *SSLContext::config(const XmlNode *pNode)
 
                 pDHParam = NULL;
             }
-            pDHParam = achCAPath;
+            else
+                pDHParam = achCAPath;
         }
         pSSL->initDH(pDHParam);
     }
