### ISSUE TITLE
cannot run an ESM app

### ISSUE THREAD

**Issue by its-dibo** [litespeedtech/openlitespeed#371]
I'm trying to run a Nodejs app and I used the default vhost (Example), but with a very small modification
I replaced
```
const HTTP = require('http');
```
with
```
import http from 'http'
```
and it failed to start my app
I also tried adding `type: module` to package.json, and change app.js to app.mj, but also failed

and tried setting the env `NODE_OPTIONS="--loader ts-node/esm"` but also failed
also, I need to pass custom flags to node `--experimental-specifier-resolution=node` or use a custom start command such as `npm start`, but I cannot see this option anywhere

inspecting the error log I fond:
```
$ cat /usr/local/lsws/logs/stderr.log
```

```
2024-01-09 22:31:46.584 [STDERR] node:internal/modules/cjs/loader:1117
    throw new ERR_REQUIRE_ESM(filename, true);
    ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /apps/mobarmegeen-ui/server/server.mjs not supported.
Instead change the require of /apps/mobarmegeen-ui/server/server.mjs to a dynamic import() which is available in all CommonJS modules.
    at startApplication (/usr/local/lsws/fcgi-bin/lsnode.js:48:15)
    at Object.<anonymous> (/usr/local/lsws/fcgi-bin/lsnode.js:16:1) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v18.17.1
```

**Comment by litespeedtech** [comment]
I think you need to create a wrapper `server.js` startup file to import `server.mjs` . looks similar to 
https://stackoverflow.com/questions/69297449/how-can-i-correct-this-esm-error-with-phusion-passenger/71901828#71901828

**Comment by its-dibo** [comment]
it is not a solution, this doesn't allow me to pass node flags like this `node --some-flags server.mjs`
moreover, this also will make issues with other cjs modules. openlitesSpeed should enable running esm modules directly.

a simple solution is to allow customizing the scripts such as 
install: `npm install`
build: `npm run build`
start: `npm run serve`

**Comment by litespeedtech** [comment]
You can add node command parameters via `Binary Path` configuration
https://openlitespeed.org/kb/running-node-js-apps-with-openlitespeed/

You can try play with `/usr/local/lsws/fcgi-bin/lsnode.js` script in your environment see if you can make it play well with `mjs` startup file. Maybe detect by file name extension and switch to different way to load the startup file. 
Pull requests are welcome.

**Comment by its-dibo** [comment]
> You can add node command parameters via `Binary Path` configuration

Binary path is used to change the path of node which is not my case. I'm ok to use the default path but to run an esm file i.e files that ends with `.mjs`

**Comment by litespeedtech** [comment]
> > You can add node command parameters via `Binary Path` configuration
> 
> Binary path is used to change the path of node which is not my case. I'm ok to use the default path but to run an esm file i.e files that ends with `.mjs`

It is the command to start node, you can add parameters.

**Comment by litespeedtech** [comment]
.mjs startup file is supported in 1.8.0 now. 
/usr/local/lsws/admin/misc/lsup.sh -v 1.8.0
