### ISSUE TITLE
Don't support this system? CentOS Stream 8？

### ISSUE THREAD

**Issue by xkatld** [litespeedtech/openlitespeed#374]
`
[root@centos ~]# cat /etc/redhat-release
CentOS Stream release 8
`
`
--2024-02-02 15:57:27-- https://na1-node.bt.cn/install/1/openlitespeed.sh
Resolving na1-node.bt.cn (na1-node.bt.cn)... 128.1.164.196
Connecting to na1-node.bt.cn (na1-node.bt.cn)|128.1.164.196|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 24091 (24K) [application/octet-stream]
Saving to: ‘openlitespeed.sh’

0K .......... .......... ... 100% 122M=0s

2024-02-02 15:57:27 (122 MB/s) - ‘openlitespeed.sh’ saved [24091/24091]

805
Sorry, currently one click installation only supports Centos(6-8), Debian(7-10) and Ubuntu(14,16,18,20).
You can download the source code and build from it.
The url of the source code is https://github.com/litespeedtech/openlitespeed/releases.
`

**Comment by xkatld** [comment]
CentOS Stream 8 x86_64(Py3.7.9)

**Comment by rperper** [comment]
This is a known issue and we're working on it.  Between CentOS 8 and CentOS 8 Stream they changed the format of the message.  We should have this fixed in an upcoming release.

**Comment by litespeedtech** [comment]
please contact `bt.cn` support to fix their script.
