### ISSUE TITLE
Permission denied on OCSP cache in default RPM installation

### ISSUE THREAD

**Issue by kopytov** [litespeedtech/openlitespeed#38]
OLS 1.3.10 failed to save OCSP response via permissions error:

    stat("/usr/local/lsws//tmp/ocspcache/Rb0654bbe1894c320dd141a364fad649b.rsp", 0x7fff3725ed20) = -1 EACCES (Permission denied)
    stat("/usr/local/lsws//tmp/ocspcache/Rb0654bbe1894c320dd141a364fad649b.rsp.tm", 0x7fff3725cd00) = -1 EACCES (Permission denied)
    open("/usr/local/lsws//tmp/ocspcache/Rb0654bbe1894c320dd141a364fad649b.rsp.tm", O_RDWR|O_CREAT|O_TRUNC, 0600) = -1 EACCES (Permission denied)

The ocspcache directory should be owned by nobody to work properly in default installation.

Workaround:

    chown nobody:nobody /usr/local/lsws/tmp/ocspcache

**Comment by litespeedtech** [comment]
You are right. We will fix it in the next release. 
Thanks.

**Comment by litespeedtech** [comment]
It is fixed and will be in the next RPM release.
