### ISSUE TITLE
File ".rtreport" affects the useful life of an SSD - WRITE I/O

### ISSUE THREAD

**Issue by TBMSP** [litespeedtech/openlitespeed#381]
Hello!
I have been looking for how to prevent the process from writing to "/tmp/lshttpd/.rtreport" every second per thread, I have not found a way, and this represents a significant use of IO in writing to the disk, it is approximately 4k per second per thread, which is very little, but in a sufficient period of time, clearly affects the useful life of an SSD.
From what I saw, this file is for real-time statistics for the administration panel, but it is not always needed, I would say (at least for me) never.
In the panel I did not find an option to disable the process from writing ".rtreport" even if I clicked "stop" in the panel, it is possible that there is some setting between the files but for now I have not found it.
I have OpenLiteSpeed 1.7.19 on a fresh install on debian 12.

**Comment by litespeedtech** [comment]
you can mount a ramdisk at /tmp/lshttpd .

**Comment by litespeedtech** [comment]
Addressed in 1.8.2 , use /dev/shm for rtreport now.
