### ISSUE TITLE
webp replacment problem

### ISSUE THREAD

**Issue by AkramiPro** [litespeedtech/openlitespeed#382]
Hi. thank you for your great work at litespeed plugin.
As of admin i need to be able to see output of some settings with admin access.
but some options only applied for cached pages.
and i cannot see them until i logged out. 
but debugging without admin is very difficult.
like webp replacement and lazy load output.
![image](https://github.com/litespeedtech/openlitespeed/assets/54323929/bd5dd3f3-9a92-42a8-8c45-2e0078c1dc41)
i know that you cannot change the code for some good reason and logics that i know.
so i came with a new solution 
i think you can add debugging mode option that only work with admin users and special params in url
we can control which options apply in debugging mode by passing params like that:
`https://site.com/?lsp_debug=true&lsp_lazy_load=true&lsap_minify_html=false&lsp_web_replacement=true`

so we can see options output and debug easily 😊

**Comment by qtwrk** [comment]
you should post this on LSCWP repo instead of OLS repo 

and for your screenshot , you can enable private cache and set `optimize for guest only` to OFF to see the optm effect for login/admin user.

**Comment by AkramiPro** [comment]
ok thank you
