### ISSUE TITLE
SSL issue with binding multiple alias domains in vhost.conf

### ISSUE THREAD

**Issue by 0xddy** [litespeedtech/openlitespeed#383]
**../../vhost.conf**

```

vhssl  {
  keyFile                 /etc/letsencrypt/live/$VH_NAME/privkey.pem
  certFile                /etc/letsencrypt/live/$VH_NAME/fullchain.pem
  certChain               1
  enableECDHE             1
  renegProtection         1
  sslSessionCache         1
  enableSpdy              15
  enableStapling          1
  ocspRespMaxAge          86400
}

```

As shown in the code above, I want different alias domains to automatically correspond to SSL certificate files. However, I cannot find a system variable that represents the "currently accessed alias domain", like " $VH_ALIAS " so I cannot achieve this purpose using $VH_NAME or $VH_NAME incorrectly.

This is a very critical and urgent problem that needs to be resolved.

**Comment by litespeedtech** [comment]
Sorry.
It is not possible with the way vhost level SSL are configured. Each vhost can only have one SSL cert, regardless the variable, it is determined at server startup, not when the server serves the request.
