### ISSUE TITLE
How to upgrade to 1.8.0 using apt?

### ISSUE THREAD

**Issue by Lvshujun0918** [litespeedtech/openlitespeed#385]
I try to use `apt upgrade` to check for update, but I didn't get any for openlitespeed. My system version is Ubuntu 22.04.4 LTS. May you offer help? thx!

**Comment by FatGrizzly** [comment]
Stable repo doesn't have 1.8.x yet, https://rpms.litespeedtech.com/debian/pool/main/jammy/

Edge repo doesn't have jammy support at all.

https://rpms.litespeedtech.com/edge/debian/pool/main/


Wait until it comes to stable ver.

**Comment by timnolte** [comment]
Yeah, I ran into this as well when attempting to update the arm64 Docker image for OLS 1.8, they don't exist. 😕

**Comment by Lvshujun0918** [comment]
Thanks for help. It seems that I can only wait until it published.
