### ISSUE TITLE
OLS 1.3.10 Warn Failed to compress file

### ISSUE THREAD

**Issue by olegy89** [litespeedtech/openlitespeed#39]
Hello.

Here is a file:
https://raw.githubusercontent.com/almende/vis/master/dist/vis.min.js
Gzip is On. When file is requested - in server logs:
[WARN] Failed to compress file ~/vis.min.js
It's fine with other .js files.

Is there a bug?

**Comment by litespeedtech** [comment]
It is hard to say if there is some kind of setting error or this is a bug, but the WARN log is strange to me.
Can you explain it in more detail?
Also you may want to try to latest version 1.3.11.
Thanks.

**Comment by olegy89** [comment]
Yes, on 1.3.11 issue is resolved.
