### ISSUE TITLE
QUIC Connection Closure with TLS Internal Error

### ISSUE THREAD

**Issue by plumplumli** [litespeedtech/openlitespeed#390]
I use the **tquic** (Tencent Quic) Client to communicate with OpenLiteSpeed via **HTTP3**, OpenLiteSpeed decides to **close the connection during the QUIC handshake**.

**Comment by LZJ0913** [comment]
I use the **tquic** (Tencent Quic) Client to communicate with OpenLiteSpeed via **HTTP3**, OpenLiteSpeed decides to **close the connection during the QUIC handshake**.

![issue1](https://github.com/litespeedtech/openlitespeed/assets/78056809/4f09112a-26bc-4318-bbec-77a45059a374)

The specific error message of **CONNECTION_ClOSE frame** is:

![issue2](https://github.com/litespeedtech/openlitespeed/assets/78056809/8d804574-ebfa-4122-b3c5-3f072831e700)

I have tried the following **two methods** to generate and configure the **SSL Private Key & Certificate**:
The **first method** is:
```
openssl genpkey -algorithm RSA -out private_key.pem -pkeyopt rsa_keygen_bits:2048
openssl genpkey -algorithm RSA -out ca_private_key.pem -pkeyopt rsa_keygen_bits:2048
openssl req -new -key private_key.pem -out csr.pem
openssl x509 -signkey private_key.pem -in csr.pem -req -days 365 -out certificate.pem
openssl req -x509 -new -nodes -key ca_private_key.pem -days 1024 -out ca_certificate.pem
```
In this way, my SSL configuration for the Listener and Virtual Host is:
```
Private Key File = /usr/local/lsws/mylocation/private_key.pem
Certificate File = /usr/local/lsws/mylocation/certificate.pem
CA Certificate File = /usr/local/lsws/mylocation/ca_certificate.pem
```
The **second method** is:
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha256 -days 365`
In this way, my SSL configuration for the Listener and Virtual Host is:
```
Private Key File = /usr/local/lsws/mylocation/key.pem
Certificate File = /usr/local/lsws/mylocation/cert.pem
Chained Certificate = Yes
```

The **error.log(debug mode)** is:
```
2024-06-03 02:25:40.066707 [NOTICE] [25637] sendKillCmdToWatchdog: 'extappkill:26690:-3:0'.
2024-06-03 02:25:40.822138 [NOTICE] [25635] Cmd from child: [extappkill:26690:-3:0]
2024-06-03 02:25:40.822245 [INFO] [25635] Failed to get process [26690] start time, not running, skip killing.
```

I would like to know what the cause of the error is. Could you please provide some ideas or guidance on how to resolve this issue? Any help would be greatly appreciated.

**Comment by litespeedtech** [comment]
Make sure the regular TCP HTTPS works properly with the cert/key, using TLS 1.3. 
then try HTTP/3, if not work, enable OLS debug logging check the log. it is likely a TLS 1.3 handshake problem.

**Comment by litespeedtech** [comment]
Please make sure you have the certificate configured at both listener level and vhost level, otherwise, SNI wont work. it is required for HTTP3.
