### ISSUE TITLE
Memory allocated to each process does not match memSoftLimit

### ISSUE THREAD

**Issue by f-liva** [litespeedtech/openlitespeed#399]
This is the /usr/local/lsws/conf/httpd_config.conf configuration:

```
CGIRLimit  {
  maxCGIInstances         20
  minUID                  11
  minGID                  10
  priority                0
  CPUSoftLimit            10
  CPUHardLimit            50
  memSoftLimit            2047M
  memHardLimit            2048M
  procSoftLimit           400
  procHardLimit           450
}
```

By executing from PHP this directive, the memory allocated to the process exactly matches the value memSoftLimit/1000. A limit of 2GB is set in the configuration, while ulimit shows a limit of 2MB.

```
<?php

exec('ulimit -v'); // Results in 2096128 instead of 268304384
```

If I set memSoftLimit to 268304384M instead, the value returned by ulimit is 2047 MB as it should be. 
Why does OLS divide the memSoftLimit value by 1000?

This is an unexpected behavior and I think it is a bug.

**Comment by litespeedtech** [comment]
`ulimit -v` return size in KB. nothing wrong with OLS memory limit.
