### ISSUE TITLE
Add support LScache PrestaShop

### ISSUE THREAD

**Issue by eveneme** [litespeedtech/openlitespeed#400]
The LScache module doesn't work well with OpenLiteSpeed for PrestaShop, as it breaks the store's template and displays a string of numbers and letters at the top of the page.

![image](https://github.com/litespeedtech/openlitespeed/assets/85762221/3ec1fe28-4327-49ab-b09f-1bc7707dbd47)

`<esi:inline name="/module/litespeedcache/esi?s=1&amp;c=1&amp;l=1&amp;pd=%7B%22pt%22%3A%22tk%22%2C%22m%22%3A%22lsc_token%22%2C%22d%22%3A%22static%22%7D" cache-control="private,no-vary,max-age=1800" cache-tag="public:PS5ba40_PRIV,PS5ba40_signin">8a95d0efe6107b77846a3a55e4343552</esi:inline>`

**Comment by litespeedtech** [comment]
Sorry, OLS has no ESI support.
