### ISSUE TITLE
RackRunner.rb incompatible with Rails 7.2

### ISSUE THREAD

**Issue by climatebrad** [litespeedtech/openlitespeed#407]
Rails 7.2 removes a host of deprecated methods, including 
`ActiveRecord::Base.clear_all_connections!` 

See [Rails 7.2 release notes](https://github.com/rails/rails/blob/4a45f3144c680f86655a24d21a9e014f694cca74/guides/source/7_2_release_notes.md)

Could change line 136 to:

```
if defined?(ActiveRecord::Base)
  if defined?(ActiveRecord::Base.connection_pool.release_connection)
    ActiveRecord::Base.connection_pool.release_connection
  else
    ActiveRecord::Base.clear_active_connections! 
  end
end
```

**Comment by litespeedtech** [comment]
Thanks for the notification. Will apply it for next release.

**Comment by litespeedtech** [comment]
Will be in 1.8.2 .
