### ISSUE TITLE
RUBYOPT=rubygems needs to be RUBYOPT=-rrubygems

### ISSUE THREAD

**Issue by climatebrad** [litespeedtech/openlitespeed#408]
ubygems.rb alias was removed in Rubygems 3.2.3 (2020).

https://github.com/litespeedtech/openlitespeed/blob/d9610258f5c76ca204e1fd7074c23297b96a64de/src/http/httpvhost.cpp#L1681

Change `RUBYOPT=rubygems` to `RUBYOPT=-rrubygems`

See rubygems/rubygems#2393

**Comment by climatebrad** [comment]
To be clear I haven't tested this fix and am not an expert, the line may be entirely deprecated or unnecessary. but `RUBYOPT=rubygems` is definitely an error

**Comment by litespeedtech** [comment]
Thanks for the bug report. 
We have found that it causes trouble, so we just removed that environment variable in the latest code. it is not necessary.

**Comment by litespeedtech** [comment]
It will be in 1.8.2 .
