### ISSUE TITLE
CentOS 6 repository do not contain OLS 1.3.11

### ISSUE THREAD

**Issue by kopytov** [litespeedtech/openlitespeed#41]
Hello.

File [repomd.xml](http://rpms.litespeedtech.com/centos/6/x86_64/repodata/repomd.xml) in CentOS 6 x86_64 repository points to [0cc7287ae09c106b5b06a6d251ba30f6e913aafaea2f9f99798c08f6312f0d65](http://rpms.litespeedtech.com/centos/6/x86_64/repodata/0cc7287ae09c106b5b06a6d251ba30f6e913aafaea2f9f99798c08f6312f0d65-primary.xml.gz) as a primary file which was created at 27 Apr and do not contain anything about OLS 1.3.11. If you will try to install OLS as described on [your wiki](http://open.litespeedtech.com/mediawiki/index.php/Help:Repositories), you will install OLS 1.3.10 without ability to upgrade to 1.3.11 via yum update.

Please check the repository metadata.

**Comment by jacksonlst** [comment]
Fixed.

**Comment by kopytov** [comment]
Thanks!
