### ISSUE TITLE
docs: config/logs/visitorip/

### ISSUE THREAD

**Issue by epreston** [litespeedtech/openlitespeed#417]
Could you direct me where I can contribute a documentation update ?

I would like to update the following page:  

https://docs.openlitespeed.org/config/logs/visitorip/

The updates are:

- The example command line is missing: 104.24.0.0/14T 
- It includes an extra trusted IP range: 199.27.128.0/21T

References:  

https://www.cloudflare.com/en-au/ips/

**Comment by epreston** [comment]
Two more updates:  

104.16.0.0/12 removed from ips-v4
104.16.0.0/13 added to ips-v4

**Comment by lslisa** [comment]
Thanks for the report, @epreston. The listed IPs in the doc are meant to be simply an example to show how it is done, not an exhaustive list of Cloudflare IPs. There is a link right above the list that will get you Cloudflare's current IP list.

I will update the documentation to be more clear about that.

**Comment by epreston** [comment]
@lslisa do you know the repo and location to submit a PR to ?  

Just want to update the values, already clear enough that it's an example, not looking for the reference since I've included it above. 

My main issue is including an old range that cloudflare now uses for a different purpose in the trusted set.

**Comment by lclarke522** [comment]
The repo isn't public. I'll make those changes. Or maybe I will change the example to use nonsense numbers (like `123.45.67.89/00`) I plan to look at it later today. Thank you for the additional context.

**Comment by epreston** [comment]
@litespeedtech can I get someone else to help with this ?

**Comment by lslisa** [comment]
@epreston I am the director of content at LiteSpeed, and this includes Documentation. What additional help did you require?

**Comment by lslisa** [comment]
@epreston I've updated the doc. The CF IPs have been replaced with example IPs. Thank you for bringing this to our attention. Let me know if you have any further issues with that (or other) documentation.

**Comment by epreston** [comment]
@lslisa No thanks. Given the results I'll go through sales or customer support if I notice any issues.
