### ISSUE TITLE
Support for ECDSA and RSA Hybrid

### ISSUE THREAD

**Issue by firegore** [litespeedtech/openlitespeed#42]
Hello, maybe im wrong here, but i didnt find an appropiate Way to ask, does OpenLS support Hybrid mode for ECDSA and RSA, like Apache do?

 (2 different Certs for the same Vhost, Server chooses between RSA and ECDSA based on Cipher Suits that it gets from the Client)

Best Regards

**Comment by litespeedtech** [comment]
This function has been added to upcoming 1.4.12 release.

**Comment by centminmod** [comment]
Wow that's great news :)
