### ISSUE TITLE
FreeBSD Compatibility: Service Name Change, Arch Command Update, and Symlink Creation for /dev/shm

### ISSUE THREAD

**Issue by dev-zhandos** [litespeedtech/openlitespeed#423]
### Issue Summary
Several changes are required to improve compatibility with FreeBSD. These changes are addressed in Pull Request #422 and include renaming the RC service, updating the command used to get the machine architecture, and creating a symlink for /dev/shm. Each change is necessary to ensure smoother integration and functionality on FreeBSD systems.

**These updates have been tested on Debian 12, Rocky Linux 9, and FreeBSD 14.1 to ensure cross-platform functionality.**

### Changes

1. **Rename RC Service to `lsws`:**
   - The current service name `lsws.sh` is not compatible with FreeBSD’s `sysrc` command, as `sysrc` does not support values with dots (`.`). This causes the following error:
     ```
     sysrc: lsws.sh_enable: name contains characters not allowed in shell
     ```
   - To resolve this, the RC service should be renamed from `lsws.sh` to `lsws`, allowing `sysrc lsws_enable="YES"` to be used without errors.
https://github.com/litespeedtech/openlitespeed/blob/1b5825fa728aae4c975084e0c1f7e0ce241ba45a/dist/admin/misc/rc-inst.sh#L41-L42
https://github.com/litespeedtech/openlitespeed/blob/1b5825fa728aae4c975084e0c1f7e0ce241ba45a/dist/admin/misc/rc-uninst.sh#L19
2. **Replace `arch` with `uname -m`:**
   - On FreeBSD, the `arch` command is not available by default. The equivalent command to get the machine's architecture is `uname -m`. Replacing `arch` with `uname -m` ensures that scripts relying on architecture detection work properly on FreeBSD.
https://github.com/litespeedtech/openlitespeed/blob/1b5825fa728aae4c975084e0c1f7e0ce241ba45a/dist/install.sh#L7
https://github.com/litespeedtech/openlitespeed/blob/1b5825fa728aae4c975084e0c1f7e0ce241ba45a/dist/install.sh#L53

3. **Create Symlink for `/dev/shm`:**
   - FreeBSD does not have a `/dev/shm` directory by default. To ensure compatibility with software that expects `/dev/shm`, a symlink should be created by linking `/tmp/shm` to `/dev/shm`:
     ```bash
     ln -s /tmp/shm /dev/shm
     ```
https://github.com/litespeedtech/openlitespeed/blob/1b5825fa728aae4c975084e0c1f7e0ce241ba45a/build.sh#L511-L518

### Environment

- **Operating System:** FreeBSD 14.1
- **OpenLiteSpeed Version:** Latest (`v1.8.2` tag)

### Additional Information
These changes ensure compatibility with FreeBSD and allow proper service management, architecture detection, and shared memory handling. Without these changes, users may encounter issues related to service management (`sysrc` errors), architecture detection (missing `arch` command), and software compatibility (missing `/dev/shm`).

**Comment by litespeedtech** [comment]
Thanks!
