### ISSUE TITLE
503 error

### ISSUE THREAD

**Issue by olegy89** [litespeedtech/openlitespeed#43]
Hello.

OLS 1.3.12

root     11541          S     openlitespeed (lshttpd - main)
root     11542          S     \_ openlitespeed (lscgid)
user   11544         SN     |   \_ lsphp
user   11545         SN     |   \_ lsphp
nobody   11543       S     \_ openlitespeed (lshttpd - #01)

When 503 error occurs 'lshttpd' process under user 'nobody' tries to kill lsphp process and get:
     getppid()                 = 11541
     kill(11544, SIG_0)        = -1 EPERM (Operation not permitted)
     kill(11545, SIG_0)        = -1 EPERM (Operation not permitted)

and so it goes until the lsws is restarted manually.

I suppose it has to do 'lscgid' under 'root' user? It's a bug?

**Comment by litespeedtech** [comment]
You are right. This killing issue is a bug and will be fixed in the future.
But the 503 error should be something wrong in the configuration, and you probably can find it in the error log.
Thanks for your feedback.

**Comment by olegy89** [comment]
Thank you, for reply.
The last messages in error log after getting 503 is notice:
No request delivery notification has been received from LSAPI application, possible dead lock.

How to know, is there issue or miss configuration?
I've only found about it that "This error indicates your PHP is crashing." - but should this lead to the collapse of the web server with 503 error?
