### ISSUE TITLE
NSPOSIXErrorDomain on Safari 9.0

### ISSUE THREAD

**Issue by Maxime-BHA** [litespeedtech/openlitespeed#46]
Hello,

Litespeed is configured with SSL through HTTP/2, SPDY/2 and SPDY/3, but everytime I do a POST request, Safari shuts down the request with NSPOSIXErrorDomain, the cipher is starting with "ECDHE-RSA-AES128-GCM-SHA256".

TLS 1.1 / 1.2 are used, tried enabling TLS 1.0 and SSLv3 but no success right here.

Best regards.

**Comment by litespeedtech** [comment]
Which version of openlitespeed are you using?
Do you have a simple script that can be used to reproduce this problem?

**Comment by Maxime-BHA** [comment]
Using 1.4.11, can access my websites through SSL but when I'm processing data through POST request doesn't work and output the NSPOSIXErrorDomain.

Can't give you a simple script to reproduce the problem, but here are all the details :

* SSL is working through GET request and everything is working fine, sometimes, Safari throw an error and say that he couldn't establish a secured connection to the server but when reloading, it does work.
* POST requests doesn't work and shuts down the request with NSPOSIXErrorDomain, while there is URL parameters
* SSL is well configured and verified by Comodo tools, the ca-bundle has been set and certificate is valid
* This problem only occurs on Safari 8 and 9 through Maverick 10.9 ,Yosemite 10.10 and El Capitan 10.11 Developper Beta 8, it does not occurs on Chrome (so close to the Litespeed 5.0 build 1/2/3 problem
* Disable HTTP/2 or SPDY/3 or SPDY/2 consecutively doesn't impact or solve the problem, changing to TLS 1.2 / 1.1 / 1.0 or SSLv3 doesn't solve the problem (using only SSLv3 block everything as it is obsolete and any TLS doesn't change anything)

**Comment by litespeedtech** [comment]
This bug should have been fixed, please try below patch:

diff --git src/http/httpsession.cpp src/http/httpsession.cpp
index e85b394..afdbba9 100644
--- src/http/httpsession.cpp
+++ src/http/httpsession.cpp
@@ -373,7 +373,7 @@ void HttpSession::setupChunkIS()
     assert(m_pChunkIS == NULL);
     {
         m_pChunkIS = HttpGlobals::getResManager()->getChunkInputStream();
-        m_pChunkIS->setStream(getStream());
+        m_pChunkIS->setStream(this);
         m_pChunkIS->open();
     }
 }
diff --git src/http/httpsession.h src/http/httpsession.h
index 6cf1e9c..22e46a3 100644
--- src/http/httpsession.h
+++ src/http/httpsession.h
@@ -73,7 +73,8 @@ enum  HttpSessionState
 
 
 
-class HttpSession : public LsiSession, public HioHandler
+
+class HttpSession : public LsiSession, public InputStream, public HioHandler
 {
     HttpReq               m_request;
     HttpResp              m_response;

**Comment by Maxime-BHA** [comment]
`error: ‘HttpGlobals’ has not been declared`

**Comment by litespeedtech** [comment]
Sorry, that's for 1.3 branch. 
Actually, 1.4.11 includes that fix, maybe it is something else, we need investigate more . 

So, this problem even happen to plain http connection? not likely related to SPDY or HTTP/2.

**Comment by Maxime-BHA** [comment]
@litespeedtech only occurs on HTTPS, doesn't happen in plain HTTP connection.

It doesn't seems to affect GET requests but it behave like this on POST / FORM POST requests.

**Comment by litespeedtech** [comment]
Please turn on full debug logging, reproduce the problem, then send error.log to bug@litespeed...

**Comment by Maxime-BHA** [comment]
@litespeedtech https://gist.githubusercontent.com/Maxime-BHA/adc4bfd1631ee7cbfe5c/raw/642bdc5095c7944dd9beb999f9de356de8d5298c/error.log :smile:

**Comment by Maxime-BHA** [comment]
@litespeedtech also there is an exact moment when the connection is shutdown : https://gist.github.com/Maxime-BHA/f211d47981bc9829142d

**Comment by litespeedtech** [comment]
Which browser are you testing? the one from El Capitan 10.11, earlier version does not support HTTP/2 as I know.

The log shows the response has been successfully processed, what follows that in the log, for that connection 213.44.104.118:60210? did the connection go away immediately after that?

**Comment by Maxime-BHA** [comment]
@litespeedtech Actually on El Capitan can't test now on Yosemite but it does also occurs on SPDY/2 and SPDY/3, but however El Capitan does use Safari 9 and Safari 9 is bassicly supporting HTTP2 see [here](http://caniuse.com/#feat=http2)

I'll do another log with the full stack

**Comment by Maxime-BHA** [comment]
@litespeedtech https://gist.github.com/Maxime-BHA/8ac81f485a00b26b7cc1

**Comment by litespeedtech** [comment]
The log shows a few crashes. just search for "AutoRestarter", however, there is no core dump created. 
We need to make it dump the core file. then we can find out what causing it. 

If you server is using abrtd, you may need to stop it and restore /proc/sys/kernel/core_pattern to default core.%p

**Comment by Maxime-BHA** [comment]
@litespeedtech These AutoRestarter seems not related to the problem.

Seems to be a HTTP/2 related problem through Safari/OLSWS, just reconfigured Litespeed and the problem is still there but when I force SPDY on Safari, there is no problem.

**Comment by Maxime-BHA** [comment]
@litespeedtech Reinstalled OLSWS and reconfigured, the problem seems to have disappeared..

I'll close this for the moment, please remove my IPs.

**Comment by litespeedtech** [comment]
ip removed.
