### ISSUE TITLE
compiling on smartos fails 

### ISSUE THREAD

**Issue by j-trash** [litespeedtech/openlitespeed#49]
building on smartos fails somewhere at gsendfile, i assume this affects other illumos based distributions as well

[litespeed.txt](https://github.com/litespeedtech/openlitespeed/files/163869/litespeed.txt)

**Comment by litespeedtech** [comment]
Thanks for let me known.
I will fix these compiling issue to the next release.

**Comment by j-trash** [comment]
just wanted to ask if theres probably already a patch/fix avail?

**Comment by litespeedtech** [comment]
Please try patch
diff --git src/util/gsendfile.h src/util/gsendfile.h
index a2ef87a..bd28d66 100644
--- src/util/gsendfile.h
+++ src/util/gsendfile.h
@@ -72,7 +72,7 @@ static inline ssize_t gsendfile(int fdOut, int fdIn, off_t *off,
     vec[n].sfv_len  = size;
     ++n;
 
-    off_t written;
+    size_t written;
     ssize_t ret = ::sendfilev(fdOut, vec, n, &written);
     if ((!ret) || (errno == EAGAIN))
         ret = written;

**Comment by litespeedtech** [comment]
The fix will be in the next release.
Thanks.
