### ISSUE TITLE
please report pagespeed module version used with each OLS release

### ISSUE THREAD

**Issue by centminmod** [litespeedtech/openlitespeed#51]
In light of security vulnerabilities that pagepseed sometimes get, it's important to keep it up to date. Would be useful if OLS releases always reported the pagespeed module version it is accompanied with.

one way i can find it :)

```
echo "$(/usr/local/lsws/bin/openlitespeed --version) with modpagespeed $(strings /usr/local/lsws/modules/modpagespeed.so | awk -F "/" '/\/home\/buildbot\/build\// {print $5}' | uniq)"
LiteSpeed/1.4.22 Open with modpagespeed 1.11.33.2
```

**Comment by litespeedtech** [comment]
Yes. We will add this feature in the next release 1.4.24.
Thanks.
David
