### ISSUE TITLE
redis.so: undefined symbol: igbinary_serialize in Unknown on line 0

### ISSUE THREAD

**Issue by centminmod** [litespeedtech/openlitespeed#52]
Trying your ols1clk.sh install got errors with php pecl redis, igbinary and memcached https://github.com/litespeedtech/ols1clk/issues/5#issuecomment-239507044

on CentOS 7.2 64bit with forked copy of ols1clk.sh https://github.com/centminmod/ols1clk/tree/centminmod but shouldn't matter as using default lsphp yum packages

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/lsws/lsphp56/lib64/php/modules/redis.so' - /usr/local/lsws/lsphp56/lib64/php/modules/redis.so: undefined symbol: igbinary_serialize in Unknown on line 0
PHP 5.6.24 (cli) (built: Jul 29 2016 15:22:18) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by litespeedtech** [comment]
We tested our latest rpm, looks fine. 
If problem still exists, please let us know.

**Comment by wmh** [comment]
try to change the priority of loading extension:
```
20-igbinary.ini
30-redis.ini
```
