### ISSUE TITLE
Wrong checking for download command (wget/curl/fetch)

### ISSUE THREAD

**Issue by petk** [litespeedtech/openlitespeed#55]
If system doesn't have wget installed PHP gets always build probably because there is wrong checking for wget in `install.sh`:
https://github.com/litespeedtech/openlitespeed/blob/master/dist/install.sh#L9
(this doesn't set download command to curl, for example)

I think checking for wget/curl/fetch should be like this instead:
https://github.com/litespeedtech/openlitespeed/blob/master/dist/admin/misc/build_admin_php.sh#L19

**Comment by litespeedtech** [comment]
Yes, we did update that code base on your request and your changes on 4/4/2017.
It will be in the next release.
Thank you.
