### ISSUE TITLE
Configure warning unknown --is-lightweight option, missing script is too old or missing

### ISSUE THREAD

**Issue by petk** [litespeedtech/openlitespeed#72]
With OpenLiteSpeed 1.4.26, the `./configure` outputs the following warning at the beginning:

```
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
/build/main/openlitespeed/src/openlitespeed-1.4.26/missing: Unknown '--is-lightweight' option
Try '/build/main/openlitespeed/src/openlitespeed-1.4.26/missing --help' for more information
configure: WARNING: 'missing' script is too old or missing
checking for a thread-safe mkdir -p... ./install-sh -c -d
```

The current `missing` shell script in the OpenLiteSpeed root folder is version `2012-01-06.18` which, from my testing, could be easily upgraded to the more recent version of `2013-10-28.13`. It can be found on some systems in `/usr/share/automake-1.15/missing` or in `/usr/share/libtool/build-aux/missing`.

**Comment by litespeedtech** [comment]
Fixed. Thanks.
