### ISSUE TITLE
Litespeed-repo and OpenLitespped do not support Oracle Enterprise Linux 7

### ISSUE THREAD

**Issue by ivmm** [litespeedtech/openlitespeed#76]
Oracle Enterprise Linux is RHEL re-compiled version, and RHEL, CentOS perfect compatibility. Compared to CentOS updates faster.

But the Litespeed-repo and OpenLitespped binary packages are not supported on Oracle Enterprise Linux.

```bash
Retrieving http://rpms.litespeedtech.com/centos/litespeed-repo-1.1-1.el7.noarch.rpm
Error: Failed dependencies:
Centos-release> = 5 is needed by litespeed-repo-1.1-1.el7.centos.noarch
```

Hope the OLS team can increase support for Oracle Enterprise Linux, which does not require a lot of work or add a repo to maintain.

**Comment by jacksonlst** [comment]
If it is similar to centos7, you can download the repo file directly and tweak it when needed. 
 http://rpms.litespeedtech.com/centos/litespeed.repo

**Comment by ivmm** [comment]
@jacksonlst Using the --force command can also solve the problem, but still hope that the litespeed-repo next update could support for Oracle Enterprise Linux.

**Comment by litespeedtech** [comment]
If in the future you will have the same issue, please just re-create an issue.
This too old issue will be closed now.
Thanks.
David
