### ISSUE TITLE
ClientInfo->Access reset when accessing already existing cache entry

### ISSUE THREAD

**Issue by LoadLow** [litespeedtech/openlitespeed#80]
Hi,

I was stress-testing OpenLitespeed and I realized that blocked IPs are not kept after new requests.
In this case I reviewed the code, and I saw that ClientInfo->Access is always reset to `AC_ALLOW` when accessing the existing client cache entry.

Here is the issue, when ClientInfo->Access is set to `AC_BLOCK` by the AntiDoS system, the reset is happening here :
https://github.com/litespeedtech/openlitespeed/blob/master/src/http/clientcache.cpp#L460

```C++

        pInfo = iter.second();

        //always reset existing cache entry to AC_ALLOW
        if (AccessControl::getAccessCtrl())
            pInfo->setAccess(AccessControl::getAccessCtrl()->hasAccess(pPeer));
        else
            pInfo->setAccess(AC_ALLOW); 

```

Bests regards,
LoadLow.

**Comment by litespeedtech** [comment]
Hi LoadLow,

Please just remove the 4 lines you mentioned and try again.


    else
    {
        pInfo = iter.second();
        // pShmClient = pInfo->getShmClientInfo();

-        if (AccessControl::getAccessCtrl())
-            pInfo->setAccess(AccessControl::getAccessCtrl()->hasAccess(pPeer));
-        else
-            pInfo->setAccess(AC_ALLOW);
    }
    pInfo->hit(DateTime::s_curTime);
    return pInfo;

Thanks.
David

**Comment by LoadLow** [comment]
Yes, of course it works. 
I found that you started an implementation of a client cache pool shared with every child process with IPC, will it be continued?

LLow.

**Comment by litespeedtech** [comment]
yes. of course.
