### ISSUE TITLE
OpenLiteSpeed can be built along with OpenSSL 1.0.2 only. No luck with OpenSSL 1.1.0, LibreSSL or BoringSSL.

### ISSUE THREAD

**Issue by LQ2-apostrophe** [litespeedtech/openlitespeed#83]
My server is an EC2 instance running Ubuntu 16.04 LTS. It was using OpenSSL 1.0.2g and I have installed OLS 1.4.27 from source. Then I see the OLS is using OpenSSL 1.0.2m-dev (from Server Error Log in OLS admin page).

I have upgraded OpenSSL to 1.1.0f and reinstall OpenLiteSpeed based on your guide written [here](http://open.litespeedtech.com/mediawiki/index.php/Help:Install:OpenLiteSpeed_with_HTTP2_Installation_Notes).

Here are terminal commands I have used.
```sh
# OpenSSL
./config --prefix=/usr/local --openssldir=/usr/local/openssl
make
make install
# OpenLiteSpeed
./configure --with-openssl=/usr/local
make
make install
```

After that, OLS is still using OpenSSL 1.0.2m-dev. Is there any problem in my steps?

What I'm trying to accomplish is applying cipher CHACHA20-POLY1305 to SSL connection between my server and site visitors. I've already got a SHA256-RSA certficate (with key length of 2048 bits) from Let's Encrypt. I'm copying the cipher suite settings from [this page](https://wiki.mozilla.org/Security/Server_Side_TLS) as they follow the syntax mentioned in OLS admin panel.

**Comment by LQ2-apostrophe** [comment]
I have tried re-extracting OLS source code and build again. I have found that `configure` always download the last OpenSSL 1.0.2 source code into `ssl` subfolder and compile it along. So every time I need to reinstall OLS to use another version of OpenSSL, I have to remove `ssl` subfolder.

OpenSSL 1.0.2 does not support ChaCha20-Poly1305. And that download operation is in the file `dlossl.sh`.

So, I have tried extracting the source code of OpenSSL 1.1.0 into that `ssl` subfolder. During OLS compilation with `make`, I have seen some errors in OLS source code.

My conclusion: There has to be much more work for OLS to be compatible with OpenSSL 1.1.0.

Also, the checking operation in the file `dlossl.sh` does not apply to LibreSSL, as in its source code does not have any file named `libcrypto.a`.

**Comment by LQ2-apostrophe** [comment]
I've tried compiling OLS with BoringSSL as the last resort. No success. Here are the commands I used.

```sh
# Already in home directory: /home/ubuntu/
wget http://open.litespeedtech.com/packages/openlitespeed-1.4.28.tgz # Download OLS source code
tar -xvzf openlitespeed-1.4.28.tgz # Extract OLS. Creates directory named openlitespeed-1.4.28
git clone https://boringssl.googlesource.com/boringssl # Download BoringSSL. Creates directory named boringssl

# BoringSSL
cd boringssl # Enter BoringSSL directory
mkdir build
cd build
cmake .. # Prepare BoringSSL for compilation
make # Compiling/building BoringSSL. Success!

cd # Return to home directory

# OpenLiteSpeed
cd openlitespeed-1.4.28 # Enter OLS
./configure --with-bssl=/home/ubuntu/boringssl
make # Error in this step!
```

The error I've got:
```
ntwkiolink.cpp:54:34: fatal error: openssl/internal.h: No such file or directory
compilation terminated.
```

I've tried with the latest build of BoringSSL first, then the build 3112 (May 25) of it. I always get the same error.

**Comment by darkspadez** [comment]
Can you try applying the following?

```patch
diff --git a/configure b/configure
index 7e3635b..0f8ab6c 100755
--- a/configure
+++ b/configure
@@ -16033,7 +16033,9 @@ _ACEOF
 
     CPPFLAGS=" -I../../ssl/include $CPPFLAGS -I../../src -I../../include -I/usr/local/include -I/usr/local -I/usr -I/usr/pkg -DUSE_BORINGSSL=1 "
     if test "$OPENLSWS_BSSL" = yes ; then
-        echo "Will use exist BoringSSL files in $srcdir/ssl/."
+        echo "Will build stable BoringSSL libraries for you, this may take several minutes ..."
+        OSSL=`. $srcdir/dlossl.sh use_bssl`
+        echo "Will now use BoringSSL files located in $srcdir/ssl/."
     else
         OSSL=`. $srcdir/dlossl.sh use_bssl "$OPENLSWS_BSSL"`
         echo "BoringSSL files copied to $srcdir/ssl/ from $OPENLSWS_BSSL."
diff --git a/configure.ac b/configure.ac
index 9046486..9143414 100644
--- a/configure.ac
+++ b/configure.ac
@@ -260,7 +260,9 @@ else
     AC_DEFINE_UNQUOTED([USE_BORINGSSL], [1], [Defined to use BoringSSL instead of OpenSSL])
     CPPFLAGS=" -I../../ssl/include $CPPFLAGS -I../../src -I../../include -I/usr/local/include -I/usr/local -I/usr -I/usr/pkg -DUSE_BORINGSSL=1 "
     if test "$OPENLSWS_BSSL" = yes ; then
-        echo "Will use exist BoringSSL files in $srcdir/ssl/."
+       echo "Will now build stable BoringSSL libraries for you, this may take several minutes ..."
+       OSSL=`. $srcdir/dlossl.sh use_bssl`
+        echo "Will now use BoringSSL files located in $srcdir/ssl/."
     else
         OSSL=`. $srcdir/dlossl.sh use_bssl "$OPENLSWS_BSSL"`
         echo "BoringSSL files copied to $srcdir/ssl/ from $OPENLSWS_BSSL."
diff --git a/dlossl.sh b/dlossl.sh
index d01288a..e9228d2 100755
--- a/dlossl.sh
+++ b/dlossl.sh
@@ -4,6 +4,8 @@
 # Use your pre-built boringSSL
 #! /bin/sh
 
+BSSL_VERSION=96e744c176328b51239df6e48a8a590e4949e6c8
+
 if [ "x$1" = "xuse_bssl" ] ; then 
     if [ "x$2" != "x" ] ; then 
         mkdir ssl
@@ -11,6 +13,30 @@ if [ "x$1" = "xuse_bssl" ] ; then
         cp $2/build/crypto/libcrypto.a     ssl/
         cp $2/build/decrepit/libdecrepit.a ssl/
         cp -r $2/include/                  ssl/
+       cp $2/ssl/internal.h               ssl/include/openssl/
+    else
+       cd `dirname "$0"`
+       if [ -d boringssl ] ; then
+           rm -rf boringssl
+       fi
+       git clone -b master --single-branch https://boringssl.googlesource.com/boringssl boringssl
+       cd boringssl
+       git checkout $BSSL_VERSION
+       mkdir build
+       cd build
+       cmake ..
+       make
+       cd ../../
+       if [ -d "ssl" ] ; then
+           rm -rf ssl/*
+       else
+           mkdir ssl
+       fi
+       cp boringssl/build/ssl/libssl.a ssl/
+       cp boringssl/build/crypto/libcrypto.a ssl/
+       cp boringssl/build/decrepit/libdecrepit.a ssl/
+       cp -r boringssl/include/ ssl/
+       cp boringssl/ssl/internal.h ssl/include/openssl/
     fi
     
     if [ ! -f ssl/libcrypto.a ] ; then
```

Once it is applied just try: `./configure --with-bssl=yes`

**Comment by LQ2-apostrophe** [comment]
I have edited the files based on your solution above. Now `dlossl` script would re-download BoringSSL everytime I run `configure`, which is great for upgrading BoringSSL used by OpenLiteSpeed.

Then I've found that I have to run `autoreconf` to update related files, then I can run `./configure`, `make` and then `make install` without fatal errrors. In the end, I have successfully installed OLS with BoringSSL. What a steep learning curve!

Thank you so much.

Now I have to deal with the following problems:

- Double HSTS headers: One header is set in virtual host configuration, the other one is put by LiteSpeed Cache plugin by accident.
- The following random error: `[moddecompress+++] compressbuf in 0, inflate/deflate return -5` with source IP from outside.

I'm digging in those issues and I'll open another thread then.

**Comment by LQ2-apostrophe** [comment]
BoringSSL patch is not needed anymore. I have posted a manual installation with BoringSSL [here](https://github.com/LQ2-apostrophe/openlitespeed-edgy/wiki/Installing-with-BoringSSL). Tested up to commit `0e4a448ab8aa66a38593f68d19fa0a2e340833e4` of BoringSSL.

I am currently working on compatibility with latest fixes of BoringSSL.
