### ISSUE TITLE
Module mod_security on Ubuntu 16.04: yajl_alloc undefined

### ISSUE THREAD

**Issue by LQ2-apostrophe** [litespeedtech/openlitespeed#88]
My server is running Ubuntu 16.04 (Xenial).

I have followed [your instructions to build ModSecurity module](http://open.litespeedtech.com/mediawiki/index.php/Modules:ModSecurity-Installation). It is built successfully, file name is `mod_security.so`.

I have only tested if it is working by writing the following lines in `httpd_config.conf`:
```
module mod_security {
modsecurity on
}
```

The result is, I cannot see my page anymore (the server unexpectedly closed the connection). I have found the following line in `/usr/local/lsws/logs/stderr.log`:
```
openlitespeed (lshttpd - #01): symbol lookup error: /usr/local/lsws//modules/mod_security.so: undefined symbol: yajl_alloc
```

Do I have to rebuild ModSecurity using an earlier commit of libModSecurity 3?

**P.S.:** Please remember [the problem with BoringSSL](https://github.com/litespeedtech/openlitespeed/issues/83) also had to be solved by using an earlier commit of BoringSSL.

**Comment by darkspadez** [comment]
What is the output of the following?
`dpkg -l | grep 'yajl'`

**Comment by Radnevec** [comment]
Hello,

Change the line:

modsecurity on

to:

mod_security on

and restart OLS.

**Comment by LQ2-apostrophe** [comment]
@darkspadez The output is
```
ii  libyajl-dev:amd64                2.1.0-2                                    amd64        Yet Another JSON Library - development files
ii  libyajl2:amd64                   2.1.0-2                                    amd64        Yet Another JSON Library
ii  libyajl2-dbg:amd64               2.1.0-2                                    amd64        Yet Another JSON Library - debugging symbols
```

@Radnevec Your configuration just works...
I have checked the instructions again, and all related syntaxes are updated. I'll try them again.

**Comment by Radnevec** [comment]
The wiki has been update yes and glad that now its working.

**Comment by LQ2-apostrophe** [comment]
I have just tried update configuration syntax, and now ModSecurity module works. Topic closed.
