### ISSUE TITLE
error: 'SSL_CTX_set_cert_cb' was not declared in this scope

### ISSUE THREAD

**Issue by slawek-mazur** [litespeedtech/openlitespeed#89]
./configure
make && make install

sslcontext.cpp: In member function 'int SslContext::initSNI(void*)':
sslcontext.cpp:625:71: error: 'SSL_CTX_set_cert_cb' was not declared in this scope
     SSL_CTX_set_cert_cb(m_pCtx, SslConnection_ssl_servername_cb, param);
                                                                       ^
make[3]: *** [sslcontext.o] Error 1
make[3]: Leaving directory `/root/openlitespeed-1.5.0/src/sslpp'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/root/openlitespeed-1.5.0/src'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/root/openlitespeed-1.5.0/src'
make: *** [all-recursive] Error 1

this happens for both 1.4.29 and 1.5.0rc1

**Comment by litespeedtech** [comment]
You need OpenSSL 1.0.2+ , or boringSSL.

**Comment by slawek-mazur** [comment]
Yep that was openssl version. 

In file included from ntwkiolink.cpp:32:0:
ntwkiolink.cpp: In static member function 'static int NtwkIOLink::close_(NtwkIOLink*)':
../../src/log4cxx/logger.h:81:74: warning: format '%zd' expects argument of type 'signed size_t', but argument 5 has type 'int' [-Wformat=]
             log4cxx::Logger::s_log( log4cxx::Level::DBG_LESS, __VA_ARGS__); \
                                                                          ^
ntwkiolink.cpp:811:13: note: in expansion of macro 'LS_DBG_L'
             LS_DBG_L(pThis, "Available Connections: %d, concurrent conn: %zd.",
             ^
ntwkiolink.cpp: In member function 'void NtwkIOLink::handle_acceptSSL_EIO_Err()':
ntwkiolink.cpp:1543:28: error: invalid use of incomplete type 'SSL {aka struct ssl_st}'
     length = m_ssl.getSSL()->packet_length;
                            ^
In file included from ntwkiolink.h:26:0,
                 from ntwkiolink.cpp:18:
../../src/sslpp/sslconnection.h:26:16: error: forward declaration of 'SSL {aka struct ssl_st}'
 typedef struct ssl_st SSL;
                ^
ntwkiolink.cpp:1544:31: error: invalid use of incomplete type 'SSL {aka struct ssl_st}'
     p = (char *)m_ssl.getSSL()->packet;
                               ^
In file included from ntwkiolink.h:26:0,
                 from ntwkiolink.cpp:18:
../../src/sslpp/sslconnection.h:26:16: error: forward declaration of 'SSL {aka struct ssl_st}'
 typedef struct ssl_st SSL;
                ^
ntwkiolink.cpp:1571:34: warning: ignoring return value of 'ssize_t writev(int, const iovec*, int)', declared with attribute warn_unused_result [-Wunused-result]
         ::writev(getfd(), iov, 4);
                                  ^
ntwkiolink.cpp:1578:63: warning: ignoring return value of 'ssize_t write(int, const void*, size_t)', declared with attribute warn_unused_result [-Wunused-result]
         ::write(getfd(), s_errUseSSL, sizeof(s_errUseSSL) - 1);

**Comment by darkspadez** [comment]
What OS? And do you have the specific OpenSSL or BoringSSL version you are using?

**Comment by slawek-mazur** [comment]
Ubuntu 16.04.3 LTS, openssl-1.1.0 installed from sources. I run this in docker

**Comment by litespeedtech** [comment]
Can you just install latest openssl 1.0.2? 1.1.0 has bigger internal changes.

**Comment by slawek-mazur** [comment]
![screenshot from 2018-02-10 13-11-56](https://user-images.githubusercontent.com/9823973/36062012-024b0164-0e64-11e8-8856-baf7cd093061.png)

**Comment by darkspadez** [comment]
Is it possible to get the output of the configure command? I have not been able to successfully reproduce this issue on 16.04. Trying to see if something is configured differently.

**Comment by litespeedtech** [comment]
The compile error is due to OpenSSL 1.0.1 . 
OpenSSL 1.0.1 is EOL already, and you need to 1.0.2 for HTTP/2 as well. so, just install OpenSSL 1.0.2 package, it should be readily available in 16.04.

**Comment by darkspadez** [comment]
For your configure command can you try `./configure --with-openssl=/path/openssl`
Seems it is not picking up the `1.0.2n` that you compiled.

**Comment by slawek-mazur** [comment]
root@c718110fcaea:~/openlitespeed-1.4.30# ./configure --with-openssl=/root/openssl-1.0.2n > configure_out.log
./dlossl.sh: line 41: -k: command not found
tar: ossl.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat 'openssl-OpenSSL_1_0_2-stable': No such file or directory
rm: cannot remove 'ossl.tar.gz': No such file or directory
./dlossl.sh: line 46: cd: ssl: No such file or directory
sed: can't read ssl/s3_pkt.c: No such file or directory
./dlossl.sh: line 48: ./config: No such file or directory
make: *** No rule to make target `depend'.  Stop.
sslcontext.cpp: In member function 'int SslContext::initSNI(void*)':
sslcontext.cpp:625:71: error: 'SSL_CTX_set_cert_cb' was not declared in this scope
     SSL_CTX_set_cert_cb(m_pCtx, SslConnection_ssl_servername_cb, param);
                                                                       ^
make[3]: *** [sslcontext.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by slawek-mazur** [comment]
root@c718110fcaea:~/openlitespeed-1.4.30# whereis openssl
openssl: /usr/bin/openssl /usr/include/openssl
root@c718110fcaea:~/openlitespeed-1.4.30# ./configure --with-openssl=/usr/bin/openssl > configure_out.log
./dlossl.sh: line 41: -k: command not found
tar: ossl.tar.gz: Cannot open: No such file or directory
tar: Error is not recoverable: exiting now
mv: cannot stat 'openssl-OpenSSL_1_0_2-stable': No such file or directory
rm: cannot remove 'ossl.tar.gz': No such file or directory
./dlossl.sh: line 46: cd: ssl: No such file or directory
sed: can't read ssl/s3_pkt.c: No such file or directory
./dlossl.sh: line 48: ./config: No such file or directory
make: *** No rule to make target `depend'.  Stop.
sslcontext.cpp: In member function 'int SslContext::initSNI(void*)':
sslcontext.cpp:625:71: error: 'SSL_CTX_set_cert_cb' was not declared in this scope
     SSL_CTX_set_cert_cb(m_pCtx, SslConnection_ssl_servername_cb, param);
                                                                       ^
make[3]: *** [sslcontext.o] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all] Error 2
make: *** [all-recursive] Error 1

**Comment by darkspadez** [comment]
Can you make sure the packages `which` and `curl` are installed and see if it fixes the issue?

**Comment by slawek-mazur** [comment]
`curl` was the missing part. having `curl` installed one doesn't even have to manually build OpenSSL in 1.0.2n version. 

`apt -y install wget make gcc curl`

```
openssl version
OpenSSL 1.0.1f 6 Jan 2014
``` 

works perfectly well.

thanks man!
