### ISSUE TITLE
Cannot set Expires header

### ISSUE THREAD

**Issue by Tropicalista** [litespeedtech/openlitespeed#90]
I have this htaccess:

```ExpiresActive On

ExpiresDefault "access plus 1 month"

ExpiresByType text/html "access plus 1 day"
ExpiresByType text/css "access plus 1 day"
```

The header is not sent. I have enabled expires both at server and virtual host level.

I think it's a bug.

**Comment by gduan** [comment]
Only LiteSpeed Enterprise support .htaccess. However, OpenLiteSpeed does support rewire rules. You can enable rewrite rules in virtualhost or context of virtualhost section.
-- http://open.litespeedtech.com/mediawiki/index.php/Help:FAQ_OLS

**Comment by Tropicalista** [comment]
Hi, I've reported a more detailed explanation here: https://www.litespeedtech.com/support/forum/threads/setting-expires-cache-control-headers-seems-buggy.15964/#post-101098

I think the bug is related to wordpress cache plugin. 

Setting expires header on virtual host level does not work.

**Comment by LQ2-apostrophe** [comment]
OpenLiteSpeed only supports rewrite rules in `.htaccess` files. Please visit *General* tab of your virtual host, then change expires settings for that virtual host there.

**Comment by litespeedtech** [comment]
The latest release fixed some relative bugs.
