### ISSUE TITLE
Cannot read server log from admin dashboard

### ISSUE THREAD

**Issue by LQ2-apostrophe** [litespeedtech/openlitespeed#91]
I'm using Ubuntu Server 16.04 LTS. Until OLSWS 1.4.29, I can easily read server logs from the dashboard. Versions 1.4.30 and version 1.5.0 RC(1 & 2) just don't let me see the details of the server log.

I can still see the file size. `chmod` settings for all the logs are all 644. I have tried changing owners and groups for those files to `lsadm:lsadm`, `nobody:nogroup`. But this problem still persist.

**Comment by litespeedtech** [comment]
This is a bug due to some log format changes, it will be fixed soon and we will release a patch for it once it is fixed.

**Comment by LQ2-apostrophe** [comment]
I have tested the latest commit: `3de1d7aabec06c1baa887267cd1b9cc66f0eee94`. This problem has been fixed by this commit. Thank you!
