### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by AiraYumi** [litespeedtech/openlitespeed#92]
~~~
aclocal
automake --add-missing
./configure --with-user=**** --with-group=**** --enable-http2
make
~~~

An error will occur during execution of the make command.

~~~
/bin/bash: AR@: command not found
~~~

libsocket.a
libspdy.a
libsslpp.a
libssi.a

AND

~~~
/bin/bash: LIBTOOL@: command not found
~~~

cache.lo

Please Fix.

**Comment by LQ2-apostrophe** [comment]
Which Linux distro are you on?

`ar` is in `binutils` package, so you need to install that package. Also, you can get `libtool` by installing `libtool-bin` package.

**Comment by AiraYumi** [comment]
Thanks.

I use Debian 9.
I installed "libtool" and "libtool-bin".
Compilation has progressed, but on the way it displayed "libtool: Version mismatch error.".

Command Excecution.

~~~
autoreconf -fvi
~~~

It progressed to the end.
However, "aclocal", "automake", "libtool" do not match in the latest version on the way.

In Debian 9 the following versions will be installed.

~~~
automake 1.15
aclocal 1.15
libtool 2.4.6
~~~

I think that it is better to correspond to these tools.

**Comment by qtwrk** [comment]
just tried on a debian 9.4 , 

```
root@vps:~/openlitespeed-1.4.30# libtool --version
libtool (GNU libtool) 2.4.6

root@vps:~/openlitespeed-1.4.30# automake --version
automake (GNU automake) 1.15

root@vps:~/openlitespeed-1.4.30# aclocal --version
aclocal (GNU automake) 1.15
```

which version you were compiling ?   1.4.30 or 1.5 RC2?

**Comment by AiraYumi** [comment]
I installed "1.5 RC 2".
I think that it was the same symptom in 1.4.30.

**Comment by qtwrk** [comment]
So I tried again on debian 9.4 , Digitao ocean droplets 

there was some missing packages , so I added into my command line , and please try this from scratch 


```
apt-get install build-essential
apt-get install rcs libpcre3-dev libexpat1-dev libssl-dev libgeoip-dev libudns-dev zlib1g-dev libxml2 libxml2-dev libpng-dev openssl g++ automake make wget curl libtool-bin

wget http://open.litespeedtech.com/packages/openlitespeed-1.5.0rc2.tgz
tar xzvf openlitespeed-1.5.0rc2.tgz
cd openlitespeed-1.5.0
./configure --with-openssl=/usr/bin/openssl --with-user=www --with-group=www --enable-http2
make
```

see if this works out or not

**Comment by litespeedtech** [comment]
Actually you can install through 
./configure .... ; make; make install
even if you do not have the autotools installed.
The ar error should be OK if finally you have the openssl library files created.
Usually user has such errors, but installation is all right.
Please let me know if you still have some issues.
Thanks.
David
