### ISSUE TITLE
Saving rewrite Rules creates malformed config

### ISSUE THREAD

**Issue by stevekim** [litespeedtech/openlitespeed#93]
v1.4.30.

In admin panel, Virtual Host > Rewrite, when I add Rewrite Rules, it creates malformed rules in vhconf.conf. For example, when I add "rewriteFile /vagrant/.htaccess" to the admin ui interface and save, then it creates:

rewrite {

  enable 1

  logLevel 9

  rewriteFile /vagrant/.htaccess

}

This wouldn't work. This should create something like:

rewrite {

  enable 1

  logLevel 9

  rules rewriteFile /vagrant/.htaccess

}

I've tried with regualr rewrite rules and same thing happens. it doesn't work at all.

**Comment by usmannasir** [comment]
Meanwhile, you can use:

rewrite  {
  enable                  1
  rules                   <<<END_rules
rewriteFile           /vagrant/.htaccess
  END_rules
}

**Comment by stevekim** [comment]
Hi David,

Thanks for your reply. I can confirm that the web server can read the .htaccess file with no problem.
Well the issue didn't happen in 1.4.2x version. There must be something wrong with 1.4.3x verison.
I can put in the suggested config format, but I guess it should be supported by the admin interface. 

Thanks
Steve

**Comment by litespeedtech** [comment]
Steve,
for 1.4.3x, we removed the requirement of surrounding the actual rules with rules tag. When you save in webadmin, it will skip the rules tag output. This will make config file simpler. So it is as designed, and should be backward compatible.
You can test again with latest 1.4.3.x, and let us know if you still have issues. If good, please close this issue.
Thanks,
Lauren
