### ISSUE TITLE
Large chain of RewriteCond crashed whole server without any logs

### ISSUE THREAD

**Issue by kiler129** [litespeedtech/openlitespeed#94]
I attempted pasting large (~300KB) .htaccess file to OpenLSWS "Rewrite" tab and the result was inaccessible web panel. I started debugging and I found certain combination of rules crashes whole lsws. It attempts to start, logs every rule and then suddenly it dies without any logs.

I tried enabling debug logs - nothing there either. Process starts and just dies unexpectedly. There are no segfaults, it's just exits with code 1. I tried modifying my rewrite rules and see if I can isolate one, but changing the rules in pseudo-random places can make the server start.

I think giving the fact how weirdly the server reacts to change of rules it may be something related to catastrophic backtracking handling, since the ruleset I'm testing contains a lot of rules like:

```
RewriteCond %{HTTP_HOST} <bad regex> [NC] -> repeated ~100 times with different domains
RewriteRule ....
```

I was able to find a combination of artificially generated rules causing that behavior: https://pastebin.com/sXrriNRp

**Comment by litespeedtech** [comment]
What platform you are using?
I just did some tests about 1.4.30 code with the large .htacess file and also with the large block paste into rewrite rule text field, and both are good. No any issue occurred.
Please try to give us more info and do more tests.
Thanks.
David

**Comment by kiler129** [comment]
@litespeedtech 

I'm using xUbuntu 17.10 64 bit running as VMWare guest. Currently utilizing `Linux 4.13.0-38-generic #43-Ubuntu SMP Wed Mar 14 15:20:44 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`.
I use 1.4.29 compiled from source downloaded 2018/01/10 as tar.gz. I used `./configure --with-lsphp7 --with-exampleport=80 --with-adminport=81` to configure. Let me know what other details may be useful.

The thing is it's not just about the size of file, but long chain of poor `RewriteCond`. It looks like something crashes inside of lsws core producing no output. The issue arises after you paste rules and restart the server (even if rewrite flag is set to 0).

I can attach gdb if you want, but I need some aid what and how to look for the problem.

**Comment by litespeedtech** [comment]
Hi Greg,

I did see these errors on ubuntu 17.10 and have fixed them. 
I just uploaded a new commit to V1_4 branch.
please try it and let me know the result.

Thanks.
David

**Comment by kiler129** [comment]
@litespeedtech Sorry for such a long response. It seems to be fixed David.

Thank you!
