### ISSUE TITLE
Rewrite Rule Processing Order Differs From Apache

### ISSUE THREAD

**Issue by kiler129** [litespeedtech/openlitespeed#95]
Let's use an example of such rewrite rules put in `.htaccess`:

```
RewriteEngine on
RewriteRule ^(.*)/(.*)/(.*)\.html$ index.php?first=1 [L]
RewriteRule (.*)\.html index.php?second=1 [L]
```

and version adjusted for OpenLSWS rewrite:
```
rewrite  {
  enable                  1

<Directory "/">
    RewriteRule ^(.*)/(.*)/(.*)\.html$ index.php?first=1 [L]
    RewriteRule (.*)\.html index.php?second=1 [L]
</Directory>
}
```

I expected both rulesets to get me to `index.php?second=1` while matched at `/a/b.html` URL, however while Apache does that the OpenLSWS instance behaves differently and points to ` index.php?first=1` instead.

**Comment by litespeedtech** [comment]
Please use the latest release and it was fixed.
